/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "bl?hvit",
antiquewhite: "antikk hvit",
aqua: "akva",
aquamarine: "akvamarin",
azure: "asur",
beige: "beige",
bisque: "gulrosa",
black: "svart",
blanchedalmond: "lys mandel",
blue: "bl?",
blueviolet: "bl?fiolett",
brown: "brun",
burlywood: "matt mellombrun",
cadetblue: "m?rk gr?nnbl?",
chartreuse: "l?vgr?nn",
chocolate: "sjokolade",
coral: "korall",
cornflowerblue: "kornbl?",
cornsilk: "cornsilk",
crimson: "karmosinr?dt",
cyan: "cyan",
darkblue: "m?rk bl?",
darkcyan: "m?rk cyan",
darkgoldenrod: "m?rk gyldenris",
darkgray: "m?rk gr?",
darkgreen: "m?rk gr?nn",
darkgrey: "m?rk gr?", // same as darkgray
darkkhaki: "m?rk khaki",
darkmagenta: "m?rk magenta",
darkolivegreen: "m?rk olivengr?nn",
darkorange: "m?rk oransje",
darkorchid: "m?rk orkide",
darkred: "m?rk r?d",
darksalmon: "m?rk lakserosa",
darkseagreen: "m?rk sj?gr?nn",
darkslateblue: "m?rk skiferbl?",
darkslategray: "m?rk skifergr?",
darkslategrey: "m?rk skifergr?", // same as darkslategray
darkturquoise: "m?rk turkis",
darkviolet: "m?rk fiolett",
deeppink: "dyp rosa",
deepskyblue: "dyp himmelbl?",
dimgray: "m?rk m?rkegr?",
dimgrey: "m?rk m?rkegr?", // same as dimgray
dodgerblue: "lys havbl?",
firebrick: "mursteinsr?d",
floralwhite: "blomsterhvit",
forestgreen: "skoggr?nn",
fuchsia: "fuksia",
gainsboro: "lys lys gr?",
ghostwhite: "egghvit",
gold: "gull",
goldenrod: "gyldenris",
gray: "gr?",
green: "gr?nn",
greenyellow: "gulgr?nn",
grey: "gr?", // same as gray
honeydew: "gr?nnhvit",
hotpink: "halvm?rk rosa",
indianred: "rustr?d",
indigo: "indigo",
ivory: "elfenbenshvit",
khaki: "khaki",
lavender: "lavendel",
lavenderblush: "lillahvit",
lawngreen: "plengr?nn",
lemonchiffon: "ferskenfarget",
lightblue: "lys bl?",
lightcoral: "lys korall",
lightcyan: "lys cyan",
lightgoldenrodyellow: "lys gyldenrisgul",
lightgray: "lys gr?",
lightgreen: "lys gr?nn",
lightgrey: "lys gr?", // same as lightgray
lightpink: "lys rosa",
lightsalmon: "lys lakserosa",
lightseagreen: "lys sj?gr?nn",
lightskyblue: "lys himmelbl?",
lightslategray: "lys skifergr?",
lightslategrey: "lys skifergr?", // same as lightslategray
lightsteelblue: "lys st?lbl?",
lightyellow: "lys gul",
lime: "lime",
limegreen: "limegr?nn",
linen: "lin",
magenta: "magenta",
maroon: "r?dbrun",
mediumaquamarine: "middels akvamarin",
mediumblue: "mellombl?",
mediumorchid: "middels orkide",
mediumpurple: "middels purpur",
mediumseagreen: "middels sj?gr?nn",
mediumslateblue: "middels skiferbl?",
mediumspringgreen: "middels v?rgr?nn",
mediumturquoise: "middels turkis",
mediumvioletred: "middels fiolettr?d",
midnightblue: "midnattsbl?",
mintcream: "mintkrem",
mistyrose: "lys rosenr?d",
moccasin: "lys gulbrun",
navajowhite: "gulbrun",
navy: "marinebl?",
oldlace: "kniplingshvit",
olive: "oliven",
olivedrab: "middels olivengr?nn",
orange: "oransje",
orangered: "r?doransje",
orchid: "orkide",
palegoldenrod: "svak gyldenris",
palegreen: "svak gr?nn",
paleturquoise: "svak turkis",
palevioletred: "svak fiolettr?d",
papayawhip: "lys papaya",
peachpuff: "brunrosa",
peru: "lys n?ttebrun",
pink: "rosa",
plum: "plommefarget",
powderblue: "lys gr?nnbl?",
purple: "purpur",
red: "r?d",
rosybrown: "brunlilla",
royalblue: "kongebl?",
saddlebrown: "m?rk n?ttebrun",
salmon: "lakserosa",
sandybrown: "sandbrun",
seagreen: "sj?gr?nn",
seashell: "skjellhvit",
sienna: "n?ttebrun",
silver: "s?lvfarget",
skyblue: "himmelbl?",
slateblue: "skiferbl?",
slategray: "skifergr?",
slategrey: "skifergr?", // same as slategray
snow: "sn?hvit",
springgreen: "v?rgr?nn",
steelblue: "st?lbl?",
tan: "matt mellombrun",
teal: "m?rk gr?nnbl?",
thistle: "lys gr?lilla",
tomato: "tomatr?d",
turquoise: "turkis",
violet: "fiolett",
wheat: "varm sienna",
white: "hvit",
whitesmoke: "r?ykhvit",
yellow: "gul",
yellowgreen: "gulgr?nn"
})
//end v1.x content
);
