/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"yl?salainen huutomerkki",
	cent:"sentin merkki",
	pound:"punnan merkki",
	curren:"valuuttamerkki",
	yen:"jenin merkki\nyuanin merkki",
	brvbar:"katkopystyviiva",
	sect:"pyk?l?merkki",
	uml:"treema\ntilaa viev? treema",
	copy:"tekij?noikeusmerkki",
	ordf:"feminiinisen j?rjestysluvun merkki",
	laquo:"vasemmalle osoittava kaksinkertainen kulmalainausmerkki\nvasemmalle osoittava kulmalainausmerkki",
	not:"negaation merkki\nei-merkki",
	shy:"ehdollinen tavuviiva\npehme? tavuviiva\ntavutusvihje",
	reg:"rekister?idyn tavaramerkin merkki\nrekister?ity tavaramerkki -merkki",
	macr:"macron\nviiva-aksentti\npituusmerkki\np??llekk?isviiva",
	deg:"astemerkki",
	plusmn:"plus-miinus-merkki\nplus- tai miinusmerkki",
	sup2:"yl?indeksi kaksi\nneli?\ntoinen potenssi",
	sup3:"yl?indeksi kolme\nkuutio\nkolmas potenssi",
	acute:"akuutti\nakuuttiaksentti",
	micro:"mikro-merkki",
	para:"kappaleen merkki\nkappalemerkki",
	middot:"keskipiste\nrivinkeskinen piste\ngeorgialainen pilkku\nkreikkalainen keskipiste",
	cedil:"sedilji\ntilaa viev? sedilji\ncedilla",
	sup1:"yl?indeksi yksi",
	ordm:"maskuliinisen j?rjestysluvun merkki",
	raquo:"oikealle osoittava kaksinkertainen kulmalainausmerkki\noikealle osoittava kulmalainausmerkki",
	frac14:"nelj?sosan merkki\nnelj?sosa",
	frac12:"puolikkaan merkki\npuolikas",
	frac34:"kolmen nelj?sosan merkki\nkolme nelj?sosaa",
	iquest:"yl?salainen kysymysmerkki",
	Agrave:"iso A ja gravis\nversaali A ja gravis",
	Aacute:"iso A ja akuutti\niso A ja akuuttiaksentti\nversaali A ja akuutti",
	Acirc:"iso A ja sirkumfleksi\nversaali A ja sirkumfleksi",
	Atilde:"iso A ja tilde\nversaali A ja tilde\niso A ja aaltoviiva\nversaali A ja aaltoviiva",
	Auml:"iso ?\nversaali ?",
	Aring:"iso ?\nversaali ?\niso ruotsalainen o\nversaali ruotsalainen o",
	AElig:"iso AE\nversaali AE\niso ligatuuri AE\nversaaliligatuuri AE\niso tanskalainen ?\nversaali tanskalainen ?",
	Ccedil:"iso C ja sedilji\nversaali C ja sedilji",
	Egrave:"iso E ja gravis\nversaali E ja gravis",
	Eacute:"iso E ja akuutti\niso E ja akuuttiaksentti\nversaali E ja akuutti",
	Ecirc:"iso E ja sirkumfleksi\nversaali E ja sirkumfleksi",
	Euml:"iso E ja treema\nversaali E ja treema",
	Igrave:"iso I ja gravis\nversaali I ja gravis",
	Iacute:"iso I ja akuutti\niso I ja akuuttiaksentti\nversaali I ja akuutti",
	Icirc:"iso I ja sirkumfleksi\nversaali I ja sirkumfleksi",
	Iuml:"iso I ja treema\nversaali I ja treema",
	ETH:"iso eth\nversaali eth",
	Ntilde:"iso N ja tilde\nversaali N ja tilde\niso N ja aaltoviiva\nversaali N ja aaltoviiva",
	Ograve:"iso O ja gravis\nversaali O ja gravis",
	Oacute:"iso O ja akuutti\niso O ja akuuttiaksentti\nversaali O ja akuutti",
	Ocirc:"iso O ja sirkumfleksi\nversaali O ja sirkumfleksi",
	Otilde:"iso O ja tilde\nversaali O ja tilde\niso O ja aaltoviiva\nversaali O ja aaltoviiva",
	Ouml:"iso O ja treema\nversaali O ja treema",
	times:"kertomerkki",
	Oslash:"iso tanskalainen ?\nversaali tanskalainen ?\niso O ja vinoviiva\nversaali O ja vinoviiva\niso O, jossa on poikkiviiva\nversaali O, jossa on poikkiviiva",
	Ugrave:"iso U ja gravis\nversaali U ja gravis",
	Uacute:"iso U ja akuutti\niso U ja akuuttiaksentti\nversaali U ja akuutti",
	Ucirc:"iso U ja sirkumfleksi\nversaali U ja sirkumfleksi",
	Uuml:"iso U ja treema\nversaali U ja treema\niso saksalainen y\nversaali saksalainen y",
	Yacute:"iso Y ja akuutti\niso Y ja akuuttiaksentti\nversaali Y ja akuutti",
	THORN:"iso thorn\nversaali thorn",
	szlig:"pieni kaksois-s\ngemena kaksois-s\npieni saksalainen kaksois-s\ngemena saksalainen kaksois-s",
	agrave:"pieni a ja gravis\ngemena a ja gravis",
	aacute:"pieni a ja akuutti\ngemena a ja akuutti\npieni a ja akuuttiaksentti",
	acirc:"pieni a ja sirkumfleksi\ngemena a ja sirkumfleksi",
	atilde:"pieni a ja tilde\ngemena a ja tilde\npieni a ja aaltoviiva\ngemena a ja aaltoviiva",
	auml:"pieni ?\ngemena ?",
	aring:"pieni ?\ngemena ?\npieni ruotsalainen o\ngemena ruotsalainen o",
	aelig:"pieni ae\ngemena ae\npieni ligatuuri ae\ngemenaligatuuri ae\npieni tanskalainen ?\ngemena tanskalainen ?",
	ccedil:"pieni c ja sedilji\ngemena c ja sedilji",
	egrave:"pieni e ja gravis\ngemena e ja gravis",
	eacute:"pieni e ja akuutti\ngemena e ja akuutti\npieni e ja akuuttiaksentti",
	ecirc:"pieni e ja sirkumfleksi\ngemena e ja sirkumfleksi",
	euml:"pieni e ja treema\ngemena e ja treema",
	igrave:"pieni i ja gravis\ngemena e ja gravis",
	iacute:"pieni i ja akuutti\ngemena i ja akuutti\npieni i ja akuuttiaksentti",
	icirc:"pieni i ja sirkumfleksi\ngemena i ja sirkumfleksi",
	iuml:"pieni i ja treema\ngemena i ja treema",
	eth:"pieni eth\ngemena eth",
	ntilde:"pieni n ja tilde\ngemena n ja tilde\npieni n ja aaltoviiva\ngemena n ja aaltoviiva",
	ograve:"pieni o ja gravis\ngemena o ja gravis",
	oacute:"pieni o ja akuutti\ngemena o ja akuutti\npieni o ja akuuttiaksentti",
	ocirc:"pieni o ja sirkumfleksi\ngemena o ja sirkumfleksi",
	otilde:"pieni o ja tilde\ngemena o ja tilde\npieni o ja aaltoviiva\ngemena o ja aaltoviiva",
	ouml:"pieni ?\ngemena ?",
	divide:"jakomerkki",
	oslash:"pieni tanskalainen ?\ngemena tanskalainen ?\npieni o ja vinoviiva\ngemena o ja vinoviiva\npieni o, jossa on poikkiviiva\ngemena o, jossa on poikkiviiva",
	ugrave:"pieni u ja gravis\ngemena u ja gravis",
	uacute:"pieni u ja akuutti\ngemena u ja akuutti\npieni u ja akuuttiaksentti",
	ucirc:"pieni u ja sirkumfleksi\ngemena u ja sirkumfleksi",
	uuml:"pieni u ja treema\ngemena u ja treema\npieni saksalainen y\ngemena saksalainen y",
	yacute:"pieni y ja akuutti\ngemena y ja akuutti\npieni y ja akuuttiaksentti",
	thorn:"pieni thorn\ngemena thorn",
	yuml:"pieni y ja treema\ngemena y ja treema",

// Greek Characters and Symbols
	fnof:"pieni f, jossa koukku\ngemena f, jossa koukku\nfunktio\nguldeni",
	Alpha:"iso alfa\nversaali alfa",
	Beta:"iso beeta\nversaali beeta",
	Gamma:"iso gamma\nversaali gamma",
	Delta:"iso delta\nversaali delta",
	Epsilon:"iso epsilon\nversaali epsilon",
	Zeta:"iso zeeta\nversaali zeeta",
	Eta:"iso eeta\nversaali eeta",
	Theta:"iso theeta\nversaali theeta",
	Iota:"iso ioota\nversaali ioota",
	Kappa:"iso kappa\nversaali kappa",
	Lambda:"iso lambda\nversaali lambda",
	Mu:"iso myy\nversaali myy",
	Nu:"iso nyy\nversaali nyy",
	Xi:"iso ksii\nversaali ksii",
	Omicron:"iso omikron\nversaali omikron",
	Pi:"iso pii\nversaali pii",
	Rho:"iso rhoo\nversaali rhoo",
	Sigma:"iso sigma\nversaali sigma",
	Tau:"iso tau\nversaali tau",
	Upsilon:"iso ypsilon\nversaali ypsilon",
	Phi:"iso fii\nversaali fii",
	Chi:"iso khii\nversaali khii",
	Psi:"iso psii\nversaali psii",
	Omega:"iso oomega\nversaali oomega",
	alpha:"pieni alfa\ngemena alfa",
	beta:"pieni beeta\ngemena beeta",
	gamma:"pieni gamma\ngemena gamma",
	delta:"pieni delta\ngemena delta",
	epsilon:"pieni epsilon\ngemena epsilon",
	zeta:"pieni zeeta\ngemena zeeta",
	eta:"pieni eeta\ngemena eeta",
	theta:"pieni theeta\ngemena theeta",
	iota:"pieni ioota\ngemena ioota",
	kappa:"pieni kappa\ngemena kappa",
	lambda:"pieni lambda\ngemena lambda",
	mu:"pieni myy\ngemena myy",
	nu:"pieni nyy\ngemena nyy",
	xi:"pieni ksii\ngemena ksii",
	omicron:"pieni omikron\ngemena omikron",
	pi:"pieni pii\ngemena pii",
	rho:"pieni rhoo\ngemena rhoo",
	sigmaf:"pieni sananloppuinen sigma\ngemena sananloppuinen sigma",
	sigma:"pieni sigma\ngemena sigma",
	tau:"pieni tau\ngemena tau",
	upsilon:"pieni ypsilon\ngemena ypsilon",
	phi:"pieni fii\ngemena fii",
	chi:"pieni khii\ngemena khii",
	psi:"pieni psii\ngemena psii",
	omega:"pieni oomega\ngemena oomega",
	thetasym:"pieni theeta\ngemena theeta",
	upsih:"ypsilon, jossa koukku",
	piv:"pii-merkki",
	bull:"luetelmamerkki\nluetelmapallo\npieni musta ympyr?",
	hellip:"kolme pistett?\nkolme pistett? vaakasuunnassa\nellipsi",
	prime:"yl?puolinen indeksointipilkku\nindeksointipilkku\nminuutit\njalat",
	Prime:"kaksinkertainen yl?puolinen indeksointipilkku\nsekunnit\ntuumat",
	oline:"yl?viiva",
	frasl:"murtoluvun vinoviiva\nmurtolukuviiva",
	weierp:"iso kaunokirjoitus-P\npotenssijoukko\nWeierstrassin p",
	image:"goottilainen iso I\ngoottilainen versaali I\nimaginaarinen osa",
	real:"goottilainen iso R\ngoottilainen versaali R\nreaaliosa",
	trade:"tavaramerkki\ntavaramerkin merkki",
	alefsym:"alef-merkki\nalef\nensimm?inen transfiniittinen kardinaali",
	larr:"vasen nuoli\nnuoli vasemmalle",
	uarr:"yl?nuoli\nnuoli yl?s\nyl?sp?in osoittava nuoli",
	rarr:"oikea nuoli\nnuoli oikealle",
	darr:"alanuoli\nnuoli alas\nalasp?in osoittava nuoli",
	harr:"nuoli vasemmalle ja oikealle",
	crarr:"rivinvaihtomerkki",
	lArr:"kaksoisnuoli vasemmalle",
	uArr:"kaksoisnuoli yl?s",
	rArr:"kaksoisnuoli oikealle",
	dArr:"kaksoisnuoli alas",
	hArr:"kaksoisnuoli vasemmalle ja oikealle",
	forall:"kaikkikvanttori\nuniversaalikvanttori",
	part:"osittaisderivaatta",
	exist:"olemassaolokvanttori",
	empty:"tyhj? joukko\nhalkaisija",
	nabla:"nabla\ngradientti",
	isin:"joukkoon kuulumisen merkki",
	notin:"joukkoon kuulumattomuuden merkki",
	ni:"k??nteinen joukkoon kuulumisen merkki",
	prod:"tulo\ntulon merkki",
	sum:"summa",
	minus:"miinusmerkki",
	lowast:"t?hti\nasteriski",
	radic:"neli?juuri\njuurimerkki",
	prop:"verrannollinen",
	infin:"??ret?n\n??rett?m?n merkki",
	ang:"kulma",
	and:"looginen ja-merkki",
	or:"looginen tai-merkki",
	cap:"leikkauksen merkki\nleikkaus",
	cup:"yhdisteen merkki\nyhdiste\nunioni","int":"integraalimerkki\nintegraali",
	there4:"loogisen seuraamuksen merkki\njoten\nsiis",
	sim:"tildeoperaattori\nlikiarvo",
	cong:"suunnilleen yht? suuri kuin -merkki",
	asymp:"likimain yht? suuri kuin -merkki\nasymptoottinen",
	ne:"eri suuri kuin -merkki\nerisuuruusmerkki",
	equiv:"identtisesti yht? suuri kuin -merkki",
	le:"pienempi tai yht? suuri kuin -merkki",
	ge:"suurempi tai yht? suuri kuin -merkki",
	sub:"osajoukon merkki",
	sup:"ylijoukon merkki",
	nsub:"osajoukkosuhteen negaation merkki",
	sube:"osajoukkosuhteen tai yht?l?isyyden merkki",
	supe:"ylijoukkosuhteen tai yht?l?isyyden merkki",
	oplus:"ympyr?ss? oleva plusmerkki\nsuora summa",
	otimes:"ympyr?ss? oleva kertomerkki\nvektoritulo\nristitulo",
	perp:"kohtisuoruusmerkki",
	sdot:"pisteoperaattori",
	lceil:"vasen kattosymboli",
	rceil:"oikea kattosymboli",
	lfloor:"vasen lattiasymboli",
	rfloor:"oikea lattiasymboli",
	lang:"vasemmalle osoittava kulmasulje",
	rang:"oikealle osoittava kulmasulje",
	loz:"vinoneli?\nnelikovero",
	spades:"musta korttipakan pata",
	clubs:"musta korttipakan risti\napila",
	hearts:"musta korttipakan hertta\nsyd?n",
	diams:"musta korttipakan ruutu",
	OElig:"iso ligatuuri OE\nversaaliligatuuri OE",
	oelig:"pieni ligatuuri oe\ngemenaligatuuri oe",
	Scaron:"iso hattu-S\nversaali hattu-S",
	scaron:"pieni hattu-s\ngemena hattu-s",
	Yuml:"iso Y ja treema\nversaali Y ja treema",
	circ:"tarkkeenomainen sirkumfleksi",
	tilde:"pieni tilde",
	ensp:"n-v?li\nn-kirjaimen levyinen v?li",
	emsp:"m-v?li\nm-kirjaimen levyinen v?li",
	thinsp:"kapea v?li",
	zwnj:"leveydet?n erottava merkki",
	zwj:"leveydet?n yhdist?v? merkki",
	lrm:"vasemmalta oikealle -merkki",
	rlm:"oikealta vasemmalle -merkki",
	ndash:"n-viiva\nlyhyt ajatusviiva",
	mdash:"m-viiva\npitk? ajatusviiva",
	lsquo:"yl?salainen puolilainausmerkki",
	rsquo:"puolilainausmerkki",
	sbquo:"rivinalinen puolilainausmerkki",
	ldquo:"yl?salainen kokolainausmerkki",
	rdquo:"kokolainausmerkki",
	bdquo:"rivinalinen kokolainausmerkki",
	dagger:"risti",
	Dagger:"kaksoisristi",
	permil:"promillemerkki",
	lsaquo:"vasemmalle osoittava kulmapuolilainausmerkki",
	rsaquo:"oikealle osoittava kulmapuolilainausmerkki",
	euro:"euron merkki"
})

//end v1.x content
);
