/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "alice blue",
antiquewhite: "antique white",
aqua: "aqua",
aquamarine: "aquamarine",
azure: "azuriu",
beige: "bej",
bisque: "bisque",
black: "negru",
blanchedalmond: "blanched almond",
blue: "albastru",
blueviolet: "albastru-violet",
brown: "maro",
burlywood: "burlywood",
cadetblue: "cadet blue",
chartreuse: "chartreuse",
chocolate: "ciocolat?",
coral: "coral",
cornflowerblue: "cornflower blue",
cornsilk: "cornsilk",
crimson: "crimson",
cyan: "cyan",
darkblue: "albastru ?nchis",
darkcyan: "cyan ?nchis",
darkgoldenrod: "goldenrod ?nchis",
darkgray: "cenu?iu ?nchis",
darkgreen: "verde ?nchis",
darkgrey: "gri ?nchis", // same as darkgray
darkkhaki: "kaki ?nchis",
darkmagenta: "magenta ?nchis",
darkolivegreen: "verde oliv ?nchis",
darkorange: "portocaliu ?nchis",
darkorchid: "dark orchid",
darkred: "ro?u ?nchis",
darksalmon: "dark salmon",
darkseagreen: "dark sea green",
darkslateblue: "dark slate blue",
darkslategray: "dark slate gray",
darkslategrey: "dark slate gray", // same as darkslategray
darkturquoise: "dark turquoise",
darkviolet: "violet ?nchis",
deeppink: "roz ?nchis",
deepskyblue: "deep sky blue",
dimgray: "dim gray",
dimgrey: "dim gray", // same as dimgray
dodgerblue: "dodger blue",
firebrick: "fire brick",
floralwhite: "floral white",
forestgreen: "verde p?dure",
fuchsia: "fuchsia",
gainsboro: "gainsboro",
ghostwhite: "ghost white",
gold: "auriu",
goldenrod: "goldenrod",
gray: "cenu?iu",
green: "verde",
greenyellow: "verde-galben",
grey: "gri", // same as gray
honeydew: "honeydew",
hotpink: "roz aprins",
indianred: "ro?u indian",
indigo: "indigo",
ivory: "ivoriu",
khaki: "kaki",
lavender: "lev?n?ic?",
lavenderblush: "lavender blush",
lawngreen: "lawn green",
lemonchiffon: "lemon chiffon",
lightblue: "albastru deschis",
lightcoral: "coral deschis",
lightcyan: "cyan deschis",
lightgoldenrodyellow: "light goldenrod yellow",
lightgray: "gri deschis",
lightgreen: "verde deschis",
lightgrey: "gri deschis", // same as lightgray
lightpink: "roz deschis",
lightsalmon: "somon deschis",
lightseagreen: "verde marin deschis",
lightskyblue: "albastru cer deschis",
lightslategray: "light slate gray",
lightslategrey: "light slate gray", // same as lightslategray
lightsteelblue: "light steel blue",
lightyellow: "galben deschis",
lime: "lime",
limegreen: "verde lime",
linen: "linen",
magenta: "magenta",
maroon: "maroon",
mediumaquamarine: "medium aquamarine",
mediumblue: "medium blue",
mediumorchid: "medium orchid",
mediumpurple: "medium purple",
mediumseagreen: "medium sea green",
mediumslateblue: "medium slate blue",
mediumspringgreen: "medium spring green",
mediumturquoise: "medium turquoise",
mediumvioletred: "medium violet-red",
midnightblue: "midnight blue",
mintcream: "mint cream",
mistyrose: "trandafiriu obscur",
moccasin: "moccasin",
navajowhite: "navajo white",
navy: "navy",
oldlace: "old lace",
olive: "oliv",
olivedrab: "maron-g?lbui oliv",
orange: "portocaliu",
orangered: "ro?u portocaliu",
orchid: "orhidee",
palegoldenrod: "solidago pal",
palegreen: "verde pal",
paleturquoise: "turquoise pal",
palevioletred: "ro?u violet pal",
papayawhip: "papaya whip",
peachpuff: "puf de piersic?",
peru: "peru",
pink: "roz",
plum: "prun?",
powderblue: "albastru pudr?",
purple: "purpur?",
red: "ro?u",
rosybrown: "maro trandafiriu",
royalblue: "albastru regal",
saddlebrown: "maro de ?a",
salmon: "somon",
sandybrown: "maro nisipiu",
seagreen: "verde marin",
seashell: "cochilie",
sienna: "sienna",
silver: "argintiu",
skyblue: "albastru de cer",
slateblue: "albastru ardezie",
slategray: "gri ardezie",
slategrey: "gri ardezie", // same as slategray
snow: "z?pad?",
springgreen: "verde de prim?var?",
steelblue: "albastru metalic",
tan: "tan",
teal: "li?i??",
thistle: "ciulin",
tomato: "ro?ie",
turquoise: "turquoise",
violet: "violet",
wheat: "gr?u",
white: "alb",
whitesmoke: "fum alb",
yellow: "galben",
yellowgreen: "verde galben"
})

//end v1.x content
);
