/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"obrnjen klicaj ",
	cent:"znak za cent ",
	pound:"znak za funt ",
	curren:"znak za valuto ",
	yen:"znak za jen\njuan ",
	brvbar:"prekinjena ?rta\nprekinjena navpi?na ?rta ",
	sect:"znak za odsek ",
	uml:"diareza\ndiareza z razmikom ",
	copy:"znak za avtorske pravice ",
	ordf:"?enski ordinalni indikator ",
	laquo:"dvojni narekovaj, ki ka?e v levo smer ",
	not:"znak za ne ",
	shy:"pogojni deljaj ",
	reg:"znak za registrirano\nznak za registrirano blagovno znamko ",
	macr:"ravni preglas ",
	deg:"znak za stopinje ",
	plusmn:"znak plus-minus\nznak plus ali minus ",
	sup2:"nadpisana dve\nnadpisana ?tevka dve\nna kvadrat ",
	sup3:"nadpisana tri\nnadpisana ?tevka tri\nna kub ",
	acute:"ostrivec ",
	micro:"znak za mikro",
	para:"znak za paragraf",
	middot:"pika na sredini\nGeorgian comma\nGr?ka pika na sredini ",
	cedil:"cedila ",
	sup1:"nadpisana ena\nnadpisana ?tevka ena ",
	ordm:"mo?ki ordinalni indikator ",
	raquo:"dvojni narekovaj, ki ka?e v desno smer ",
	frac14:"pravi ulomek ena ?etrtina ",
	frac12:"pravi ulomek ena polovica ",
	frac34:"pravi ulomek tri ?etrtine ",
	iquest:"obrnjen vpra?aj ",
	Agrave:"Latinska velika ?rka A s krativcem ",
	Aacute:"Latinska velika ?rka A z ostrivcem ",
	Acirc:"Latinska velika ?rka A s cirkumfleksom ",
	Atilde:"Latinska velika ?rka A s tildo ",
	Auml:"Latinska velika ?rka A z diarezo ",
	Aring:"Latinska velika ?rka A s krogcem na vrhu ",
	AElig:"Latinska velika ?rka AE ",
	Ccedil:"Latinska velika ?rka C s cedilo ",
	Egrave:"Latinska velika ?rka E s krativcem ",
	Eacute:"Latinska velika ?rka E z ostrivcem ",
	Ecirc:"Latinska velika ?rka E s cirkumfleksom ",
	Euml:"Latinska velika ?rka E z diarezo ",
	Igrave:"Latinska velika ?rka I s krativcem ",
	Iacute:"Latinska velika ?rka I z ostrivcem ",
	Icirc:"Latinska velika ?rka I s cirkumfleksom ",
	Iuml:"Latinska velika ?rka I z diarezo ",
	ETH:"Latinska velika ?rka ETH ",
	Ntilde:"Latinska velika ?rka N s tildo ",
	Ograve:"Latinska velika ?rka O s krativcem ",
	Oacute:"Latinska velika ?rka O z ostrivcem ",
	Ocirc:"Latinska velika ?rka O s cirkumfleksom ",
	Otilde:"Latinska velika ?rka O s tildo ",
	Ouml:"Latinska velika ?rka O z diarezo ",
	times:"znak za mno?enje ",
	Oslash:"Po?evno pre?rtana latinska velika ?rka O ",
	Ugrave:"Latinska velika ?rka U s krativcem ",
	Uacute:"Latinska velika ?rka U z ostrivcem ",
	Ucirc:"Latinska velika ?rka U s cirkumfleksom ",
	Uuml:"Latinska velika ?rka U z diarezo ",
	Yacute:"Latinska velika ?rka Y z ostrivcem ",
	THORN:"Latinska velika ?rka THORN ",
	szlig:"Latinska majhna ?rka ostri s ",
	agrave:"Latinska majhna ?rka a s krativcem ",
	aacute:"Latinska majhna ?rka a z ostrivcem ",
	acirc:"Latinska majhna ?rka a s cirkumfleksom ",
	atilde:"Latinska majhna ?rka a s tildo ",
	auml:"Latinska majhna ?rka a z diarezo ",
	aring:"Latinska majhna ?rka a s krogcem na vrhu ",
	aelig:"Latinska majhna ?rka ae ",
	ccedil:"Latinska majhna ?rka c s cedilo ",
	egrave:"Latinska majhna ?rka e s krativcem ",
	eacute:"Latinska majhna ?rka e z ostrivcem ",
	ecirc:"Latinska majhna ?rka e s cirkumfleksom ",
	euml:"Latinska majhna ?rka e z diarezo ",
	igrave:"Latinska majhna ?rka i s krativcem ",
	iacute:"Latinska majhna ?rka i z ostrivcem ",
	icirc:"Latinska majhna ?rka i s cirkumfleksom ",
	iuml:"Latinska majhna ?rka i z diarezo ",
	eth:"Latinska majhna ?rka eth ",
	ntilde:"Latinska majhna ?rka n s tildo ",
	ograve:"Latinska majhna ?rka o s krativcem ",
	oacute:"Latinska majhna ?rka o z ostrivcem ",
	ocirc:"Latinska majhna ?rka o s cirkumfleksom ",
	otilde:"Latinska majhna ?rka o s tildo ",
	ouml:"Latinska majhna ?rka o z diarezo ",
	divide:"znak za deljenje ",
	oslash:"Po?evno pre?rtana latinska majhna ?rka o ",
	ugrave:"Latinska majhna ?rka u s krativcem ",
	uacute:"Latinska majhna ?rka u z ostrivcem ",
	ucirc:"Latinska majhna ?rka u s cirkumfleksom ",
	uuml:"Latinska majhna ?rka u z diarezo ",
	yacute:"Latinska majhna ?rka y z ostrivcem ",
	thorn:"Latinska majhna ?rka thorn ",
	yuml:"Latinska majhna ?rka y z diarezo ",

// Greek Characters and Symbols
	fnof:"Zavita latinska majhna ?rka f\nfunkcija ",
	Alpha:"Gr?ka velika ?rka alfa ",
	Beta:"Gr?ka velika ?rka beta ",
	Gamma:"Gr?ka velika ?rka gama ",
	Delta:"Gr?ka velika ?rka delta ",
	Epsilon:"Gr?ka velika ?rka epsilon ",
	Zeta:"Gr?ka velika ?rka zeta ",
	Eta:"Gr?ka velika ?rka eta ",
	Theta:"Gr?ka velika ?rka theta ",
	Iota:"Gr?ka velika ?rka jota ",
	Kappa:"Gr?ka velika ?rka kapa ",
	Lambda:"Gr?ka velika ?rka lambda ",
	Mu:"Gr?ka velika ?rka mu ",
	Nu:"Gr?ka velika ?rka nu ",
	Xi:"Gr?ka velika ?rka ksi ",
	Omicron:"Gr?ka velika ?rka omikron ",
	Pi:"Gr?ka velika ?rka pi ",
	Rho:"Gr?ka velika ?rka ro ",
	Sigma:"Gr?ka velika ?rka sigma ",
	Tau:"Gr?ka velika ?rka tau ",
	Upsilon:"Gr?ka velika ?rka ipsilon ",
	Phi:"Gr?ka velika ?rka fi ",
	Chi:"Gr?ka velika ?rka hi ",
	Psi:"Gr?ka velika ?rka psi ",
	Omega:"Gr?ka velika ?rka omega ",
	alpha:"Gr?ka majhna ?rka alfa ",
	beta:"Gr?ka majhna ?rka beta ",
	gamma:"Gr?ka majhna ?rka gama ",
	delta:"Gr?ka majhna ?rka delta ",
	epsilon:"Gr?ka majhna ?rka epsilon ",
	zeta:"Gr?ka majhna ?rka zeta ",
	eta:"Gr?ka majhna ?rka eta ",
	theta:"Gr?ka majhna ?rka theta ",
	iota:"Gr?ka majhna ?rka iota ",
	kappa:"Gr?ka majhna ?rka kapa ",
	lambda:"Gr?ka majhna ?rka lambda ",
	mu:"Gr?ka majhna ?rka mu ",
	nu:"Gr?ka majhna ?rka nu ",
	xi:"Gr?ka majhna ?rka ksi ",
	omicron:"Gr?ka majhna ?rka omikron ",
	pi:"Gr?ka majhna ?rka pi ",
	rho:"Gr?ka majhna ?rka ro ",
	sigmaf:"Gr?ka majhna ?rka kon?na sigma ",
	sigma:"Gr?ka majhna ?rka sigma ",
	tau:"Gr?ka majhna ?rka tau ",
	upsilon:"Gr?ka majhna ?rka ipsilon ",
	phi:"Gr?ka majhna ?rka fi ",
	chi:"Gr?ka majhna ?rka hi ",
	psi:"Gr?ka majhna ?rka psi ",
	omega:"Gr?ka majhna ?rka omega ",
	thetasym:"Simbol majhne gr?ke ?rke theta ",
	upsih:"Gr?ki zaviti simbol ipsilon ",
	piv:"Gr?ki simbol pi ",
	bull:"oznaka\nmajhen ?rn krog ",
	hellip:"tripi?je ",
	prime:"apostrof\nminute\n?evlji ",
	Prime:"dvojni apostrof\nsekunde\npalci",
	oline:"nad?rtaj ",
	frasl:"po?evnica ulomka ",
	weierp:"poten?na mno?ica\nWierstrassov p ",
	image:"Gotska velika ?rka I\nimaginarni del ",
	real:"Gotska velika ?rka R\nrealni del ",
	trade:"znak za blagovno znamko ",
	alefsym:"simbol alef\nprvo transfinitno kardinalno ?tevilo ",
	larr:"pu??ica levo ",
	uarr:"pu??ica navzgor ",
	rarr:"pu??ica desno ",
	darr:"pu??ica navzdol ",
	harr:"pu??ica levo navzgor ",
	crarr:"pu??ica navzdol s kotom na levi strani\nza?etek vrstice ",
	lArr:"dvojna pu??ica levo ",
	uArr:"dvojna pu??ica navzgor ",
	rArr:"dvojna pu??ica desno ",
	dArr:"dvojna pu??ica navzdol ",
	hArr:"dvojna pu??ica levo-desno ",
	forall:"za vse ",
	part:"delni diferencial ",
	exist:"obstaja ",
	empty:"prazna mno?ica ",
	nabla:"nabla ",
	isin:"je element ",
	notin:"ni element ",
	ni:"vsebuje kot ?lana ",
	prod:"n-kratni produkt ",
	sum:"n-kratna vsota ",
	minus:"znak za minus ",
	lowast:"operator zvezdice ",
	radic:"kvadratni koren ",
	prop:"proporcialno z ",
	infin:"neskon?nost ",
	ang:"kot ",
	and:"logi?ni in ",
	or:"logi?ni ali ",
	cap:"presek ",
	cup:"unija ","int":"integral ",
	there4:"zato ",
	sim:"operator tilda\nje podobno\nvarira z ",
	cong:"je pribli?no enako kot ",
	asymp:"je skoraj enako kot\nasimptotsko glede na ",
	ne:"ni enako ",
	equiv:"je identi?no ",
	le:"je manj?e ali enako kot ",
	ge:"je ve?je ali enako kot ",
	sub:"je podmno?ica ",
	sup:"je nadmno?ica ",
	nsub:"ni podmno?nica ",
	sube:"podmno?ica ali enako ",
	supe:"nadmno?ica ali enako ",
	oplus:"obkro?en plus\nneposredna svota ",
	otimes:"obrkro?en krat\nvektorski produkt ",
	perp:"?eblji?ek, obrnjen navzgor\npravokoten glede na ",
	sdot:"operator pika ",
	lceil:"levi zgornji kot ",
	rceil:"desni zgornji kot ",
	lfloor:"levi spodnji kot ",
	rfloor:"desni spodnji kot ",
	lang:"lomljeni oklepaj, ki ka?e v levo ",
	rang:"lomljeni oklepaj, ki ka?e v desno ",
	loz:"romb ",
	spades:"?rni pik ",
	clubs:"?rni kri?\ndetelja ",
	hearts:"?rno srce\nvalentinovo ",
	diams:"?rni karo ",
	OElig:"Latinska velika ligatura OE ",
	oelig:"Latinska majhna ligatura oe ",
	Scaron:"Latinska velika ?rka S s stre?ico ",
	scaron:"Latinska majhna ?rka s s stre?ico ",
	Yuml:"Latinska velika ?rka Y z diarezo ",
	circ:"znak za cirkumfleks ",
	tilde:"mala tilda ",
	ensp:"presledek ",
	emsp:"dolgi presledek ",
	thinsp:"kratki presledek ",
	zwnj:"razdru?evalnik z ni?no ?irino ",
	zwj:"zdru?evalnik z ni?no ?irino ",
	lrm:"oznaka od leve proti desni ",
	rlm:"oznaka od desne proti levi ",
	ndash:"pomi?ljaj",
	mdash:"dolgi pomi?ljaj ",
	lsquo:"levi opu??aj ",
	rsquo:"desni opu??aj ",
	sbquo:"enojni spodnji narekovaj ",
	ldquo:"levi dvojni narekovaj ",
	rdquo:"desni dvojni narekovaj ",
	bdquo:"dvojni spodnji narekovaj ",
	dagger:"kri?ec ",
	Dagger:"dvojni kri?ec ",
	permil:"znak 'na miljo' ",
	lsaquo:"enojni kotni narekovaj, ki ka?e v levo ",
	rsaquo:"enojni kotni narekovaj, ki ka?e v desno ",
	euro:"znak za evro "
})

//end v1.x content
);
