/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "babybl?",
antiquewhite: "antikhvid",
aqua: "akvabl?",
aquamarine: "akvamarin",
azure: "azurbl?",
beige: "beige",
bisque: "gulgr?",
black: "sort",
blanchedalmond: "blanceret mandel",
blue: "bl?",
blueviolet: "bl?violet",
brown: "brun",
burlywood: "tobak",
cadetblue: "kadetbl?",
chartreuse: "chartreuse",
chocolate: "rust",
coral: "koralr?d",
cornflowerblue: "kornblomstbl?",
cornsilk: "majs",
crimson: "blodr?d",
cyan: "cyan",
darkblue: "m?rkebl?",
darkcyan: "m?rk cyan",
darkgoldenrod: "m?rk gyldenris",
darkgray: "m?rkegr?",
darkgreen: "m?rkegr?n",
darkgrey: "m?rkegr?", // same as darkgray
darkkhaki: "m?rk khaki",
darkmagenta: "m?rk magenta",
darkolivegreen: "m?rk olivengr?n",
darkorange: "m?rk orange",
darkorchid: "m?rk orkide",
darkred: "m?rker?d",
darksalmon: "m?rk laksefarvet",
darkseagreen: "m?rk havgr?n",
darkslateblue: "m?rk skiferbl?",
darkslategray: "m?rk skifergr?",
darkslategrey: "m?rk skifergr?", // same as darkslategray
darkturquoise: "m?rk turkis",
darkviolet: "m?rkelilla",
deeppink: "dyb pink",
deepskyblue: "dyb himmelbl?",
dimgray: "svag gr?",
dimgrey: "svag gr?", // same as dimgray
dodgerblue: "dodgerbl?",
firebrick: "chamottesten",
floralwhite: "blomsterhvid",
forestgreen: "skovgr?n",
fuchsia: "lyslilla",
gainsboro: "gainsboro",
ghostwhite: "sp?gelseshvid",
gold: "guld",
goldenrod: "gyldenris",
gray: "gr?",
green: "gr?n",
greenyellow: "gr?ngul",
grey: "gr?", // same as gray
honeydew: "honningdug",
hotpink: "m?rk rosa",
indianred: "lys r?dbrun",
indigo: "indigo",
ivory: "elfenben",
khaki: "khaki",
lavender: "lysviolet",
lavenderblush: "lavendelr?d",
lawngreen: "gr?sgr?n",
lemonchiffon: "citronfromage",
lightblue: "lysebl?",
lightcoral: "lys koralr?d",
lightcyan: "lys cyan",
lightgoldenrodyellow: "lys gyldenrisgul",
lightgray: "lysegr?",
lightgreen: "lysegr?n",
lightgrey: "lysegr?", // same as lightgray
lightpink: "lys pink",
lightsalmon: "lys laksefarvet",
lightseagreen: "lys havgr?n",
lightskyblue: "lys himmelbl?",
lightslategray: "lys skifergr?",
lightslategrey: "lys skifergr?", // same as lightslategray
lightsteelblue: "lys st?lbl?",
lightyellow: "lysegul",
lime: "lime",
limegreen: "limegr?n",
linen: "l?rred",
magenta: "magenta",
maroon: "r?dbrun",
mediumaquamarine: "mellem akvamarin",
mediumblue: "mellembl?",
mediumorchid: "mellem orkide",
mediumpurple: "mellemlilla",
mediumseagreen: "mellemhavgr?n",
mediumslateblue: "mellemskiferbl?",
mediumspringgreen: "mellemfor?rsgr?n",
mediumturquoise: "mellemturkis",
mediumvioletred: "mellemviolet",
midnightblue: "midnatsbl?",
mintcream: "pebermyntecreme",
mistyrose: "blegrosa",
moccasin: "fruesko",
navajowhite: "navajo-hvid",
navy: "marinebl?",
oldlace: "kniplingshvid",
olive: "olivengr?n",
olivedrab: "brungr?n",
orange: "orange",
orangered: "oranger?d",
orchid: "orkide",
palegoldenrod: "bleg gyldenris",
palegreen: "bleggr?n",
paleturquoise: "bleg turkis",
palevioletred: "blegviolet",
papayawhip: "papaya",
peachpuff: "fersken",
peru: "peru",
pink: "pink",
plum: "blomme",
powderblue: "pudderbl?",
purple: "lilla",
red: "r?d",
rosybrown: "rosabrun",
royalblue: "kongebl?",
saddlebrown: "saddelbrun",
salmon: "laksefarvet",
sandybrown: "sandbrun",
seagreen: "havgr?n",
seashell: "muslingeskal",
sienna: "sienna",
silver: "s?lv",
skyblue: "himmelbl?",
slateblue: "skiferbl?",
slategray: "skifergr?",
slategrey: "skifergr?", // same as slategray
snow: "sne",
springgreen: "for?rsgr?n",
steelblue: "metalbl?",
tan: "tan",
teal: "bl?gr?n",
thistle: "tidsel",
tomato: "tomat",
turquoise: "turkis",
violet: "lilla",
wheat: "korngul",
white: "hvid",
whitesmoke: "hvid r?g",
yellow: "gul",
yellowgreen: "gulgr?n"
})
//end v1.x content
);
