/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	"lightsteelblue":"a??q metal mavi",
	"orangered" :"nar?nc? q?rm?z?",
	"midnightblue" :"gec? mavisi",
	"cadetblue" :"d?niz mavisi" ,
	"seashell" :"d?niz s?thi",
	"slategrey" :"boz ?ifer r?ngi",
	"coral" :"m?rcan",
	"darkturquoise" :"t?nd firuz?yi",
	"antiquewhite" :"antik a?",
	"mediumspringgreen" :"orta bahar ya??l?",
	"salmon" :"somon",
	"darkgrey" :"t?nd boz",
	"ivory" :"fil di?i",
	"greenyellow" :"ya??l-sar?",
	"mistyrose" :"g?l qurusu",
	"lightsalmon" :"a??q somon",
	"silver" :"g?m???",
	"dimgrey" :"a??q boz",
	"orange" :"nar?nc?",
	"white" :"a?",
	"navajowhite" :"navajo a??",
	"royalblue" :"parlaq t?nd mavi" ,
	"deeppink" :"t?nd ??hray?",
	"lime" :"lomon ya??l?",
	"oldlace" :"k?hn? krujeva",
	"chartreuse" :"chartreuse",
	"darkcyan" :"t?nd firuz?yi",
	"yellow" :"sar?",
	"linen" :"k?tan",
	"olive" :"zeytun",
	"gold" :"q?z?l",
	"lawngreen" :"??m?n ya??l?",
	"lightyellow" :"a??q sar?",
	"tan" :"g?n?? yan???",
	"darkviolet" :"t?nd b?n?v??yi",
	"lightslategrey" :"t?nd ?ifer bozu",
	"grey" :"boz",
	"darkkhaki" :"t?nd haki",
	"green" :"ya??l",
	"deepskyblue" :"t?nd s?ma mavisi",
	"aqua" :"d?niz mavisi",
	"sienna" :"t?nd q?hv?yi",
	"mintcream" :"nan?li krem",
	"rosybrown" :"??hray?ms? q?hv?yi",
	"mediumslateblue" :"orta ??fer bozu",
	"magenta" :"magenta",
	"lightseagreen" :"a??q d?niz ya??l?",
	"cyan" :"firuz?yi",
	"olivedrab" :"?sg?r ya??l?",
	"darkgoldenrod" :"t?nd sar?",
	"slateblue" :"?ifer mavisi",
	"mediumaquamarine" :"orta akvamarin",
	"lavender" :"lavanta",
	"mediumseagreen" :"orta d?niz ya??l?",
	"maroon" :"t?nd q?rm?z?",
	"darkslategray" :"t?nd ?ifer bozu",
	"mediumturquoise" :"orta firuz?yi",
	"ghostwhite" :"ala",
	"darkblue" :"t?nd mavi",
	"mediumvioletred" :"orta b?n?v??yi-q?rm?z?",
	"brown" :"q?hv?yi",
	"lightgray" :"a??q boz",
	"sandybrown" :"qum r?ngi",
	"pink" :"??hray?",
	"firebrick" :"yanm?? k?rpic r?ngi",
	"indigo" :"indigo",
	"snow" :"qar",
	"darkorchid" :"t?nd orkide",
	"turquoise" :"firuz?yi",
	"chocolate" :"?okolad",
	"springgreen" :"bahar ya??l?",
	"moccasin" :"mokosen",
	"navy" :"t?nd g?y",
	"lemonchiffon" :"limon r?ngi",
	"teal" :"teal mavi",
	"floralwhite" :"?i??k a??",
	"cornflowerblue" :"pey??mb?r ?i??k mavisi",
	"paleturquoise" :"sol?un firuz?yi",
	"purple" :"t?nd q?rm?z?",
	"gainsboro" :"gainsboro",
	"plum" :"gaval?",
	"red" :"q?rm?z?",
	"blue" :"g?y",
	"forestgreen" :"t?nd d?niz ya??l?",
	"darkgreen" :"t?nd ya??l",
	"honeydew" :"bal saqq?z?",
	"darkseagreen" :"t?nd d?niz ya??l?",
	"lightcoral" :"a??q m?rcan",
	"palevioletred" :"sol?un b?n?v??yi-q?rm?z?",
	"mediumpurple" :"orta t?nd q?rm?z?",
	"saddlebrown" :"a??q q?hv?yi",
	"darkmagenta" :"t?nd magenta",
	"thistle" :"d?v? tikan?",
	"whitesmoke" :"a? duman",
	"wheat" :"bu?day?",
	"violet" :"b?n?v??yi",
	"lightskyblue" :"a??q s?ma mavisi" ,
	"goldenrod" :"sapsar?",
	"mediumblue" :"orta g?y",
	"skyblue" :"g?y mavisi",
	"crimson" :"crimson",
	"darksalmon" :"t?nd somon",
	"darkred" :"t?nd q?rm?z?",
	"darkslategrey" :"t?nd ?ifer bozu",
	"peru" :"peru",
	"lightgrey" :"a??q boz",
	"lightgoldenrodyellow" :"a??q q?z?l?",
	"blanchedalmond" :"sol?un badam?",
	"aliceblue" :"alice mavisi",
	"bisque" :"biskvit",
	"slategray" :"?ifer bozu",
	"palegoldenrod" :"a??q q?z?l?",
	"darkorange" :"t?nd nar?nc?",
	"aquamarine" :"akvamarin",
	"lightgreen" :"a??q ya??l",
	"burlywood" :"sar?ms? q?hv? r?ngi",
	"dodgerblue" :"toz mavisi",
	"darkgray" :"t?nd boz",
	"lightcyan" :"a??q firuz?yi",
	"powderblue" :"pudra mavisi",
	"blueviolet" :"mavi-b?n?v??yi",
	"orchid" :"orkide",
	"dimgray" :"sol?un boz",
	"beige" :"bej",
	"fuchsia" :"fu?ya",
	"lavenderblush" :"lavanta t?nd q?rm?z?s?",
	"hotpink" :"t?nd ??hray?",
	"steelblue" :"metal mavisi",
	"tomato" :"pomidor",
	"lightpink" :"a??q ??hray?",
	"limegreen" :"?h?ng ya??l?",
	"indianred" :"q?z?ld?rili q?rm?z?s?",
	"papayawhip" :"papaya qam??s?",
	"lightslategray" :"a??q ?ifer bozu",
	"gray" :"boz",
	"mediumorchid" :"orta orkide",
	"cornsilk" :"qar??dal? r?ngi",
	"black" :"qara",
	"seagreen" :"d?niz ya??l?",
	"darkslateblue" :"t?nd ?ifer bozu",
	"khaki" :"haki",
	"lightblue" :"a??q mavi",
	"palegreen" :"sol?un ya??l",
	"azure" :"azur mavisi",
	"peachpuff" :"a??q ?aftal?",
	"darkolivegreen" :"t?nd zeytun ya??l?",
	"yellowgreen" :"sar?-ya??l"
})
//end v1.x content
);