/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"ters ?nlem i?areti",
	cent:"sent i?areti",
	pound:"sterlin i?areti",
	curren:"d?viz i?areti",
	yen:"yen i?areti\nyuan i?areti",
	brvbar:"kesik ?ubuk\nkesik ?ubuk",
	sect:"b?l?m i?areti",
	uml:"umlaut i?areti\naral?kl? umlaut i?areti",
	copy:"telif hakk? i?areti",
	ordf:"di?i s?ra g?stergesi",
	laquo:"sol a??l? ?ift t?rnak i?areti\nleft pointing guillemet",
	not:"de?il i?areti",
	shy:"ko?ullu kesme i?areti\niste?e ba?l? kesme i?areti",
	reg:"tescil i?areti\ntescilli ticari marka i?areti",
	macr:"uzatma i?areti\naral?kl? uzatma i?areti\n?st ?izgi\nAPL ?st?izgisi",
	deg:"derece i?areti",
	plusmn:"art?-eksi i?areti\nart?-veya-eksi i?areti",
	sup2:"?st simge iki\n?st simge iki rakam?\nkare i?areti",
	sup3:"?st simge ??\n?st simge ?? rakam?\nk?p i?areti",
	acute:"tiz aksan i?areti\naral?kl? aksan",
	micro:"mikro i?areti",
	para:"pilcrow i?areti\nparagraf i?areti",
	middot:"orta nokta\nGeorgian comma\nGreek middle dot",
	cedil:"?engel\naral?kl? ?engel",
	sup1:"?st simge bir\n?st simge bir rakam?",
	ordm:"erkek s?ra g?stergesi",
	raquo:"sa? a??l? ?ift t?rnak i?areti\nright pointing guillemet",
	frac14:"d?rtte birlik baya?? kesir\nd?rtte birlik kesir",
	frac12:"bir b?l? ikilik baya?? kesir\nbir b?l? ikilik kesir",
	frac34:"d?rtte ??l?k baya?? kesir\nd?rtte ??l?k kesir",
	iquest:"ters soru i?areti\nd?nm?? soru i?areti",
	Agrave:"Aksan imiyle Latince b?y?k harf A\nLatince b?y?k harf A aksanl?",
	Aacute:"Vurgu imiyle Latince b?y?k harf A",
	Acirc:"?nceltme imiyle Latince b?y?k harf A",
	Atilde:"Tilde imiyle Latince b?y?k harf A",
	Auml:"Umlaut imiyle Latince b?y?k harf A",
	Aring:"?stte halka imiyle Latince b?y?k harf A\nLatince b?y?k harf A halkal?",
	AElig:"Latince b?y?k harf AE\nLatin b?y?k birle?tirmeli yaz?m AE",
	Ccedil:"?engel imiyle Latince b?y?k harf C",
	Egrave:"Aksan imiyle Latince b?y?k harf E",
	Eacute:"Vurgu imiyle Latince b?y?k harf E",
	Ecirc:"?nceltme imiyle Latince b?y?k harf E",
	Euml:"Umlaut imiyle Latince b?y?k harf E",
	Igrave:"Aksan imiyle Latince b?y?k harf I",
	Iacute:"Vurgu imiyle Latince b?y?k harf I",
	Icirc:"?nceltme imiyle Latince b?y?k harf I",
	Iuml:"Umlaut imiyle Latince b?y?k harf I",
	ETH:"Latince b?y?k harf ETH",
	Ntilde:"Tilde imiyle Latince b?y?k harf N",
	Ograve:"Aksan imiyle Latince b?y?k harf O",
	Oacute:"Vurgu imiyle Latince b?y?k harf O",
	Ocirc:"?nceltme imiyle Latince b?y?k harf O",
	Otilde:"Tilde imiyle Latince b?y?k harf O",
	Ouml:"Umlaut imiyle Latince b?y?k harf O",
	times:"?arpma i?areti",
	Oslash:"B?l? i?aretiyle Latince b?y?k harf O\ntaksim i?aretiyle Latince b?y?k harf O",
	Ugrave:"Aksan imiyle Latince b?y?k harf U",
	Uacute:"Vurgu imiyle Latince b?y?k harf U",
	Ucirc:"?nceltme imiyle Latince b?y?k harf U",
	Uuml:"Umlaut i?aretiyle Latince b?y?k harf U",
	Yacute:"Vurgu imiyle Latince b?y?k harf Y",
	THORN:"Latince b?y?k harf THORN",
	szlig:"Latince k???k harf sert s\ness-zed",
	agrave:"Aksan imiyle Latince k???k harf a\nLatince k???k harf a aksanl?",
	aacute:"Vurgu imiyle Latince k???k harf a",
	acirc:"?nceltme imiyle Latince k???k harf a",
	atilde:"Tilde imiyle Latince k???k harf a",
	auml:"Umlaut imiyle Latince k???k harf a",
	aring:"?stte halka imiyle Latince k???k harf a\nLatince k???k harf a halkal?",
	aelig:"Latince k???k harf ae\nLatince k???k birle?tirmeli yaz?m ae",
	ccedil:"?engel imiyle Latince k???k harf c",
	egrave:"Aksan imiyle Latince k???k harf e",
	eacute:"Vurgu imiyle Latince k???k harf e",
	ecirc:"?nceltme imiyle Latince k???k harf e",
	euml:"Umlaut imiyle Latince k???k harf e",
	igrave:"Aksan imiyle Latince k???k harf i",
	iacute:"Vurgu imiyle Latince k???k harf i",
	icirc:"?nceltme imiyle Latince k???k harf i",
	iuml:"Umlaut imiyle Latince k???k harf i",
	eth:"Latince k???k harf eth",
	ntilde:"Tilde imiyle Latince k???k harf n",
	ograve:"Aksan imiyle Latince k???k harf o",
	oacute:"Vurgu imiyle Latince k???k harf o",
	ocirc:"?nceltme imiyle Latince k???k harf o",
	otilde:"Tilde imiyle Latince k???k harf o",
	ouml:"Umlaut imiyle Latince k???k harf o",
	divide:"b?l? i?areti",
	oslash:"B?l? i?aretiyle Latince k???k harf o\ntaksim i?aretiyle Latince k???k harf o",
	ugrave:"Aksan imiyle Latice k???k harf u",
	uacute:"Vurgu imiyle Latince k???k harf u",
	ucirc:"?nceltme imiyle Latince k???k harf u",
	uuml:"Umlaut imiyle Latince k???k harf u",
	yacute:"Vurgu imiyle Latince k???k harf y",
	thorn:"Latince k???k harf thorn",
	yuml:"Umlaut imiyle Latince k???k harf y",

// Greek Characters and Symbols
	fnof:"Kanca imiyle Latince k???k f\nfonksiyon\nflorin",
	Alpha:"Yunanca b?y?k harf alpha",
	Beta:"Yunanca b?y?k harf beta",
	Gamma:"Yunanca b?y?k harf gamma",
	Delta:"Yunanca b?y?k harf delta",
	Epsilon:"Yunanca b?y?k harf epsilon",
	Zeta:"Yunanca b?y?k harf zeta",
	Eta:"Yunanca b?y?k harf eta",
	Theta:"Yunanca b?y?k harf theta",
	Iota:"Yunanca b?y?k harf iota",
	Kappa:"Yunanca b?y?k harf kappa",
	Lambda:"Yunanca b?y?k harf lambda",
	Mu:"Yunanca b?y?k harf mu",
	Nu:"Yunanca b?y?k harf nu",
	Xi:"Yunanca b?y?k harf xi",
	Omicron:"Yunanca b?y?k harf omicron",
	Pi:"Yunanca b?y?k harf pi",
	Rho:"Yunanca b?y?k harf rho",
	Sigma:"Yunanca b?y?k harf sigma",
	Tau:"Yunanca b?y?k harf tau",
	Upsilon:"Yunanca b?y?k harf upsilon",
	Phi:"Yunanca b?y?k harf phi",
	Chi:"Yunanca b?y?k harf chi",
	Psi:"Yunanca b?y?k harf psi",
	Omega:"Yunanca b?y?k harf omega",
	alpha:"Yunanca k???k harf alpha",
	beta:"Yunanca k???k harf beta",
	gamma:"Yunanca k???k harf gamma",
	delta:"Yunanca k???k harf delta",
	epsilon:"Yunanca k???k harf epsilon",
	zeta:"Yunanca k???k harf zeta",
	eta:"Yunanca k???k harf eta",
	theta:"Yunanca k???k harf theta",
	iota:"Yunanca k???k harf iota",
	kappa:"Yunanca k???k harf kappa",
	lambda:"Yunanca k???k harf lambda",
	mu:"Yunanca k???k harf mu",
	nu:"Yunanca k???k harf nu",
	xi:"Yunanca k???k harf xi",
	omicron:"Yunanca k???k harf omicron",
	pi:"Yunanca k???k harf pi",
	rho:"Yunanca k???k harf rho",
	sigmaf:"Yunanca k???k harf final",
	sigma:"Yunanca k???k harf final",
	tau:"Yunanca k???k harf tau",
	upsilon:"Yunanca k???k harf final",
	phi:"Yunanca k???k harf phi",
	chi:"Yunanca k???k harf final",
	psi:"Yunanca k???k harf psi",
	omega:"Yunanca k???k harf final",
	thetasym:"Yunanca k???k harf theta",
	upsih:"Kanca i?aretiyle Yunanca upsilon",
	piv:"Yunanca pi i?areti",
	bull:"madde imi\nsiyah k???k daire",
	hellip:"yanyana ?? nokta\n?? nokta",
	prime:"?ss?\ndakika\nfit",
	Prime:"?ss? iki\nsaniye\nin?",
	oline:"?st?izgi\naral?kl? ?st?izgi",
	frasl:"b?lme i?aretli kesir",
	weierp:"el yaz?s? b?y?k harf P\nkuvvet k?mesi\nWeierstrass p",
	image:"Gotik b?y?k harf I\nsanal k?s?m",
	real:"Gotik b?y?k harf R\nger?ek k?s?m i?areti",
	trade:"ticari marka i?areti",
	alefsym:"alef i?areti\nbirinci sonsuz sayma say?s?",
	larr:"sol ok i?areti",
	uarr:"yukar? ok i?areti",
	rarr:"sa? ol i?areti",
	darr:"a?a?? ok i?areti",
	harr:"sol sa? ok",
	crarr:"sola d?nen a?a?? ok\nsat?r ba?? karakteri",
	lArr:"sola ?ift ok",
	uArr:"yukar? ?ift ok",
	rArr:"sa?a ?ift ok",
	dArr:"a?a?? ?ift ok",
	hArr:"sola sa?a ?ift ok",
	forall:"for all",
	part:"k?smi t?rev",
	exist:"vard?r",
	empty:"bo? k?me\nbo? k?me\n?ap",
	nabla:"nabla\ngeriye do?ru fark",
	isin:"eleman?d?r",
	notin:"eleman? de?ildir",
	ni:"kapsar",
	prod:"n-ary ?arp?m\?arp?m i?areti",
	sum:"n-ary toplam?",
	minus:"eksi i?areti",
	lowast:"asterisk i?leci",
	radic:"kare k?k\nk?k i?areti",
	prop:"orant?l?",
	infin:"sonsuzluk",
	ang:"a??",
	and:"mant?kl? ve\nwedge",
	or:"mant?kl? veya\nvee",
	cap:"arakesit\ncap",
	cup:"birle?im\ncup","int":"integral",
	there4:"bu nedenle",
	sim:"tilde i?leci\nde?i?ir\nbenzer",
	cong:"yakla??k olarak e?it",
	asymp:"neredeyse e?it\nkavu?maz",
	ne:"e?it de?il",
	equiv:"ayn?",
	le:"daha k???k ya da e?it",
	ge:"daha b?y?k ya da e?it",
	sub:"alt k?mesi",
	sup:"?st k?mesi",
	nsub:"alt k?mesi de?il",
	sube:"alt k?mesi ya da e?it",
	supe:"?st k?mesi ya da e?it",
	oplus:"daire i?inde art?\ndolays?z toplam",
	otimes:"daire i?inde ?arp?\nvekt?rel ?arp?m",
	perp:"up tack\ndik\ndikey",
	sdot:"nokta i?leci",
	lceil:"left ceiling\nAPL upstile",
	rceil:"right ceiling",
	lfloor:"left floor\nAPL downstile",
	rfloor:"right floor",
	lang:"sol a??l? ayra?",
	rang:"sa? a??l? ayra?",
	loz:"baklava bi?imi",
	spades:"siyah ma?a i?areti",
	clubs:"siyah sinek i?areti\nyonca",
	hearts:"siyah kupa i?areti\nkalp",
	diams:"siyah karo i?areti",
	OElig:"Latince b?y?k birle?ik harf OE",
	oelig:"Latince k???k birle?ik harf oe",
	Scaron:"Karon imiyle Latince b?y?k harf S",
	scaron:"Karon imiyle Latince k???k harf s",
	Yuml:"Umlaut imiyle Latince b?y?k harf Y",
	circ:"niteleyici harf inceltme vurgusu",
	tilde:"k???k tilde",
	ensp:"k?sa bo?luk",
	emsp:"uzun bo?luk",
	thinsp:"ince bo?luk",
	zwnj:"s?f?r geni?lik ay?r?c?",
	zwj:"s?f?r geni?lik birle?tirici",
	lrm:"soldan sa?a i?areti",
	rlm:"sa?dan sola i?areti",
	ndash:"tire",
	mdash:"uzun tire",
	lsquo:"sol tek t?rnak i?areti",
	rsquo:"sa? tek t?rnak i?areti",
	sbquo:"9 bi?imli al?ak tek t?rnak i?areti",
	ldquo:"sol ?ift t?rnak i?areti",
	rdquo:"sa? ?ift t?rnak i?areti",
	bdquo:"9 bi?imli al?ak ?ift t?rnak i?areti",
	dagger:"kama",
	Dagger:"?ift kama",
	permil:"binde i?areti",
	lsaquo:"sol a??l? tek t?rnak i?areti",
	rsaquo:"sa? a??l? tek t?rnak i?areti",
	euro:"euro i?areti"
})

//end v1.x content
);
