/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "alicebl?",
antiquewhite: "antikvitt",
aqua: "akvamarin",
aquamarine: "akvamarin",
azure: "azurbl?tt",
beige: "beige",
bisque: "biskvi",
black: "svart",
blanchedalmond: "sk?llad mandel",
blue: "bl?tt",
blueviolet: "bl?violett",
brown: "brunt",
burlywood: "tr?f?rgat",
cadetblue: "kadettbl?tt",
chartreuse: "chartreuse",
chocolate: "choklad",
coral: "korall",
cornflowerblue: "kornbl?tt",
cornsilk: "gulvitt",
crimson: "karmosinr?tt",
cyan: "cyan",
darkblue: "m?rkbl?tt",
darkcyan: "m?rkt cyan",
darkgoldenrod: "m?rkt gullris",
darkgray: "m?rkgr?tt",
darkgreen: "m?rkgr?nt",
darkgrey: "m?rkgr?tt", // same as darkgray
darkkhaki: "m?rkt kaki",
darkmagenta: "m?rk magenta",
darkolivegreen: "m?rkt olivgr?nt",
darkorange: "m?rkorange",
darkorchid: "m?rkt orkid?",
darkred: "m?rkr?tt",
darksalmon: "m?rkt laxf?rgat",
darkseagreen: "m?rkt havsgr?nt",
darkslateblue: "m?rkt skifferbl?tt",
darkslategray: "m?rkt skiffergr?tt",
darkslategrey: "m?rkt skiffergr?tt", // same as darkslategray
darkturquoise: "m?rkturkost",
darkviolet: "m?rkviolett",
deeppink: "djuprosa",
deepskyblue: "m?rkt himmelsbl?tt",
dimgray: "smutsgr?tt",
dimgrey: "smutsgr?tt", // same as dimgray
dodgerblue: "dodgerbl?tt",
firebrick: "tegelstensr?tt",
floralwhite: "blomvitt",
forestgreen: "skogsgr?nt",
fuchsia: "fuchsia",
gainsboro: "gainsboro",
ghostwhite: "sp?kvitt",
gold: "guld",
goldenrod: "gullris",
gray: "gr?tt",
green: "gr?nt",
greenyellow: "gr?ngult",
grey: "gr?tt", // same as gray
honeydew: "honungsdagg",
hotpink: "varmrosa",
indianred: "indianr?tt",
indigo: "indigo",
ivory: "elfenbensvitt",
khaki: "kaki",
lavender: "lavendel",
lavenderblush: "lavendelskimrande",
lawngreen: "gr?smattegr?nt",
lemonchiffon: "citronchiffong",
lightblue: "ljusbl?tt",
lightcoral: "ljuskorall",
lightcyan: "ljust cyan",
lightgoldenrodyellow: "ljust gullrisgult",
lightgray: "ljusgr?tt",
lightgreen: "ljusgr?nt",
lightgrey: "ljusgr?tt", // same as lightgray
lightpink: "ljusrosa",
lightsalmon: "ljust laxf?rgat",
lightseagreen: "ljust havsgr?nt",
lightskyblue: "ljust himmelsbl?tt",
lightslategray: "ljust skiffergr?tt",
lightslategrey: "ljust skiffergr?tt", // same as lightslategray
lightsteelblue: "ljust st?lbl?tt",
lightyellow: "ljusgult",
lime: "lime",
limegreen: "limegr?nt",
linen: "linne",
magenta: "magenta",
maroon: "r?dbrunt",
mediumaquamarine: "mellanakvamarin",
mediumblue: "mellanbl?tt",
mediumorchid: "mellanorkid?",
mediumpurple: "mellanlila",
mediumseagreen: "mellanhavsgr?nt",
mediumslateblue: "mellanskifferbl?tt",
mediumspringgreen: "mellanv?rgr?nt",
mediumturquoise: "mellanturkost",
mediumvioletred: "mellanviolettr?tt",
midnightblue: "midnattsbl?tt",
mintcream: "mintgr?dde",
mistyrose: "dunkelrosa",
moccasin: "mockasin",
navajowhite: "navajovitt",
navy: "marinbl?tt",
oldlace: "spetsvitt",
olive: "olivf?rgat",
olivedrab: "olivsmutsgult",
orange: "orange",
orangered: "oranger?tt",
orchid: "orkid?",
palegoldenrod: "blekt gullris",
palegreen: "blekgr?nt",
paleturquoise: "blekturkost",
palevioletred: "blekviolettr?tt",
papayawhip: "papayar?ra",
peachpuff: "persika",
peru: "peru",
pink: "rosa",
plum: "plommon",
powderblue: "pulverbl?tt",
purple: "lila",
red: "r?tt",
rosybrown: "rosenbrunt",
royalblue: "kungligt bl?tt",
saddlebrown: "sadelbrunt",
salmon: "laxf?rgat",
sandybrown: "sandbrunt",
seagreen: "havsgr?nt",
seashell: "sn?ckskal",
sienna: "sienna",
silver: "silver",
skyblue: "himmelsbl?tt",
slateblue: "skifferbl?tt",
slategray: "skiffergr?tt",
slategrey: "skiffergr?tt", // same as slategray
snow: "sn?",
springgreen: "v?rgr?nt",
steelblue: "st?lbl?tt",
tan: "mellanbrunt",
teal: "bl?gr?nt",
thistle: "tistel",
tomato: "tomatr?tt",
turquoise: "turkost",
violet: "violett",
wheat: "vete",
white: "vitt",
whitesmoke: "vit r?k",
yellow: "gult",
yellowgreen: "gulgr?nt"
})
//end v1.x content
);
