/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "Alice k?k",
antiquewhite: "antik feh?r",
aqua: "v?zsz?n",
aquamarine: "akvamarin",
azure: "az?rk?k",
beige: "b?zs",
bisque: "porcel?n",
black: "fekete",
blanchedalmond: "h?mozott mandula",
blue: "k?k",
blueviolet: "ibolyak?k",
brown: "barna",
burlywood: "nyersfa",
cadetblue: "kad?tk?k",
chartreuse: "chartreuse",
chocolate: "csokol?d?",
coral: "korall",
cornflowerblue: "b?zavir?gk?k",
cornsilk: "kukoricahaj",
crimson: "karmazsinv?r?s",
cyan: "ci?nk?k",
darkblue: "s?t?tk?k",
darkcyan: "s?t?t ci?nk?k",
darkgoldenrod: "s?t?t aranyvessz?",
darkgray: "s?t?tsz?rke",
darkgreen: "s?t?tz?ld",
darkgrey: "s?t?tsz?rke", // same as darkgray
darkkhaki: "s?t?t khakisz?n",
darkmagenta: "s?t?tb?bor",
darkolivegreen: "s?t?t olajz?ld",
darkorange: "s?t?t narancss?rga",
darkorchid: "s?t?t orchidea",
darkred: "s?t?tv?r?s",
darksalmon: "s?t?t lazacsz?n",
darkseagreen: "s?t?t tengerz?ld",
darkslateblue: "s?t?t palak?k",
darkslategray: "s?t?t palasz?rke",
darkslategrey: "s?t?t palasz?rke", // same as darkslategray
darkturquoise: "s?t?t t?rkizk?k",
darkviolet: "s?t?t ibolyasz?n",
deeppink: "s?t?tr?zsasz?n",
deepskyblue: "s?t?t ?gsz?nk?k",
dimgray: "halv?nysz?rke",
dimgrey: "halv?nysz?rke", // same as dimgray
dodgerblue: "dodger k?k",
firebrick: "t?glav?r?s",
floralwhite: "vir?gfeh?r",
forestgreen: "erd?z?ld",
fuchsia: "fukszia",
gainsboro: "gainsboro",
ghostwhite: "szellemfeh?r",
gold: "arany",
goldenrod: "aranyvessz?",
gray: "sz?rke",
green: "z?ld",
greenyellow: "z?ldess?rga",
grey: "sz?rke", // same as gray
honeydew: "m?zharmat",
hotpink: "meleg r?zsasz?n",
indianred: "indi?nv?r?s",
indigo: "indig?",
ivory: "elef?ntcsont",
khaki: "khakisz?n",
lavender: "levendula",
lavenderblush: "pirosas levendula",
lawngreen: "f?z?ld",
lemonchiffon: "s?rga m?selyem",
lightblue: "vil?gosk?k",
lightcoral: "vil?gos korall",
lightcyan: "vil?gos ci?nk?k",
lightgoldenrodyellow: "vil?gos aranyvessz? s?rga",
lightgray: "vil?gossz?rke",
lightgreen: "vil?gosz?ld",
lightgrey: "vil?gossz?rke", // same as lightgray
lightpink: "vil?gos r?zsasz?n",
lightsalmon: "vil?gos lazacsz?n",
lightseagreen: "vil?gos tengerz?ld",
lightskyblue: "vil?gos ?gsz?nk?k",
lightslategray: "vil?gos palasz?rke",
lightslategrey: "vil?gos palasz?rke", // same as lightslategray
lightsteelblue: "vil?gos ac?lk?k",
lightyellow: "vil?goss?rga",
lime: "lime",
limegreen: "limez?ld",
linen: "v?szonfeh?r",
magenta: "b?bor",
maroon: "gesztenyebarna",
mediumaquamarine: "k?zepes akvamarin",
mediumblue: "k?zepes k?k",
mediumorchid: "k?zepes orchidea",
mediumpurple: "k?zepes lila",
mediumseagreen: "k?zepes tengerz?ld",
mediumslateblue: "k?zepes palak?k",
mediumspringgreen: "k?zepes tavaszz?ld",
mediumturquoise: "k?zepes t?rkizk?k",
mediumvioletred: "k?zepes ibolyav?r?s",
midnightblue: "?jk?k",
mintcream: "mentasz?sz",
mistyrose: "halv?ny r?zsasz?n",
moccasin: "mokkasz?n",
navajowhite: "navajo feh?r",
navy: "tenger?szk?k",
oldlace: "r?gi csipke",
olive: "olajz?ld",
olivedrab: "olajz?ld drapp",
orange: "narancss?rga",
orangered: "narancsv?r?s",
orchid: "orchidea",
palegoldenrod: "halv?ny aranyvessz?",
palegreen: "halv?nyz?ld",
paleturquoise: "halv?ny t?rkizk?k",
palevioletred: "halv?ny ibolyav?r?s",
papayawhip: "papayahab",
peachpuff: "baracksz?n",
peru: "peru",
pink: "r?zsasz?n",
plum: "szilvak?k",
powderblue: "p?derk?k",
purple: "lila",
red: "v?r?s",
rosybrown: "barn?sr?zsasz?n",
royalblue: "kir?lyk?k",
saddlebrown: "nyeregbarna",
salmon: "lazacsz?n",
sandybrown: "homokbarna",
seagreen: "tengerz?ld",
seashell: "kagyl?",
sienna: "v?r?sesbarna",
silver: "ez?st",
skyblue: "?gsz?nk?k",
slateblue: "palak?k",
slategray: "palasz?rke",
slategrey: "palasz?rke", // same as slategray
snow: "h?",
springgreen: "tavaszz?ld",
steelblue: "ac?lk?k",
tan: "rozsdabarna",
teal: "p?vak?k",
thistle: "bog?ncs",
tomato: "paradicsom",
turquoise: "t?rkizk?k",
violet: "ibolyasz?n",
wheat: "b?za",
white: "feh?r",
whitesmoke: "feh?r f?st",
yellow: "s?rga",
yellowgreen: "s?rg?sz?ld"
})
//end v1.x content
);
