/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "bladoniebieski",
antiquewhite: "biel antyczna",
aqua: "morski",
aquamarine: "akwamaryna",
azure: "lazurowy",
beige: "be?owy",
bisque: "biszkoptowy",
black: "czarny",
blanchedalmond: "migda?owy",
blue: "niebieski",
blueviolet: "b??kitnofio?kowy",
brown: "br?zowy",
burlywood: "kolor drewna",
cadetblue: "niebieskoszary",
chartreuse: "???tooliwkowy",
chocolate: "czekoladowy",
coral: "koralowy",
cornflowerblue: "chabrowy",
cornsilk: "kukurydziany",
crimson: "karmazynowy",
cyan: "niebieskozielony",
darkblue: "ciemnoniebieski",
darkcyan: "ciemnoniebieskozielony",
darkgoldenrod: "ciemne stare z?oto",
darkgray: "ciemnoszary",
darkgreen: "ciemnozielony",
darkgrey: "ciemnoszary", // same as darkgray
darkkhaki: "ciemny khaki",
darkmagenta: "ciemnoamarantowy",
darkolivegreen: "ciemnooliwkowy",
darkorange: "ciemnopomara?czowy",
darkorchid: "ciemna orchidea",
darkred: "ciemnoczerwony",
darksalmon: "ciemno?ososiowy",
darkseagreen: "ciemna ziele? morska",
darkslateblue: "ciemny go??bi",
darkslategray: "ciemny mysi",
darkslategrey: "ciemny mysi", // same as darkslategray
darkturquoise: "mlecznoturkusowy",
darkviolet: "ciemnofio?kowy",
deeppink: "g??boki r??owy",
deepskyblue: "intensywny b??kit nieba",
dimgray: "przyciemniony szary",
dimgrey: "przyciemniony szary", // same as dimgray
dodgerblue: "b??kit Dodgers",
firebrick: "ceglasty",
floralwhite: "kwiatowa biel",
forestgreen: "le?na ziele?",
fuchsia: "fuksjowy",
gainsboro: "bladoszary",
ghostwhite: "bladobia?y",
gold: "z?oty",
goldenrod: "stare z?oto",
gray: "szary",
green: "zielony",
greenyellow: "zielono???ty",
grey: "szary", // same as gray
honeydew: "miodowy",
hotpink: "odblaskowor??owy",
indianred: "kasztanowy",
indigo: "indygo",
ivory: "ko?? s?oniowa",
khaki: "khaki",
lavender: "lawendowy",
lavenderblush: "lawendowocielisty",
lawngreen: "trawiasty",
lemonchiffon: "cytrynowy",
lightblue: "jasnoniebieski",
lightcoral: "jasnokoralowy",
lightcyan: "jasnoniebieskozielony",
lightgoldenrodyellow: "jasno???te stare z?oto",
lightgray: "jasnoszary",
lightgreen: "jasnozielony",
lightgrey: "jasnoszary", // same as lightgray
lightpink: "jasnor??owy",
lightsalmon: "jasno?ososiowy",
lightseagreen: "jasna ziele? morska",
lightskyblue: "jasny b??kit nieba",
lightslategray: "jasny mysi",
lightslategrey: "jasny mysi", // same as lightslategray
lightsteelblue: "jasnostalowoniebieski",
lightyellow: "jasno???ty",
lime: "limonkowy",
limegreen: "zielony limonkowy",
linen: "lniany",
magenta: "amarantowy",
maroon: "kasztanowy",
mediumaquamarine: "?rednia akwamaryna",
mediumblue: "ciemnochabrowy",
mediumorchid: "?rednia orchidea",
mediumpurple: "?redni fioletowy",
mediumseagreen: "?rednia ziele? morska",
mediumslateblue: "?redni go??bi",
mediumspringgreen: "?rednia wiosenna ziele?",
mediumturquoise: "?redni turkusowy",
mediumvioletred: "?redni fio?kowowoczerwony",
midnightblue: "granatowoczarny",
mintcream: "jasnomi?towy",
mistyrose: "blador??any",
moccasin: "mokasynowy",
navajowhite: "piaskowy",
navy: "granatowy",
oldlace: "bladopomara?czowy",
olive: "oliwkowy",
olivedrab: "oliwkowa ziele?",
orange: "pomara?czowy",
orangered: "pomara?czowoczerwony",
orchid: "orchidea",
palegoldenrod: "blade stare z?oto",
palegreen: "bladozielony",
paleturquoise: "bladoturkusowy",
palevioletred: "blady fio?kowoczerwony",
papayawhip: "papaja",
peachpuff: "brzoskwiniowy",
peru: "jasnobr?zowy",
pink: "r??owy",
plum: "?liwkowy",
powderblue: "jasnobladob??kitny",
purple: "fioletowy",
red: "czerwony",
rosybrown: "r??owobr?zowy",
royalblue: "kr?lewski b??kit",
saddlebrown: "br?z sk?rzany",
salmon: "?ososiowy",
sandybrown: "piaskowy br?z",
seagreen: "ziele? morska",
seashell: "matowoliliowy",
sienna: "siena",
silver: "srebrny",
skyblue: "b??kit nieba",
slateblue: "go??bi",
slategray: "mysi",
slategrey: "mysi", // same as slategray
snow: "?nie?ny",
springgreen: "wiosenna ziele?",
steelblue: "stalowoniebieski",
tan: "?niady",
teal: "zielonomodry",
thistle: "bladofioletowy",
tomato: "pomidorowy",
turquoise: "turkusowy",
violet: "fio?kowy",
wheat: "pszeniczny",
white: "bia?y",
whitesmoke: "przydymiony bia?y",
yellow: "???ty",
yellowgreen: "???tozielony"
})
//end v1.x content
);
