/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "alice mavisi",
antiquewhite: "antik beyaz",
aqua: "deniz mavisi",
aquamarine: "akuamarin",
azure: "azur mavisi",
beige: "bej",
bisque: "bisk?vi",
black: "siyah",
blanchedalmond: "soluk badem",
blue: "mavi",
blueviolet: "mavi-mor",
brown: "kahverengi",
burlywood: "sar?ms? kahverengi",
cadetblue: "denizci mavisi",
chartreuse: "chartreuse",
chocolate: "?ikolata",
coral: "mercan",
cornflowerblue: "peygamber ?i?e?i mavisi",
cornsilk: "m?s?r rengi",
crimson: "crimson",
cyan: "camg?be?i",
darkblue: "koyu mavi",
darkcyan: "koyu camg?be?i",
darkgoldenrod: "koyu sar?",
darkgray: "koyu gri",
darkgreen: "koyu ye?il",
darkgrey: "koyu gri", // same as darkgray
darkkhaki: "koyu haki",
darkmagenta: "koyu mor",
darkolivegreen: "koyu zeytin ye?ili",
darkorange: "koyu turuncu",
darkorchid: "koyu orkide",
darkred: "koyu k?rm?z?",
darksalmon: "koyu somon",
darkseagreen: "koyu deniz ye?ili",
darkslateblue: "koyu arduvaz mavisi",
darkslategray: "koyu arduvaz grisi",
darkslategrey: "koyu arduvaz grisi", // same as darkslategray
darkturquoise: "koyu turkuaz",
darkviolet: "koyu eflatun",
deeppink: "koyu pembe",
deepskyblue: "koyu g?k mavisi",
dimgray: "soluk gri",
dimgrey: "soluk gri", // same as dimgray
dodgerblue: "toz mavisi",
firebrick: "canl? kiremit",
floralwhite: "?i?ek beyaz?",
forestgreen: "koyu deniz ye?ili",
fuchsia: "fu?ya",
gainsboro: "gainsboro",
ghostwhite: "silik beyaz",
gold: "alt?n",
goldenrod: "sar?sab?r",
gray: "gri",
green: "ye?il",
greenyellow: "ye?il-sar?",
grey: "gri", // same as gray
honeydew: "?am sak?z?",
hotpink: "s?cak pembe",
indianred: "k?z?lderili k?rm?z?s?",
indigo: "?ivit mavisi",
ivory: "fildi?i",
khaki: "haki",
lavender: "lavanta",
lavenderblush: "lavanta pembesi",
lawngreen: "?imen ye?ili",
lemonchiffon: "limoni",
lightblue: "a??k mavi",
lightcoral: "a??k mercan",
lightcyan: "a??k camg?be?i",
lightgoldenrodyellow: "a??k sar?sab?r",
lightgray: "a??k gri",
lightgreen: "a??k ye?il",
lightgrey: "a??k gri", // same as lightgray
lightpink: "a??k pembe",
lightsalmon: "a??k somon",
lightseagreen: "a??k deniz ye?ili",
lightskyblue: "a??k g?k mavisi",
lightslategray: "a??k arduvaz grisi",
lightslategrey: "a??k arduvaz grisi", // same as lightslategray
lightsteelblue: "a??k metalik mavi",
lightyellow: "a??k sar?",
lime: "limon ye?ili",
limegreen: "k?f ye?ili",
linen: "keten",
magenta: "macenta",
maroon: "kestane",
mediumaquamarine: "orta akuamarin",
mediumblue: "orta mavi",
mediumorchid: "orta orkide",
mediumpurple: "orta mor",
mediumseagreen: "orta deniz ye?ili",
mediumslateblue: "orta arduvaz mavisi",
mediumspringgreen: "orta bahar ye?ili",
mediumturquoise: "orta turkuaz",
mediumvioletred: "orta menek?e k?rm?z?s?",
midnightblue: "gece mavisi",
mintcream: "naneli krem",
mistyrose: "g?lkurusu",
moccasin: "mokosen",
navajowhite: "navajo beyaz?",
navy: "lacivert",
oldlace: "eski dantel",
olive: "zeytin",
olivedrab: "asker ye?ili",
orange: "turuncu",
orangered: "turuncu k?rm?z?",
orchid: "orkide",
palegoldenrod: "soluk sar?sab?r",
palegreen: "soluk ye?il",
paleturquoise: "soluk turkuaz",
palevioletred: "soluk menek?e k?rm?z?s?",
papayawhip: "papaya sap?",
peachpuff: "a??k ?eftali",
peru: "peru",
pink: "pembe",
plum: "erik",
powderblue: "pudra mavisi",
purple: "mor",
red: "k?rm?z?",
rosybrown: "pembemsi kahverengi",
royalblue: "parlak koyu mavi",
saddlebrown: "a??k kahve",
salmon: "somon",
sandybrown: "kum rengi",
seagreen: "deniz ye?ili",
seashell: "deniz kabu?u",
sienna: "koyu kahve",
silver: "g?m??",
skyblue: "g?k mavisi",
slateblue: "arduvaz mavisi",
slategray: "arduvaz grisi",
slategrey: "arduvaz grisi", // same as slategray
snow: "kar",
springgreen: "bahar ye?ili",
steelblue: "metalik mavi",
tan: "g?ne? yan???",
teal: "Teal mavi",
thistle: "devedikeni",
tomato: "domates",
turquoise: "turkuaz",
violet: "eflatun",
wheat: "bu?day",
white: "beyaz",
whitesmoke: "beyaz duman",
yellow: "sar?",
yellowgreen: "sar? ye?il"
})
//end v1.x content
);
