/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"invertovan? v?kri?n?k",
	cent:"znak centu",
	pound:"znak libry",
	curren:"znak meny",
	yen:"znak yen\nznak yuan",
	brvbar:"preru?ovan? ?iara\npreru?ovan? zvisl? ?iara",
	sect:"znak paragraf",
	uml:"znak prehl?skovania",
	copy:"znak copyright",
	ordf:"ordin?lny indik?tor, ?ensk?",
	laquo:"znak dvojitej ??pky v?avo\nukazovate? v?avo",
	not:"znak nie",
	shy:"vo?n? poml?ka",
	reg:"znak registr?cie\nzna?ka registrovanej ochrannej zn?mky",
	macr:"vodorovn? ?iarka",
	deg:"znak stupe?",
	plusmn:"znak plus-m?nus\nznak plus alebo m?nus",
	sup2:"horn? index dva\nna druh?",
	sup3:"horn? index tri\nna tretiu",
	acute:"d??e?",
	micro:"znak mikro",
	para:"znak odseku",
	middot:"stredov? bodka\ngregori?nska ?iarka\ngr?cka stredov? bodka",
	cedil:"cedilla\nspodn? h??ik",
	sup1:"horn? index jedna",
	ordm:"ordin?lny indik?tor, mu?sk?",
	raquo:"znak dvojitej ??pky vpravo\nukazovate? vpravo",
	frac14:"jedna ?tvrtina",
	frac12:"jedna polovica",
	frac34:"tri ?tvrtiny",
	iquest:"invertovan? ot?znik\noto?en? ot?znik",
	Agrave:"ve?k? latinsk? p?smeno A s opa?n?m d???om",
	Aacute:"ve?k? latinsk? p?smeno A s d???om",
	Acirc:"ve?k? latinsk? p?smeno A so strie?kou",
	Atilde:"ve?k? latinsk? p?smeno A s tildou",
	Auml:"ve?k? latinsk? p?smeno A prehlasovan?",
	Aring:"ve?k? latinsk? p?smeno A s kr??kom",
	AElig:"ve?k? latinsk? p?smeno AE",
	Ccedil:"ve?k? latinsk? p?smeno C so spodn?m h??ikom",
	Egrave:"ve?k? latinsk? p?smeno E s opa?n?m d???om",
	Eacute:"ve?k? latinsk? p?smeno E s d???om",
	Ecirc:"ve?k? latinsk? p?smeno E so strie?kou",
	Euml:"ve?k? latinsk? p?smeno E prehlasovan?",
	Igrave:"ve?k? latinsk? p?smeno I s opa?n?m d???om",
	Iacute:"ve?k? latinsk? p?smeno I s d???om",
	Icirc:"ve?k? latinsk? p?smeno I so strie?kou",
	Iuml:"ve?k? latinsk? p?smeno I prehlasovan?",
	ETH:"ve?k? latinsk? p?smeno ETH",
	Ntilde:"ve?k? latinsk? p?smeno N s tildou",
	Ograve:"ve?k? latinsk? p?smeno O s opa?n?m d???om",
	Oacute:"ve?k? latinsk? p?smeno O s d???om",
	Ocirc:"ve?k? latinsk? p?smeno O so strie?kou",
	Otilde:"ve?k? latinsk? p?smeno O s tildou",
	Ouml:"ve?k? latinsk? p?smeno O prehlasovan?",
	times:"znak n?sobenia",
	Oslash:"ve?k? latinsk? p?smeno O s pre?iarknut?m",
	Ugrave:"ve?k? latinsk? p?smeno U s opa?n?m d???om",
	Uacute:"ve?k? latinsk? p?smeno U s d???om",
	Ucirc:"ve?k? latinsk? p?smeno U so strie?kou",
	Uuml:"ve?k? latinsk? p?smeno U prehlasovan?",
	Yacute:"ve?k? latinsk? p?smeno Y s d???om",
	THORN:"ve?k? latinsk? p?smeno THORN",
	szlig:"mal? latinsk? p?smeno ostr? s",
	agrave:"mal? latinsk? p?smeno a s opa?n?m d???om",
	aacute:"mal? latinsk? p?smeno a s d???om",
	acirc:"mal? latinsk? p?smeno a so strie?kou",
	atilde:"mal? latinsk? p?smeno a s tildou",
	auml:"mal? latinsk? p?smeno a prehlasovan?",
	aring:"mal? latinsk? p?smeno a s kr??kom",
	aelig:"mal? latinsk? p?smeno ae",
	ccedil:"mal? latinsk? p?smeno c so spodn?m h??ikom",
	egrave:"mal? latinsk? p?smeno e s opa?n?m d???om",
	eacute:"mal? latinsk? p?smeno e s d???om",
	ecirc:"mal? latinsk? p?smeno e so strie?kou",
	euml:"mal? latinsk? p?smeno e prehlasovan?",
	igrave:"mal? latinsk? p?smeno i s opa?n?m d???om",
	iacute:"mal? latinsk? p?smeno i s d???om",
	icirc:"mal? latinsk? p?smeno i so strie?kou",
	iuml:"mal? latinsk? p?smeno i prehlasovan?",
	eth:"mal? latinsk? p?smeno eth",
	ntilde:"mal? latinsk? p?smeno n s tildou",
	ograve:"mal? latinsk? p?smeno o s opa?n?m d???om",
	oacute:"mal? latinsk? p?smeno o s d???om",
	ocirc:"mal? latinsk? p?smeno o so strie?kou",
	otilde:"mal? latinsk? p?smeno o s tildou",
	ouml:"mal? latinsk? p?smeno o prehlasovan?",
	divide:"znak delenia",
	oslash:"mal? latinsk? p?smeno o s pre?iarknut?m",
	ugrave:"mal? latinsk? p?smeno u s opa?n?m d???om",
	uacute:"mal? latinsk? p?smeno u s d???om",
	ucirc:"mal? latinsk? p?smeno u so strie?kou",
	uuml:"mal? latinsk? p?smeno u prehlasovan?",
	yacute:"mal? latinsk? p?smeno y s d???om",
	thorn:"mal? latinsk? p?smeno thorn",
	yuml:"mal? latinsk? p?smeno y prehlasovan?",

// Greek Characters and Symbols
	fnof:"mal? latinsk? p?smeno f s h??ikom",
	Alpha:"ve?k? gr?cke p?smeno alfa",
	Beta:"ve?k? gr?cke p?smeno beta",
	Gamma:"ve?k? gr?cke p?smeno gama",
	Delta:"ve?k? gr?cke p?smeno delta",
	Epsilon:"ve?k? gr?cke p?smeno epsilon",
	Zeta:"ve?k? gr?cke p?smeno z?ta",
	Eta:"ve?k? gr?cke p?smeno ?ta",
	Theta:"ve?k? gr?cke p?smeno t?ta",
	Iota:"ve?k? gr?cke p?smeno jota",
	Kappa:"ve?k? gr?cke p?smeno kapa",
	Lambda:"ve?k? gr?cke p?smeno lambda",
	Mu:"ve?k? gr?cke p?smeno m?",
	Nu:"ve?k? gr?cke p?smeno n?",
	Xi:"ve?k? gr?cke p?smeno ks?",
	Omicron:"ve?k? gr?cke p?smeno omikron",
	Pi:"ve?k? gr?cke p?smeno p?",
	Rho:"ve?k? gr?cke p?smeno r?",
	Sigma:"ve?k? gr?cke p?smeno sigma",
	Tau:"ve?k? gr?cke p?smeno tau",
	Upsilon:"ve?k? gr?cke p?smeno ypsilon",
	Phi:"ve?k? gr?cke p?smeno f?",
	Chi:"ve?k? gr?cke p?smeno ch?",
	Psi:"ve?k? gr?cke p?smeno ps?",
	Omega:"ve?k? gr?cke p?smeno omega",
	alpha:"mal? gr?cke p?smeno alfa",
	beta:"mal? gr?cke p?smeno beta",
	gamma:"mal? gr?cke p?smeno gama",
	delta:"mal? gr?cke p?smeno delta",
	epsilon:"mal? gr?cke p?smeno epsilon",
	zeta:"mal? gr?cke p?smeno z?ta",
	eta:"mal? gr?cke p?smeno ?ta",
	theta:"mal? gr?cke p?smeno t?ta",
	iota:"mal? gr?cke p?smeno jota",
	kappa:"mal? gr?cke p?smeno kapa",
	lambda:"mal? gr?cke p?smeno lambda",
	mu:"mal? gr?cke p?smeno m?",
	nu:"mal? gr?cke p?smeno n?",
	xi:"mal? gr?cke p?smeno ks?",
	omicron:"mal? gr?cke p?smeno omikron",
	pi:"mal? gr?cke p?smeno p?",
	rho:"mal? gr?cke p?smeno r?",
	sigmaf:"mal? gr?cke p?smeno sigma (koncov?)",
	sigma:"mal? gr?cke p?smeno sigma",
	tau:"mal? gr?cke p?smeno tau",
	upsilon:"mal? gr?cke p?smeno ypsilon",
	phi:"mal? gr?cke p?smeno f?",
	chi:"mal? gr?cke p?smeno ch?",
	psi:"mal? gr?cke p?smeno ps?",
	omega:"mal? gr?cke p?smeno omega",
	thetasym:"mal? gr?cke p?smeno t?ta",
	upsih:"gr?cky znak ypsilon s h??ikom",
	piv:"gr?cky symbol p?",
	bull:"odr??ka\nmal? ?ierny kr??ok",
	hellip:"tri body vodorovne",
	prime:"min?ty\nstopa",
	Prime:"sekundy\npalce",
	oline:"?iara nad riadkom",
	frasl:"lomka",
	weierp:"ve?k? p?san? p?smeno P\nmocninn? rad",
	image:"gotick? ve?k? p?smeno I\nimagin?rna ?as?",
	real:"gotick? ve?k? p?smeno R\nre?lna ?as?",
	trade:"znak ochrannej zn?mky",
	alefsym:"symbol alef",
	larr:"??pka do?ava",
	uarr:"??pka nahor",
	rarr:"??pka doprava",
	darr:"??pka nadol",
	harr:"??pka v?avo-vpravo",
	crarr:"lomen? ??pka nadol do?ava\nn?vrat voz?ka",
	lArr:"dvojit? ??pka do?ava",
	uArr:"dvojit? ??pka nahor",
	rArr:"dvojit? ??pka doprava",
	dArr:"dvojit? ??pka nadol",
	hArr:"dvojit? ??pka v?avo-vpravo",
	forall:"pre v?etky",
	part:"?iasto?n? rozdiel",
	exist:"existuje",
	empty:"pr?zdna mno?ina\npriemer",
	nabla:"nabla\nopa?n? rozdiel",
	isin:"prvok z",
	notin:"nie je prvok z",
	ni:"obsahuje ako ?len",
	prod:"n-?rny s??in\nznak s??inu",
	sum:"n-?rny s??et",
	minus:"znak m?nus",
	lowast:"oper?tor hviezdi?ka",
	radic:"druh? odmocnina",
	prop:"proporcion?lne k",
	infin:"nekone?no",
	ang:"uhol",
	and:"logick? a",
	or:"logick? alebo",
	cap:"prienik",
	cup:"zjednotenie","int":"integr?l",
	there4:"preto",
	sim:"oper?tor tilda\nmen? sa\npodobn?",
	cong:"pribli?ne rovn?",
	asymp:"takmer rovn?\nasymptotick? k",
	ne:"nerovn?",
	equiv:"identick?",
	le:"men?? ako alebo rovn?",
	ge:"v???? ako alebo rovn?",
	sub:"podmno?ina",
	sup:"nadmno?ina",
	nsub:"nie podmno?ina",
	sube:"podmno?ina alebo rovn?",
	supe:"nadmno?ina alebo rovn?",
	oplus:"plus v kr??ku\npriamy s??et",
	otimes:"kr?t v kr??ku\nvektorov? s??in",
	perp:"oto?en? klin?ek\nortogon?lny\nkolm?",
	sdot:"oper?tor bodka",
	lceil:"?av? strop",
	rceil:"prav? strop",
	lfloor:"?av? podlaha",
	rfloor:"prav? podlaha",
	lang:"hranat? z?tvorka smeruj?ca do?ava",
	rang:"hranat? z?tvorka smeruj?ca doprava",
	loz:"koso?tvorec",
	spades:"?ierny znak pikovej karty",
	clubs:"?ierny znak kr??ovej karty",
	hearts:"?ierny znak gu?ovej karty",
	diams:"?ierny znak k?rovej karty",
	OElig:"ve?k? latinsk? ligat?ra OE",
	oelig:"mal? latinsk? ligat?ra oe",
	Scaron:"ve?k? latinsk? p?smeno S s m?k?e?om",
	scaron:"mal? latinsk? p?smeno s s m?k?e?om",
	Yuml:"ve?k? latinsk? p?smeno Y prehlasovan?",
	circ:"znak strie?ky",
	tilde:"mal? tilda",
	ensp:"kr?tka medzera",
	emsp:"dlh? medzera",
	thinsp:"tenk? medzera",
	zwnj:"nespojova? nulovej d??ky",
	zwj:"spojova? nulovej d??ky",
	lrm:"zna?ka z?ava-doprava",
	rlm:"zna?ka sprava-do?ava",
	ndash:"poml?ka",
	mdash:"dlh? poml?ka",
	lsquo:"jednoduch? ?av? ?vodzovka",
	rsquo:"jednoduch? prav? ?vodzovka",
	sbquo:"jednoduch? doln? ?av? ?vodzovka",
	ldquo:"dvojit? ?av? ?vodzovka",
	rdquo:"dvojit? prav? ?vodzovka",
	bdquo:"dvojit? doln? ?av? ?vodzovka",
	dagger:"kr??ik",
	Dagger:"dvojit? kr??ik",
	permil:"znak promile",
	lsaquo:"jednoduch? ?av? ukazovate?",
	rsaquo:"jednoduch? prav? ukazovate?",
	euro:"znak euro"
})

//end v1.x content
);
