/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"obr?cen? vyk?i?n?k",
	cent:"znak cent",
	pound:"znak libra",
	curren:"znak m?na",
	yen:"znak yen\nznak yuan",
	brvbar:"p?eru?en? ??ra\np?eru?en? svisl? ??ra",
	sect:"znak paragraf",
	uml:"vodorovn? dvojte?ka\np?ehl?ska",
	copy:"znak copyright",
	ordf:"indik?tor ?ensk?ho rodu",
	laquo:"dvojit? lev? ?ipka",
	not:"znak negace",
	shy:"spojovn?k\nrozd?lovn?k",
	reg:"znak registrov?no\nznak registrovan? ochrann? zn?mka",
	macr:"nadtr??tko",
	deg:"znak stupe?",
	plusmn:"znak plus-minus\nznak plus nebo minus",
	sup2:"2, horn? index\ndruh? mocnina\nplo?n? m?ra",
	sup3:"3, horn? index\nt?et? mocnina\nkrychlov? m?ra",
	acute:"??rka naho?e",
	micro:"znak mikro",
	para:"znak konec odstavce",
	middot:"te?ka uprost?ed",
	cedil:"cedilla\nspodn? h??ek",
	sup1:"1, horn? index",
	ordm:"indik?tor mu?sk?ho rodu",
	raquo:"dvojit? prav? ?ipka",
	frac14:"jednoduch? zlomek jedna ?tvrtina\nzlomek jedna ?tvrtina",
	frac12:"jednoduch? zlomek jedna polovina\nzlomek jedna polovina",
	frac34:"jednoduch? zlomek t?i ?tvrtiny\nzlomek t?i ?tvrtiny",
	iquest:"obr?cen? otazn?k\noto?en? otazn?k",
	Agrave:"velk? p?smeno A s obr?cenou ??rkou",
	Aacute:"velk? p?smeno A s ??rkou",
	Acirc:"velk? p?smeno A se st???kou",
	Atilde:"velk? p?smeno A s vlnovkou",
	Auml:"velk? p?smeno A s p?ehl?skou",
	Aring:"velk? p?smeno A s krou?kem naho?e",
	AElig:"velk? p?smeno AE\nslitek AE, velk?",
	Ccedil:"velk? p?smeno C se spodn?m h??kem",
	Egrave:"velk? p?smeno E s obr?cenou ??rkou",
	Eacute:"velk? p?smeno E s ??rkou",
	Ecirc:"velk? p?smeno E se st???kou",
	Euml:"velk? p?smeno E s p?ehl?skou",
	Igrave:"velk? p?smeno I s obr?cenou ??rkou",
	Iacute:"velk? p?smeno I s ??rkou",
	Icirc:"velk? p?smeno I se st???kou",
	Iuml:"velk? p?smeno I s p?ehl?skou",
	ETH:"velk? p?smeno ETH",
	Ntilde:"velk? p?smeno N s vlnovkou",
	Ograve:"velk? p?smeno O s obr?cenou ??rkou",
	Oacute:"velk? p?smeno O s ??rkou",
	Ocirc:"velk? p?smeno O se st???kou",
	Otilde:"velk? p?smeno O s vlnovkou",
	Ouml:"velk? p?smeno O s p?ehl?skou",
	times:"znak n?soben?",
	Oslash:"velk? p?smeno O s p?e?krtnut?m",
	Ugrave:"velk? p?smeno U s obr?cenou ??rkou",
	Uacute:"velk? p?smeno U s ??rkou",
	Ucirc:"velk? p?smeno U se st???kou",
	Uuml:"velk? p?smeno U s p?ehl?skou",
	Yacute:"velk? p?smeno Y s ??rkou",
	THORN:"velk? p?smeno THORN",
	szlig:"mal? p?smeno ostr? s",
	agrave:"mal? p?smeno a s obr?cenou ??rkou",
	aacute:"mal? p?smeno a s ??rkou",
	acirc:"mal? p?smeno a se st???kou",
	atilde:"mal? p?smeno a s vlnovkou",
	auml:"mal? p?smeno a s p?ehl?skou",
	aring:"mal? p?smeno a s krou?kem naho?e",
	aelig:"mal? p?smeno ae\nslitek ae, mal?",
	ccedil:"mal? p?smeno c se spodn?m h??kem",
	egrave:"mal? p?smeno e s obr?cenou ??rkou",
	eacute:"mal? p?smeno e s ??rkou",
	ecirc:"mal? p?smeno e se st???kou",
	euml:"mal? p?smeno e s p?ehl?skou",
	igrave:"mal? p?smeno i s obr?cenou ??rkou",
	iacute:"mal? p?smeno i s ??rkou",
	icirc:"mal? p?smeno i se st???kou",
	iuml:"mal? p?smeno i s p?ehl?skou",
	eth:"mal? p?smeno eth",
	ntilde:"mal? p?smeno n s vlnovkou",
	ograve:"mal? p?smeno o s obr?cenou ??rkou",
	oacute:"mal? p?smeno o s ??rkou",
	ocirc:"mal? p?smeno o se st???kou",
	otilde:"mal? p?smeno o s vlnovkou",
	ouml:"mal? p?smeno o s p?ehl?skou",
	divide:"znak d?len?",
	oslash:"mal? p?smeno o s p?e?krtnut?m",
	ugrave:"mal? p?smeno u s obr?cenou ??rkou",
	uacute:"mal? p?smeno u s ??rkou",
	ucirc:"mal? p?smeno u se st???kou",
	uuml:"mal? p?smeno u s p?ehl?skou",
	yacute:"mal? p?smeno y s ??rkou",
	thorn:"mal? p?smeno thorn",
	yuml:"mal? p?smeno y s p?ehl?skou",

// Greek Characters and Symbols
	fnof:"mal? p?smeno f se zahnut?m h??kem\nfunkce\nflorin",
	Alpha:"velk? ?eck? p?smeno alfa",
	Beta:"velk? ?eck? p?smeno beta",
	Gamma:"velk? ?eck? p?smeno gama",
	Delta:"velk? ?eck? p?smeno delta",
	Epsilon:"velk? ?eck? p?smeno epsilon",
	Zeta:"velk? ?eck? p?smeno z?ta",
	Eta:"velk? ?eck? p?smeno ?ta",
	Theta:"velk? ?eck? p?smeno th?ta",
	Iota:"velk? ?eck? p?smeno j?ta",
	Kappa:"velk? ?eck? p?smeno kappa",
	Lambda:"velk? ?eck? p?smeno lambda",
	Mu:"velk? ?eck? p?smeno m?",
	Nu:"velk? ?eck? p?smeno n?",
	Xi:"velk? ?eck? p?smeno ks?",
	Omicron:"velk? ?eck? p?smeno omikr?n",
	Pi:"velk? ?eck? p?smeno p?",
	Rho:"velk? ?eck? p?smeno r?",
	Sigma:"velk? ?eck? p?smeno sigma",
	Tau:"velk? ?eck? p?smeno tau",
	Upsilon:"velk? ?eck? p?smeno ypsilon",
	Phi:"velk? ?eck? p?smeno f?",
	Chi:"velk? ?eck? p?smeno ch?",
	Psi:"velk? ?eck? p?smeno ps?",
	Omega:"velk? ?eck? p?smeno ?mega",
	alpha:"mal? ?eck? p?smeno alfa",
	beta:"mal? ?eck? p?smeno beta",
	gamma:"mal? ?eck? p?smeno gama",
	delta:"mal? ?eck? p?smeno delta",
	epsilon:"mal? ?eck? p?smeno epsilon",
	zeta:"mal? ?eck? p?smeno z?ta",
	eta:"mal? ?eck? p?smeno ?ta",
	theta:"mal? ?eck? p?smeno th?ta",
	iota:"mal? ?eck? p?smeno j?ta",
	kappa:"mal? ?eck? p?smeno kappa",
	lambda:"mal? ?eck? p?smeno lambda",
	mu:"mal? ?eck? p?smeno m?",
	nu:"mal? ?eck? p?smeno n?",
	xi:"mal? ?eck? p?smeno ks?",
	omicron:"mal? ?eck? p?smeno omikr?n",
	pi:"mal? ?eck? p?smeno p?",
	rho:"mal? ?eck? p?smeno r?",
	sigmaf:"mal? ?eck? p?smeno koncov? sigma",
	sigma:"mal? ?eck? p?smeno sigma",
	tau:"mal? ?eck? p?smeno tau",
	upsilon:"mal? ?eck? p?smeno ypsilon",
	phi:"mal? ?eck? p?smeno f?",
	chi:"mal? ?eck? p?smeno ch?",
	psi:"mal? ?eck? p?smeno ps?",
	omega:"mal? ?eck? p?smeno ?mega",
	thetasym:"symbol mal?ho ?eck?ho p?smena th?ta",
	upsih:"symbol ?eck?ho p?smena ypsilon se zahnut?m h??kem",
	piv:"?eck? symbol p?",
	bull:"odr??ka\nmal? ?ern? krou?ek",
	hellip:"vodorovn? v?pustka\nt?i te?ky",
	prime:"??rka naho?e\nminuty\nstopy",
	Prime:"dvojit? ??rka naho?e\nsekundy\npalce",
	oline:"nadtr??tko\npruh",
	frasl:"lom?tko u zlomk?",
	weierp:"stylizovan? velk? p?smeno P\npoten?n? mno?ina\nWeierstrassovo p?smeno p",
	image:"velk? p?smeno I, ?vabach\nimagin?rn? ??st",
	real:"velk? p?smeno R, ?vabach\nsymbol re?ln? ??sti",
	trade:"znak ochrann? zn?mka",
	alefsym:"symbol alef\nprvn? transfinitn? kardin?l",
	larr:"?ipka doleva",
	uarr:"?ipka nahoru",
	rarr:"?ipka doprava",
	darr:"?ipka dol?",
	harr:"?ipka doleva a doprava",
	crarr:"?ipka dol? zahnut? doleva\nn?vrat voz?ku, konec ??dku",
	lArr:"dvojit? ?ipka doleva",
	uArr:"dvojit? ?ipka nahoru",
	rArr:"dvojit? ?ipka doprava",
	dArr:"dvojit? ?ipka dol?",
	hArr:"dvojit? ?ipka doleva a doprava",
	forall:"pro v?echny",
	part:"parci?ln? diferenci?l",
	exist:"existuje",
	empty:"pr?zdn? mno?ina\nnulov? mno?ina\npr?m?r",
	nabla:"nabla\nzp?tn? diference",
	isin:"prvek mno?iny",
	notin:"nen? prvkem mno?iny",
	ni:"obsahuje jako ?lena",
	prod:"n-?rn? sou?in\nznak sou?in",
	sum:"n-?rn? sou?et",
	minus:"znak minus",
	lowast:"oper?tor hv?zdi?ka",
	radic:"druh? odmocnina",
	prop:"?m?rn?",
	infin:"nekone?no",
	ang:"?hel",
	and:"logick? oper?tor a\nkl?n s hrotem nahoru",
	or:"logick? oper?tor nebo\nkl?n s hrotem dol?",
	cap:"pr?nik\noblouk vypoukl? nahoru",
	cup:"sjednocen?\noblouk vypoukl? dol?","int":"integr?l",
	there4:"a proto",
	sim:"oper?tor tilda\nzm?na podle\npodobn?",
	cong:"p?ibli?n? rovno",
	asymp:"t?m?? rovno\nasymptotick? k",
	ne:"nen? rovno",
	equiv:"shodn? s",
	le:"men?? ne? nebo rovno",
	ge:"v?t?? ne? nebo rovno",
	sub:"podmno?ina",
	sup:"nadmno?ina",
	nsub:"nen? podmno?inou",
	sube:"podmno?ina nebo shodn? s",
	supe:"nadmno?ina nebo shodn? s",
	oplus:"znak plus v krou?ku\np??m? sou?et",
	otimes:"znak n?soben? v krou?ku\nvektorov? sou?in",
	perp:"kolmice\nortogon?ln? k\nkolm? na",
	sdot:"oper?tor te?ka",
	lceil:"lev? horn? cel? ??st",
	rceil:"prav? horn? cel? ??st",
	lfloor:"lev? doln? cel? ??st",
	rfloor:"prav? doln? cel? ??st",
	lang:"lev? lomen? z?vorka",
	rang:"prav? lomen? z?vorka",
	loz:"koso?tverec",
	spades:"piky",
	clubs:"k???e\ntrojl?stek",
	hearts:"srdce\nvalent?n",
	diams:"k?ry",
	OElig:"slitek OE, velk?",
	oelig:"slitek oe, mal?",
	Scaron:"velk? p?smeno S s h??kem",
	scaron:"mal? p?smeno s s h??kem",
	Yuml:"velk? p?smeno Y s p?ehl?skou",
	circ:"st???ka, modifik?tor p?smen",
	tilde:"mal? vlnovka",
	ensp:"?zk? mezera",
	emsp:"?irok? mezera",
	thinsp:"z??en? mezera",
	zwnj:"z?kaz spojen?, nulov? ???ka",
	zwj:"spojen?, nulov? ???ka",
	lrm:"zna?ka sm?ru zleva doprava",
	rlm:"zna?ka sm?ru zprava doleva",
	ndash:"kr?tk? poml?ka",
	mdash:"dlouh? poml?ka",
	lsquo:"lev? apostrof",
	rsquo:"prav? apostrof",
	sbquo:"doln? apostrof",
	ldquo:"lev? uvozovky",
	rdquo:"prav? uvozovky",
	bdquo:"doln? uvozovky",
	dagger:"k???ek",
	Dagger:"dvojit? k???ek",
	permil:"znak promile",
	lsaquo:"lev? ?ipka",
	rsaquo:"prav? ?ipka",
	euro:"znak euro"
})

//end v1.x content
);
