/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "azul alice",
antiquewhite: "branco antigo",
aqua: "verde-?gua",
aquamarine: "verde-azulado",
azure: "azul-celeste",
beige: "bege",
bisque: "rosa-velho",
black: "preto",
blanchedalmond: "am?ndoa claro",
blue: "azul",
blueviolet: "azul violeta",
brown: "castanho",
burlywood: "castanho pinho",
cadetblue: "azul cadete",
chartreuse: "amarelo esverdeado",
chocolate: "chocolate",
coral: "coral",
cornflowerblue: "azul-viol?ceo",
cornsilk: "branco seda",
crimson: "carmesim",
cyan: "ciano",
darkblue: "azul escuro",
darkcyan: "ciano escuro",
darkgoldenrod: "ouro velho escuro",
darkgray: "cinzento escuro",
darkgreen: "verde escuro",
darkgrey: "cinzento escuro", // same as darkgray
darkkhaki: "caqui escuro",
darkmagenta: "magenta escuro",
darkolivegreen: "verde-azeitona escuro",
darkorange: "laranja escuro",
darkorchid: "orqu?dea escuro",
darkred: "vermelho escuro",
darksalmon: "salm?o escuro",
darkseagreen: "verde marinho escuro",
darkslateblue: "azul ard?sia escuro",
darkslategray: "cinzento ard?sia escuro",
darkslategrey: "cinzento ard?sia escuro", // same as darkslategray
darkturquoise: "turquesa escuro",
darkviolet: "violeta escuro",
deeppink: "rosa profundo",
deepskyblue: "azul c?u profundo",
dimgray: "cinzento esbatido",
dimgrey: "cinzento esbatido", // same as dimgray
dodgerblue: "azul furtivo",
firebrick: "tijolo fogo",
floralwhite: "branco floral",
forestgreen: "verde floresta",
fuchsia: "f?csia",
gainsboro: "cinzento azulado claro",
ghostwhite: "branco sombreado",
gold: "dourado",
goldenrod: "ouro velho",
gray: "cinzento",
green: "verde",
greenyellow: "amarelo esverdeado",
grey: "cinzento", // same as gray
honeydew: "mel",
hotpink: "rosa forte",
indianred: "almagre",
indigo: "?ndigo",
ivory: "marfim",
khaki: "caqui",
lavender: "alfazema",
lavenderblush: "alfazema rosado",
lawngreen: "verde relva",
lemonchiffon: "lim?o chiffon",
lightblue: "azul claro",
lightcoral: "coral claro",
lightcyan: "ciano claro",
lightgoldenrodyellow: "ouro velho amarelado claro",
lightgray: "cinzento claro",
lightgreen: "verde claro",
lightgrey: "cinzento claro", // same as lightgray
lightpink: "rosa claro",
lightsalmon: "salm?o claro",
lightseagreen: "verde marinho claro",
lightskyblue: "azul c?u claro",
lightslategray: "cinzento ard?sia claro",
lightslategrey: "cinzento ard?sia claro", // same as lightslategray
lightsteelblue: "azul-a?o claro",
lightyellow: "amarelo claro",
lime: "lima",
limegreen: "verde-lima",
linen: "linho",
magenta: "magenta",
maroon: "bordeaux",
mediumaquamarine: "verde-azulado m?dio",
mediumblue: "azul m?dio",
mediumorchid: "orqu?dea m?dio",
mediumpurple: "roxo m?dio",
mediumseagreen: "verde marinho m?dio",
mediumslateblue: "azul ard?sia m?dio",
mediumspringgreen: "verde primavera m?dio",
mediumturquoise: "turquesa m?dio",
mediumvioletred: "violeta avermelhado m?dio",
midnightblue: "azul meia-noite",
mintcream: "creme de menta",
mistyrose: "rosa p?lido",
moccasin: "mocassim",
navajowhite: "branco navajo",
navy: "azul marinho",
oldlace: "renda antiga",
olive: "azeitona",
olivedrab: "azeitona claro",
orange: "laranja",
orangered: "vermelho alaranjado",
orchid: "orqu?dea",
palegoldenrod: "ouro velho p?lido",
palegreen: "verde p?lido",
paleturquoise: "turquesa p?lido",
palevioletred: "violeta avermelhado p?lido",
papayawhip: "creme de papaia",
peachpuff: "p?ssego",
peru: "peru",
pink: "rosa",
plum: "cor-de-ameixa",
powderblue: "azul de esmalte",
purple: "roxo",
red: "vermelho",
rosybrown: "castanho rosado",
royalblue: "azul real",
saddlebrown: "castanho sela",
salmon: "salm?o",
sandybrown: "castanho areia",
seagreen: "verde marinho",
seashell: "concha",
sienna: "castanho-avermelhado",
silver: "prateado",
skyblue: "azul c?u",
slateblue: "azul ard?sia",
slategray: "cinzento ard?sia",
slategrey: "cinzento ard?sia", // same as slategray
snow: "branco-neve",
springgreen: "verde primavera",
steelblue: "azul-a?o",
tan: "castanho claro",
teal: "verde-azulado",
thistle: "cardo",
tomato: "vermelho tomate",
turquoise: "turquesa",
violet: "violeta",
wheat: "trigo",
white: "branco",
whitesmoke: "fumo branco",
yellow: "amarelo",
yellowgreen: "verde amarelado"
})
//end v1.x content
);
