/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "blau cian clar",
antiquewhite: "blanc antic",
aqua: "aigua",
aquamarine: "aiguamarina",
azure: "atzur",
beige: "beix",
bisque: "crema",
black: "negre",
blanchedalmond: "ametlla p?l?lid",
blue: "blau",
blueviolet: "blau violeta",
brown: "marr?",
burlywood: "marr? aren?s",
cadetblue: "blau mar?",
chartreuse: "Llimona p?l?lid",
chocolate: "xocolata",
coral: "corall",
cornflowerblue: "blau blauet",
cornsilk: "cru",
crimson: "carmes?",
cyan: "cian",
darkblue: "blau fosc",
darkcyan: "cian fosc",
darkgoldenrod: "ocre fosc",
darkgray: "gris fosc",
darkgreen: "verd fosc",
darkgrey: "gris fosc", // same as darkgray
darkkhaki: "caqui fosc",
darkmagenta: "magenta fosc",
darkolivegreen: "verd oliva fosc",
darkorange: "taronja fosc",
darkorchid: "orqu?dia fosc",
darkred: "vermell fosc",
darksalmon: "salm? fosc",
darkseagreen: "verd mar? fosc",
darkslateblue: "blau pissarra fosc",
darkslategray: "gris pissarra fosc",
darkslategrey: "gris pissarra fosc", // same as darkslategray
darkturquoise: "turquesa fosc",
darkviolet: "violeta fosc",
deeppink: "rosa profund",
deepskyblue: "blau cel profund",
dimgray: "gris fosc",
dimgrey: "gris fosc", // same as dimgray
dodgerblue: "blau Dodger",
firebrick: "ma? refractari",
floralwhite: "blanc floral",
forestgreen: "verd bosc",
fuchsia: "f?csia",
gainsboro: "gainsboro",
ghostwhite: "blanc fantasma",
gold: "daurat",
goldenrod: "ocre",
gray: "gris",
green: "verd",
greenyellow: "verd grog?s",
grey: "gris", // same as gray
honeydew: "rosada de mel",
hotpink: "rosa f?csia",
indianred: "vermell indi",
indigo: "?ndigo",
ivory: "marbre",
khaki: "caqui",
lavender: "lavanda",
lavenderblush: "lavanda vermellosa",
lawngreen: "verd gespa",
lemonchiffon: "groc brisa",
lightblue: "blau clar",
lightcoral: "corall clar",
lightcyan: "cian clar",
lightgoldenrodyellow: "groc ocre clar",
lightgray: "gris clar",
lightgreen: "verd clar",
lightgrey: "gris clar", // same as lightgray
lightpink: "rosa clar",
lightsalmon: "salm? clar",
lightseagreen: "verd mar? clar",
lightskyblue: "blau cel clar",
lightslategray: "gris pissarra clar",
lightslategrey: "gris pissarra clar", // same as lightslategray
lightsteelblue: "blau acer clar",
lightyellow: "groc clar",
lime: "verd llimona",
limegreen: "verd llimona verda",
linen: "lli",
magenta: "magenta",
maroon: "marr? vermell?s",
mediumaquamarine: "aiguamarina mitjana",
mediumblue: "blau mitj?",
mediumorchid: "orqu?dia mitjana",
mediumpurple: "porpra mitjana",
mediumseagreen: "verd mar? mitj?",
mediumslateblue: "blau pissarra mitj?",
mediumspringgreen: "verd primavera mitj?",
mediumturquoise: "turquesa mitjana",
mediumvioletred: "vermell violeta mitj?",
midnightblue: "blau mitjanit",
mintcream: "menta p?l?lid",
mistyrose: "rosa dens",
moccasin: "mocass?",
navajowhite: "blanc Navajo",
navy: "blau mar?",
oldlace: "rosa crem?s",
olive: "oliva",
olivedrab: "gris oliva",
orange: "taronja",
orangered: "taronja vermell?s",
orchid: "orqu?dia",
palegoldenrod: "ocre p?l?lid",
palegreen: "verd p?l?lid",
paleturquoise: "turquesa p?l?lid",
palevioletred: "vermell porpra p?l?lid",
papayawhip: "pr?ssec pastel",
peachpuff: "pr?ssec",
peru: "Per?",
pink: "rosa",
plum: "pruna",
powderblue: "blau gris?s",
purple: "porpra",
red: "vermell",
rosybrown: "marr? rosat",
royalblue: "blau mar? intens",
saddlebrown: "marr? mitj?",
salmon: "salm?",
sandybrown: "marr? aren?s",
seagreen: "verd mar?",
seashell: "petxina marina",
sienna: "siena",
silver: "argent",
skyblue: "blau cel",
slateblue: "blau pissarra",
slategray: "gris pissarra",
slategrey: "gris pissarra", // same as slategray
snow: "neu",
springgreen: "verd de primavera",
steelblue: "blau acer",
tan: "tan",
teal: "verd blav?s",
thistle: "card",
tomato: "tom?quet",
turquoise: "turquesa",
violet: "violeta",
wheat: "blat",
white: "blanc",
whitesmoke: "blanc fumat",
yellow: "groc",
yellowgreen: "verd grog?s"
})

//end v1.x content
);
