/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "alice blue modra",
antiquewhite: "anti?no bela",
aqua: "akva",
aquamarine: "akvamarin",
azure: "azurno modra",
beige: "be?",
bisque: "porcelanasta",
black: "?rna",
blanchedalmond: "obledelo mandljeva",
blue: "modra",
blueviolet: "modro vijoli?na",
brown: "rjava",
burlywood: "pe??eno sivo-rjava",
cadetblue: "kadetsko modra",
chartreuse: "chartreuse",
chocolate: "?okoladna",
coral: "koralna",
cornflowerblue: "plavi?asto modra",
cornsilk: "koruzna",
crimson: "karminasta",
cyan: "cijan",
darkblue: "temno modra",
darkcyan: "temno cijan",
darkgoldenrod: "temna zlata rozga",
darkgray: "temno siva",
darkgreen: "temno zelena",
darkgrey: "temno siva", // same as darkgray
darkkhaki: "temno kaki",
darkmagenta: "temna magenta",
darkolivegreen: "temna olivno zelena",
darkorange: "temno oran?na",
darkorchid: "temno orhidejasta",
darkred: "temno rde?a",
darksalmon: "temno lososova",
darkseagreen: "temno morsko zelena",
darkslateblue: "temno skrilasto modra",
darkslategray: "temno skrilasto siva",
darkslategrey: "temno skrilasto siva", // same as darkslategray
darkturquoise: "temno turkizna",
darkviolet: "temno vijoli?na",
deeppink: "temno ro?nata",
deepskyblue: "temno nebe?ko modra",
dimgray: "pepelnato siva",
dimgrey: "pepelnato siva", // same as dimgray
dodgerblue: "dodgersko modra",
firebrick: "ope?nata",
floralwhite: "cvetno bela",
forestgreen: "gozdno zelena",
fuchsia: "fuksija",
gainsboro: "gainsboro",
ghostwhite: "sen?nato bela",
gold: "zlata",
goldenrod: "zlata rozga",
gray: "siva",
green: "zelena",
greenyellow: "zeleno-rumena",
grey: "siva", // same as gray
honeydew: "medena rosa",
hotpink: "kri?e?e ro?nata",
indianred: "indijansko rde?a",
indigo: "indigo",
ivory: "slonoko??ena",
khaki: "kaki",
lavender: "sivka",
lavenderblush: "ro?nato sivka",
lawngreen: "travni?ko zelena",
lemonchiffon: "limonast ?ifon",
lightblue: "svetlo modra",
lightcoral: "svetlo koralna",
lightcyan: "svetlo cijan",
lightgoldenrodyellow: "svetlo rumena zlata rozga",
lightgray: "svetlo siva",
lightgreen: "svetlo zelena",
lightgrey: "svetlo siva", // same as lightgray
lightpink: "svetlo ro?nata",
lightsalmon: "svetlo lososova",
lightseagreen: "svetlo morsko zelena",
lightskyblue: "svetlo nebe?ko modra",
lightslategray: "svetlo skrilasto siva",
lightslategrey: "svetlo skrilasto siva", // same as lightslategray
lightsteelblue: "svetlo kovinsko modra",
lightyellow: "svetlo rumena",
lime: "limetasta",
limegreen: "apneno zelena",
linen: "lanena",
magenta: "magenta",
maroon: "kostanjeva",
mediumaquamarine: "srednji akvamarin",
mediumblue: "srednje modra",
mediumorchid: "srednje orhidejasta",
mediumpurple: "srednje ?krlatna",
mediumseagreen: "srednje morsko zelena",
mediumslateblue: "srednje skrilasto modra",
mediumspringgreen: "srednje pomladno zelena",
mediumturquoise: "srednje turkizna",
mediumvioletred: "srednje vijoli?no rde?a",
midnightblue: "polno?no modra",
mintcream: "metina krema",
mistyrose: "megleno ro?nata",
moccasin: "mokasinasta",
navajowhite: "navajo bela",
navy: "mornarska",
oldlace: "stara ?ipka",
olive: "olivna",
olivedrab: "umazano olivna",
orange: "oran?na",
orangered: "oran?no-rde?a",
orchid: "orhidejasta",
palegoldenrod: "bleda zlata rozga",
palegreen: "bledo zelena",
paleturquoise: "bledo turkizna",
palevioletred: "bledo vijoli?no-rde?a",
papayawhip: "papaja",
peachpuff: "breskova",
peru: "perujska",
pink: "ro?nata",
plum: "slivova",
powderblue: "kobaltovo modra",
purple: "?krlatna",
red: "rde?a",
rosybrown: "ro?nato rjava",
royalblue: "kraljevsko modra",
saddlebrown: "sedlasto rjava",
salmon: "lososova",
sandybrown: "pe??eno rjava",
seagreen: "morsko zelena",
seashell: "morska lupina",
sienna: "sienna",
silver: "srebrna",
skyblue: "nebe?ko modra",
slateblue: "skrilasto modra",
slategray: "skrilasto siva",
slategrey: "skrilasto siva", // same as slategray
snow: "sne?ena",
springgreen: "pomladno zelena",
steelblue: "kovinsko modra",
tan: "rumeno-rjava",
teal: "modrozelena",
thistle: "osatna",
tomato: "paradi?nikova",
turquoise: "turkizna",
violet: "vijoli?na",
wheat: "p?eni?na",
white: "bela",
whitesmoke: "megleno bela",
yellow: "rumena",
yellowgreen: "rumeno-zelena"
})
//end v1.x content
);
