/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"omv?nt utropstecken",
	cent:"centtecken",
	pound:"pundtecken",
	curren:"valutatecken",
	yen:"yentecken\nyuantecken",
	brvbar:"brutet lodr?tt streck",
	sect:"avsnittstecken",
	uml:"trema",
	copy:"copyrighttecken",
	ordf:"indikator f?r feminint ordningstal",
	laquo:"dubbelt v?nstercitattecken",
	not:"inte-tecken",
	shy:"mjukt blanksteg",
	reg:"registrerat varum?rke-tecken",
	macr:"makron",
	deg:"gradtecken",
	plusmn:"plus/minus-tecken\nplus/minus-tecken",
	sup2:"upph?jd tv?a\nkvadrat",
	sup3:"upph?jd trea\nkubik",
	acute:"akut accent",
	micro:"mikrotecken",
	para:"alinea\nstycketecken",
	middot:"halvh?g punkt",
	cedil:"cedilj",
	sup1:"upph?jd etta",
	ordm:"indikator f?r maskulint ordningstal",
	raquo:"dubbelt h?gercitattecken",
	frac14:"en fj?rdedel",
	frac12:"en halv",
	frac34:"tre fj?rdedelar",
	iquest:"omv?nt fr?getecken",
	Agrave:"versalt latinskt a med grav accent",
	Aacute:"versalt latinskt a med akut accent",
	Acirc:"versalt latinskt a med cirkumflex",
	Atilde:"versalt latinskt a med tilde",
	Auml:"versalt latinskt a med trema",
	Aring:"versalt latinskt a med ring",
	AElig:"versal latinsk ae-ligatur",
	Ccedil:"versalt latinskt c med cedilj",
	Egrave:"versalt latinskt e med grav accent",
	Eacute:"versalt latinskt e med akut accent",
	Ecirc:"versalt latinskt e med cirkumflex",
	Euml:"versalt latinskt e med trema",
	Igrave:"versalt latinskt i med grav accent",
	Iacute:"versalt latinskt i med akut accent",
	Icirc:"versalt latinskt i med cirkumflex",
	Iuml:"versalt latinskt i med trema",
	ETH:"versalt latinskt eth",
	Ntilde:"versalt latinskt n med tilde",
	Ograve:"versalt latinskt o med grav accent",
	Oacute:"versalt latinskt o med akut accent",
	Ocirc:"versalt latinskt o med cirkumflex",
	Otilde:"versalt latinskt o med tilde",
	Ouml:"versalt latinskt o med trema",
	times:"multiplikationstecken",
	Oslash:"versalt latinskt o med streck",
	Ugrave:"versalt latinskt u med grav accent",
	Uacute:"versalt latinskt u med akut accent",
	Ucirc:"versalt latinskt u med cirkumflex",
	Uuml:"versalt latinskt u med trema",
	Yacute:"versalt latinskt y med akut accent",
	THORN:"versalt latinskt thorn",
	szlig:"gement latinskt dubbel-s\n?",
	agrave:"gement latinskt a med grav accent",
	aacute:"gement latinskt a med akut accent",
	acirc:"gement latinskt a med cirkumflex",
	atilde:"gement latinskt a med tilde",
	auml:"gement latinskt a med trema",
	aring:"gement latinskt a med ring",
	aelig:"gemen latinsk ae-ligatur",
	ccedil:"gement latinskt c med cedilj",
	egrave:"gement latinskt e med grav accent",
	eacute:"gement latinskt e med akut accent",
	ecirc:"gement latinskt e med cirkumflex",
	euml:"gement latinskt e med trema",
	igrave:"gement latinskt i med grav accent",
	iacute:"gement latinskt i med akut accent",
	icirc:"gement latinskt i med cirkumflex",
	iuml:"gement latinskt i med trema",
	eth:"gement latinskt eth",
	ntilde:"gement latinskt n med tilde",
	ograve:"gement latinskt o med grav accent",
	oacute:"gement latinskt o med akut accent",
	ocirc:"gement latinskt o med cirkumflex",
	otilde:"gement latinskt o med tilde",
	ouml:"gement latinskt o med trema",
	divide:"divisionstecken",
	oslash:"gement latinskt o med streck",
	ugrave:"gement latinskt u med grav accent",
	uacute:"gement latinskt u med akut accent",
	ucirc:"gement latinskt u med cirkumflex",
	uuml:"gement latinskt u med trema",
	yacute:"gement latinskt y med akut accent",
	thorn:"gement latinskt thorn",
	yuml:"gement latinskt y med trema",

// Greek Characters and Symbols
	fnof:"gement latinskt f med krok\nfunktion\nflorin",
	Alpha:"versalt grekiskt alfa",
	Beta:"versalt grekiskt beta",
	Gamma:"versalt grekiskt gamma",
	Delta:"versalt grekiskt delta",
	Epsilon:"versalt grekiskt epsilon",
	Zeta:"versalt grekiskt zeta",
	Eta:"versalt grekiskt eta",
	Theta:"versalt grekiskt theta",
	Iota:"versalt grekiskt iota",
	Kappa:"versalt grekiskt kappa",
	Lambda:"versalt grekiskt lambda",
	Mu:"versalt grekiskt my",
	Nu:"versalt grekiskt ny",
	Xi:"versalt grekiskt xi",
	Omicron:"versalt grekiskt omikron",
	Pi:"versalt grekiskt pi",
	Rho:"versalt grekiskt rho",
	Sigma:"versalt grekiskt sigma",
	Tau:"versalt grekiskt tau",
	Upsilon:"versalt grekiskt ypsilon",
	Phi:"versalt grekiskt fi",
	Chi:"versalt grekiskt chi",
	Psi:"versalt grekiskt psi",
	Omega:"versalt grekiskt omega",
	alpha:"gement grekiskt alfa",
	beta:"gement grekiskt beta",
	gamma:"gement grekiskt gamma",
	delta:"gement grekiskt delta",
	epsilon:"gement grekiskt epsilon",
	zeta:"gement grekiskt zeta",
	eta:"gement grekiskt eta",
	theta:"gement grekiskt theta",
	iota:"gement grekiskt iota",
	kappa:"gement grekiskt kappa",
	lambda:"gement grekiskt lambda",
	mu:"gement grekiskt my",
	nu:"gement grekiskt ny",
	xi:"gement grekiskt xi",
	omicron:"gement grekiskt omikron",
	pi:"gement grekiskt pi",
	rho:"gement grekiskt rho",
	sigmaf:"gement grekiskt slutligt sigma",
	sigma:"gement grekiskt sigma",
	tau:"gement grekiskt tau",
	upsilon:"gement grekiskt ypsilon",
	phi:"gement grekiskt fi",
	chi:"gement grekiskt chi",
	psi:"gement grekiskt psi",
	omega:"gement grekiskt omega",
	thetasym:"gement grekiskt theta",
	upsih:"grekiskt ypsilon med krok",
	piv:"grekisk pi-symbol",
	bull:"punkt\nliten smart cirkel",
	hellip:"ellips\ntre punkter",
	prime:"primtecken\nminuter\nfot",
	Prime:"dubbelt primtecken\nsekunder\ntum",
	oline:"?verstrykning\navst?nds?verstrykning",
	frasl:"br?kstreck",
	weierp:"versalt skript-P\nexponentupps?ttning\nweierstrass-p",
	image:"versalt I\nimagin?rdelssymbol",
	real:"versalt R\nrealdelssymbol",
	trade:"varum?rkessymbol",
	alefsym:"alefsymbol",
	larr:"v?nsterpil",
	uarr:"upp?tpil",
	rarr:"h?gerpil",
	darr:"ned?tpil",
	harr:"v?nster/h?ger-pil",
	crarr:"ned?tpil ned v?nsterg?ende h?rn\nradbrytning",
	lArr:"v?nsterdubbelpil",
	uArr:"upp?tdubbelpil",
	rArr:"h?gerdubbelpil",
	dArr:"ned?tdubbelpil",
	hArr:"v?nster/h?ger-dubbelpil",
	forall:"f?r alla",
	part:"partiell differential",
	exist:"det finns",
	empty:"tom upps?ttning\nnull-upps?ttning\ndiameter",
	nabla:"nabla\nbak?tdifferens",
	isin:"element av",
	notin:"inte element av",
	ni:"inneh?ller som medlem",
	prod:"n-un?r produkt\nprodukttecken",
	sum:"n-un?r summering",
	minus:"minustecken",
	lowast:"asteriskoperator",
	radic:"kvadratrot",
	prop:"proportionellt mot",
	infin:"o?ndligheten",
	ang:"vinkel",
	and:"logiskt och",
	or:"logiskt eller",
	cap:"sk?rning",
	cup:"union","int":"integral",
	there4:"d?rf?r",
	sim:"tildeoperator\nvarierar med\nliknar",
	cong:"ungef?r lika med",
	asymp:"n?stan lika med\nasymptotiskt med",
	ne:"inte lika med",
	equiv:"identiskt med",
	le:"mindre ?n eller lika med",
	ge:"st?rre ?n eller lika med",
	sub:"delm?ngd av",
	sup:"?verordnad m?ngd till",
	nsub:"inte delm?ngd av",
	sube:"delm?ngd av eller lika med",
	supe:"?verordnad m?ngd till eller lika med",
	oplus:"plustecken i cirkel\ndirektsumma",
	otimes:"multiplikationstecken i cirkel\nvektorprodukt",
	perp:"upp?t\nortogonal mot\nvinkelr?t",
	sdot:"punktoperator",
	lceil:"v?nstertak",
	rceil:"h?gertak",
	lfloor:"v?nstergolv",
	rfloor:"h?gergolv",
	lang:"v?nstervinkelhakparentes",
	rang:"h?gervinkelhakparentes",
	loz:"romb",
	spades:"svart spader",
	clubs:"svart kl?ver\ntrekl?ver",
	hearts:"svart hj?rter",
	diams:"svart ruter",
	OElig:"versal latinsk oe-ligatur",
	oelig:"gemen latinsk oe-ligatur",
	Scaron:"versalt latinskt s med karon",
	scaron:"gement latinskt s med karon",
	Yuml:"versalt latinskt y med trema",
	circ:"modifieringscirkumflex",
	tilde:"litet tilde",
	ensp:"halvfyrkantsblanksteg",
	emsp:"fyrkantsblanksteg",
	thinsp:"tunt blanksteg",
	zwnj:"mjukt h?rfint blanksteg",
	zwj:"h?rt h?rfint blanksteg",
	lrm:"v?nster-till-h?ger-m?rke",
	rlm:"h?ger-till-v?nster-m?rke",
	ndash:"tankstreck",
	mdash:"l?ngt tankstreck",
	lsquo:"enkelt v?nstercitattecken",
	rsquo:"enkelt h?gercitattecken",
	sbquo:"enkelt underkantscitattecken",
	ldquo:"dubbelt v?nstercitattecken",
	rdquo:"dubbelt h?gercitattecken",
	bdquo:"dubbelt underkantscitattecken",
	dagger:"kors",
	Dagger:"dubbelkors",
	permil:"promille",
	lsaquo:"enkel v?nstervinkelparentes",
	rsaquo:"enkel h?gervinkelparentes",
	euro:"eurotecken"
})

//end v1.x content
);
