/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "azul alice",
antiquewhite: "branco antigo",
aqua: "aqua",
aquamarine: "?gua marinha",
azure: "azul celeste",
beige: "bege",
bisque: "bisque",
black: "preto",
blanchedalmond: "am?ndoa pelada",
blue: "azul",
blueviolet: "azul violeta",
brown: "marrom",
burlywood: "burlywood",
cadetblue: "azul cadet",
chartreuse: "chartreuse",
chocolate: "chocolate",
coral: "coral",
cornflowerblue: "azul centaurea",
cornsilk: "cornsilk",
crimson: "carmesim",
cyan: "ciano",
darkblue: "azul escuro",
darkcyan: "ciano escuro",
darkgoldenrod: "goldenrod escuro",
darkgray: "cinza escuro",
darkgreen: "verde escuro",
darkgrey: "cinza escuro", // same as darkgray
darkkhaki: "c?qui escuro",
darkmagenta: "magenta escuro",
darkolivegreen: "verde oliva escuro",
darkorange: "laranja escuro",
darkorchid: "orqu?dea escuro",
darkred: "vermelho escuro",
darksalmon: "salm?o escuro",
darkseagreen: "verde marinho escuro",
darkslateblue: "azul ard?sia escuro",
darkslategray: "cinza ard?sia escuro",
darkslategrey: "cinza ard?sia escuro", // same as darkslategray
darkturquoise: "turquesa escuro",
darkviolet: "violeta escuro",
deeppink: "rosa profundo",
deepskyblue: "azul c?u intenso",
dimgray: "cinza turvo",
dimgrey: "cinza turvo", // same as dimgray
dodgerblue: "azul dodger",
firebrick: "firebrick",
floralwhite: "branco floral",
forestgreen: "verde floresta",
fuchsia: "f?csia",
gainsboro: "gainsboro",
ghostwhite: "branco ghost",
gold: "dourado",
goldenrod: "goldenrod",
gray: "cinza",
green: "verde",
greenyellow: "amarelo esverdeado",
grey: "cinza", // same as gray
honeydew: "honeydew",
hotpink: "rosa quente",
indianred: "vermelho indiano",
indigo: "?ndigo",
ivory: "marfim",
khaki: "c?qui",
lavender: "lavanda",
lavenderblush: "lavanda avermelhada",
lawngreen: "verde grama",
lemonchiffon: "lim?o chiffon",
lightblue: "azul claro",
lightcoral: "coral claro",
lightcyan: "ciano claro",
lightgoldenrodyellow: "amarelo goldenrod claro",
lightgray: "cinza claro",
lightgreen: "verde claro",
lightgrey: "cinza claro", // same as lightgray
lightpink: "rosa claro",
lightsalmon: "salm?o claro",
lightseagreen: "verde marinho claro",
lightskyblue: "azul c?u claro",
lightslategray: "cinza ard?sia claro",
lightslategrey: "cinza ard?sia claro", // same as lightslategray
lightsteelblue: "azul a?o claro",
lightyellow: "amarelo claro",
lime: "lima",
limegreen: "verde lima",
linen: "linho",
magenta: "magenta",
maroon: "castanho",
mediumaquamarine: "?gua marinha m?dio",
mediumblue: "azul m?dio",
mediumorchid: "orqu?dea m?dio",
mediumpurple: "roxo m?dio",
mediumseagreen: "verde marinho m?dio",
mediumslateblue: "azul ard?sia m?dio",
mediumspringgreen: "verde primavera m?dio",
mediumturquoise: "turquesa m?dio",
mediumvioletred: "vermelho violeta m?dio",
midnightblue: "azul meia-noite",
mintcream: "creme de menta",
mistyrose: "rosa enevoado",
moccasin: "moccasin",
navajowhite: "branco navajo",
navy: "marinho",
oldlace: "cadar?o velho",
olive: "oliva",
olivedrab: "verde oliva",
orange: "laranja",
orangered: "vermelho alaranjado",
orchid: "orqu?dea",
palegoldenrod: "goldenrod esbranqui?ado",
palegreen: "verde esbranqui?ado",
paleturquoise: "turquesa esbranqui?ado",
palevioletred: "vermelho violeta esbranqui?ado",
papayawhip: "creme de papaya",
peachpuff: "peach puff",
peru: "peru",
pink: "rosa",
plum: "ameixa",
powderblue: "azul talco",
purple: "roxo",
red: "vermelho",
rosybrown: "marrom rosado",
royalblue: "azul royal",
saddlebrown: "marrom saddle",
salmon: "salm?o",
sandybrown: "marrom cor de areia",
seagreen: "verde marinho",
seashell: "seashell",
sienna: "sienna",
silver: "prateado",
skyblue: "azul c?u",
slateblue: "azul ard?sia",
slategray: "cinza ard?sia",
slategrey: "cinza ard?sia", // same as slategray
snow: "branco neve",
springgreen: "verde primavera",
steelblue: "azul a?o",
tan: "tan",
teal: "azul esverdeado",
thistle: "thistle",
tomato: "tomate",
turquoise: "turquesa",
violet: "violeta",
wheat: "trigo",
white: "branco",
whitesmoke: "fuma?a branca",
yellow: "amarelo",
yellowgreen: "verde amarelado"
})
//end v1.x content
);
