/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "modr? alice",
antiquewhite: "antick? biela",
aqua: "svetl? zelenomodr?",
aquamarine: "akvamar?nov?",
azure: "az?rov?",
beige: "b??ov?",
bisque: "biskvitov?",
black: "?ierna",
blanchedalmond: "l?pan? mandle",
blue: "modr?",
blueviolet: "modrofialov?",
brown: "hned?",
burlywood: "pieskovo hned?",
cadetblue: "sivomodr?",
chartreuse: "kart?za",
chocolate: "?okol?dovo hned?",
coral: "koralov?",
cornflowerblue: "nev?dzovo modr?",
cornsilk: "hodv?bna ?lt?",
crimson: "karm?nov?",
cyan: "zelenomodr?",
darkblue: "tmavomodr?",
darkcyan: "tmavozelenomodr?",
darkgoldenrod: "zlatoby?ov? tmav?",
darkgray: "tmavosiv?",
darkgreen: "tmavozelen?",
darkgrey: "tmavosiv?", // same as darkgray
darkkhaki: "?ltohned? tmav?",
darkmagenta: "tmavopurpurov?",
darkolivegreen: "olivovozelen? tmav?",
darkorange: "tmavooran?ov?",
darkorchid: "orchideovo ru?ov? tmav?",
darkred: "tmavo?erven?",
darksalmon: "lososovo ru?ov? tmav?",
darkseagreen: "morsk? zelen? tmav?",
darkslateblue: "bridlicov? modr? tmav?",
darkslategray: "bridlicov? siv? tmav?",
darkslategrey: "bridlicov? siv? tmav?", // same as darkslategray
darkturquoise: "tyrkysov? tmav?",
darkviolet: "tmavofialov?",
deeppink: "hlbok? ru?ov?",
deepskyblue: "hlbok? blankytn? modr?",
dimgray: "siv? matn?",
dimgrey: "siv? matn?", // same as dimgray
dodgerblue: "modr? dodger",
firebrick: "p?len? tehla",
floralwhite: "kvetinov? biela",
forestgreen: "lesn? zelen?",
fuchsia: "purpurov?",
gainsboro: "sivomodr? svetl?",
ghostwhite: "biely tie?",
gold: "zlat?",
goldenrod: "zlatoby?",
gray: "siv?",
green: "zelen?",
greenyellow: "?ltozelen?",
grey: "siv?", // same as gray
honeydew: "ambr?zia",
hotpink: "tepl? ru?ov?",
indianred: "indick? ?erven?",
indigo: "fialovo modr?",
ivory: "slonovinov?",
khaki: "khaki",
lavender: "levandu?ov?",
lavenderblush: "levandu?ov? rumenec",
lawngreen: "zelen? tr?va",
lemonchiffon: "citr?nov? ?if?n",
lightblue: "svetlomodr?",
lightcoral: "koralov? svetl?",
lightcyan: "zelenomodr? svetl?",
lightgoldenrodyellow: "zlatoby?ov? svetl?",
lightgray: "svetlosiv?",
lightgreen: "svetlozelen?",
lightgrey: "svetlosiv?", // same as lightgray
lightpink: "svetloru?ov?",
lightsalmon: "lososovo ru?ov? svetl?",
lightseagreen: "morsk? zelen? svetl?",
lightskyblue: "blankytn? modr? svetl?",
lightslategray: "bridlicov? siv? svetl?",
lightslategrey: "bridlicov? siv? svetl?", // same as lightslategray
lightsteelblue: "oce?ovo modr? svetl?",
lightyellow: "svetlo?lt?",
lime: "lipov?",
limegreen: "lipov? zelen?",
linen: "?an",
magenta: "purpurov?",
maroon: "ga?tanovo hned?",
mediumaquamarine: "akvamar?nov? stredn?",
mediumblue: "stredne modr?",
mediumorchid: "orchideovo ru?ov? stredn?",
mediumpurple: "purpurov? stredn?",
mediumseagreen: "morsk? zelen? stredn?",
mediumslateblue: "bridlicov? modr? stredn?",
mediumspringgreen: "jarn? zelen? stredn?",
mediumturquoise: "tyrkysov? stredn?",
mediumvioletred: "fialovo?erven? stredn?",
midnightblue: "no?n? modr?",
mintcream: "m?tov? kr?mov?",
mistyrose: "zahmlen? ru?a",
moccasin: "?rievi?n?kov?",
navajowhite: "navajsk? biela",
navy: "vojensk? zelen?",
oldlace: "star? ?ipka",
olive: "olivovo zelen?",
olivedrab: "olivovo zelen? f?dna",
orange: "oran?ov?",
orangered: "oran?ovo ?erven?",
orchid: "orchideovo ru?ov?",
palegoldenrod: "bled? zlatoby?ov?",
palegreen: "bledozelen?",
paleturquoise: "bledo tyrkysov?",
palevioletred: "bled? fialovo ?erven?",
papayawhip: "pap?jov? kr?m",
peachpuff: "brosky?ov? pena",
peru: "peru",
pink: "ru?ov?",
plum: "slivkov?",
powderblue: "pr??kov? modr?",
purple: "purpurov?",
red: "?erven?",
rosybrown: "ru?ovo hned?",
royalblue: "kr??ovsk? modr?",
saddlebrown: "sedlov? hned?",
salmon: "lososovo ru?ov?",
sandybrown: "pieskovo hned?",
seagreen: "morsk? zelen?",
seashell: "last?rov?",
sienna: "siensk?",
silver: "strieborn?",
skyblue: "blankytn? modr?",
slateblue: "bridlicov? modr?",
slategray: "bridlicov? siv?",
slategrey: "bridlicov? siv?", // same as slategray
snow: "snehobiela",
springgreen: "jarn? zelen?",
steelblue: "oce?ovo modr?",
tan: "?ltohned?",
teal: "tyrkysov?",
thistle: "bodliakov? fialov?",
tomato: "paradajkov? ?erven?",
turquoise: "tyrkysov?",
violet: "fialov?",
wheat: "p?eni?n?",
white: "biela",
whitesmoke: "biely dym",
yellow: "?lt?",
yellowgreen: "?ltozelen?"
})

//end v1.x content
);
