/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"ponto de exclama??o invertido",
	cent:"s?mbolo de centavo",
	pound:"s?mbolo de libra",
	curren:"s?mbolo de moeda",
	yen:"s?mbolo de iene\s?mbolo de yuan",
	brvbar:"barra interrompida\nbarra vertical de interrompida",
	sect:"s?mbolo de se??o",
	uml:"trema\ntrema de espa?amento",
	copy:"s?mbolo de copyright",
	ordf:"indicador ordinal feminino",
	laquo:"aspas latinas duplas de encerramento\ns?mbolo de cita??o esquerdo",
	not:"nenhum s?mbolo",
	shy:"h?fen reformat?vel\nh?fen discricion?rio",
	reg:"s?mbolo de marca registrada\ns?mbolo de marca comercial registrada",
	macr:"macron\nmacron de espa?amento\nlinha sobreposta\nbarra superior de APL",
	deg:"s?mbolo de grau",
	plusmn:"s?mbolo de mais e menos\ns?mbolo de mais ou menos",
	sup2:"dois sobrescrito\nd?gito dois sobrescrito\nraiz quadrada",
	sup3:"tr?s sobrescrito\nd?gito tr?s sobrescrito\nraiz c?bica",
	acute:"acento agudo\nacento agudo para espa?amento",
	micro:"s?mbolo de micro",
	para:"s?mbolo p?-de-mosca\ns?mbolo de par?grafo",
	middot:"ponto mediano\nv?rgula georgiana\nponto mediano grego",
	cedil:"cedilha\ncedilha para espa?amento",
	sup1:"um sobrescrito\nd?gito um sobrescrito",
	ordm:"indicador ordinal masculino",
	raquo:"aspas latinas duplas de abertura\ns?mbolo de cita??o direito",
	frac14:"fra??o de um quarto\nfra??o de um quarto",
	frac12:"fra??o de um meio\nfra??o de um meio",
	frac34:"fra??o de tr?s quartos\nfra??o de tr?s quartos",
	iquest:"ponto de interroga??o invertido\nponto de interroga??o invertido",
	Agrave:"Letra latina mai?scula A com acento grave\nletra latina mai?scula A com acento grave",
	Aacute:"Letra latina mai?scula A com acento agudo",
	Acirc:"Letra latina mai?scula A com acento circunflexo",
	Atilde:"Letra latina mai?scula A com til",
	Auml:"Letra latina mai?scula A com trema",
	Aring:"Letra latina mai?scula A com c?rculo em cima\nLetra latina mai?scula A com c?rculo",
	AElig:"Letra latina mai?scula AE\nLetra latina mai?scula AE",
	Ccedil:"Letra latina mai?scula C com cedilha",
	Egrave:"Letra latina mai?scula E com acento grave",
	Eacute:"Letra latina mai?scula E com acento agudo",
	Ecirc:"Letra latina mai?scula E com acento circunflexo",
	Euml:"Letra latina mai?scula E com trema",
	Igrave:"Letra latina mai?scula I com acento grave",
	Iacute:"Letra latina mai?scula I com acento agudo",
	Icirc:"Letra latina mai?scula I com acento circunflexo",
	Iuml:"Letra latina mai?scula I com trema",
	ETH:"Letra latina mai?scula ETH",
	Ntilde:"Letra latina mai?scula N com til",
	Ograve:"Letra latina mai?scula O com acento grave",
	Oacute:"Letra latina mai?scula O com acento agudo",
	Ocirc:"Letra latina mai?scula O com acento circunflexo",
	Otilde:"Letra latina mai?scula O com til",
	Ouml:"Letra latina mai?scula O com trema",
	times:"s?mbolo de multiplica??o",
	Oslash:"Letra latina mai?scula O tra?ada\nLetra latina mai?scula O cortada com barra",
	Ugrave:"Letra latina mai?scula U com acento grave",
	Uacute:"Letra latina mai?scula U com acento agudo",
	Ucirc:"Letra latina mai?scula U com acento circunflexo",
	Uuml:"Letra latina mai?scula U com trema",
	Yacute:"Letra latina mai?scula Y com acento agudo",
	THORN:"Letra latina mai?scula THORN",
	szlig:"Letra latina min?scula scharfes S\ness-zed",
	agrave:"Letra latina min?scula a com acento grave\nletra latina min?scula a com acento grave",
	aacute:"Letra latina min?scula a com acento agudo",
	acirc:"Letra latina min?scula a com acento circunflexo",
	atilde:"Letra latina min?scula a com til",
	auml:"Letra latina min?scula a com trema",
	aring:"Letra latina min?scula a com c?rculo em cima\nLetra latina min?scula a com c?rculo",
	aelig:"Letra latina min?scula ae\nLetra latina min?scula ae contra?da",
	ccedil:"Letra latina min?scula c com cedilha",
	egrave:"Letra latina min?scula e com acento grave",
	eacute:"Letra latina min?scula e com acento agudo",
	ecirc:"Letra latina min?scula e com acento circunflexo",
	euml:"Letra latina min?scula e com trema",
	igrave:"Letra latina min?scula i com acento grave",
	iacute:"Letra latina min?scula i com acento agudo",
	icirc:"Letra latina min?scula i com acento circunflexo",
	iuml:"Letra latina min?scula i com trema",
	eth:"Letra latina min?scula eth",
	ntilde:"Letra latina min?scula n com til",
	ograve:"Letra latina min?scula o com acento grave",
	oacute:"Letra latina min?scula o com acento agudo",
	ocirc:"Letra latina min?scula o com acento circunflexo",
	otilde:"Letra latina min?scula o com til",
	ouml:"Letra latina min?scula o com trema",
	divide:"s?mbolo de divis?o",
	oslash:"Letra latina min?scula o tra?ada\nLetra latina min?scula o cortada com barra",
	ugrave:"Letra latina min?scula u com acento grave",
	uacute:"Letra latina min?scula u com acento agudo",
	ucirc:"Letra latina min?scula u com acento circunflexo",
	uuml:"Letra latina min?scula u com trema",
	yacute:"Letra latina min?scula y com acento agudo",
	thorn:"Letra latina min?scula thorn",
	yuml:"Letra latina min?scula y com trema",

// Greek Characters and Symbols
	fnof:"Letra latina min?scula f com gancho\nfun??o\nflorim",
	Alpha:"Letra grega mai?scula alfa",
	Beta:"Letra grega mai?scula beta",
	Gamma:"Letra grega mai?scula gama",
	Delta:"Letra grega mai?scula delta",
	Epsilon:"Letra grega mai?scula ?psilon",
	Zeta:"Letra grega mai?scula zeta",
	Eta:"Letra grega mai?scula eta",
	Theta:"Letra grega mai?scula teta",
	Iota:"Letra grega mai?scula iota",
	Kappa:"Letra grega mai?scula capa",
	Lambda:"Letra grega mai?scula lambda",
	Mu:"Letra grega mai?scula miu",
	Nu:"Letra grega mai?scula nu",
	Xi:"Letra grega mai?scula ksi",
	Omicron:"Letra grega mai?scula ?micron",
	Pi:"Letra grega mai?scula pi",
	Rho:"Letra grega mai?scula r?",
	Sigma:"Letra grega mai?scula sigma",
	Tau:"Letra grega mai?scula tau",
	Upsilon:"Letra grega mai?scula upsilon",
	Phi:"Letra grega mai?scula fi",
	Chi:"Letra grega mai?scula chi",
	Psi:"Letra grega mai?scula psi",
	Omega:"Letra grega mai?scula ?mega",
	alpha:"Letra grega min?scula alfa",
	beta:"Letra grega min?scula beta",
	gamma:"Letra grega min?scula gama",
	delta:"Letra grega min?scula delta",
	epsilon:"Letra grega min?scula ?psilon",
	zeta:"Letra grega min?scula zeta",
	eta:"Letra grega min?scula eta",
	theta:"Letra grega min?scula teta",
	iota:"Letra grega min?scula iota",
	kappa:"Letra grega min?scula capa",
	lambda:"Letra grega min?scula lambda",
	mu:"Letra grega min?scula miu",
	nu:"Letra grega min?scula nu",
	xi:"Letra grega min?scula ksi",
	omicron:"Letra grega min?scula ?micron",
	pi:"Letra grega min?scula pi",
	rho:"Letra grega min?scula r?",
	sigmaf:"Letra grega min?scula sigma final",
	sigma:"Letra grega min?scula sigma",
	tau:"Letra grega min?scula tau",
	upsilon:"Letra grega min?scula upsilon",
	phi:"Letra grega min?scula fi",
	chi:"Letra grega min?scula chi",
	psi:"Letra grega min?scula psi",
	omega:"Letra grega min?scula ?mega",
	thetasym:"S?mbolo da letra grega min?scula teta",
	upsih:"S?mbolo da letra grega upsilon com gancho",
	piv:"S?mbolo grego pi",
	bull:"marcador\npequeno c?rculo preto",
	hellip:"retic?ncias horizontais\ntr?s pontos",
	prime:"linha simples\nminutos\np?s",
	Prime:"linha dupla\nsegundos\npolegadas",
	oline:"linha sobreposta\nlinha superior para espa?amento",
	frasl:"barra de fra??o",
	weierp:"P mai?sculo cursivo\npot?ncia\np de Weierstrass",
	image:"letra I mai?scula g?tica\nparte imagin?ria",
	real:"letra R mai?scula g?tica\ns?mbolo da parte real",
	trade:"s?mbolo de marca registrada",
	alefsym:"s?mbolo alef\nprimeiro cardinal transfinito",
	larr:"seta para esquerda",
	uarr:"seta para cima",
	rarr:"seta para direita",
	darr:"seta para baixo",
	harr:"seta para esquerda e direita",
	crarr:"seta para baixo com curva para esquerda\nretorno de texto",
	lArr:"seta dupla para esquerda",
	uArr:"seta dupla para cima",
	rArr:"seta dupla para direita",
	dArr:"seta dupla para baixo",
	hArr:"seta dupla para esquerda e direita",
	forall:"para todos",
	part:"diferen?a parcial",
	exist:"existe pelo menos",
	empty:"conjunto vazio\nconjunto nulo\ndi?metro",
	nabla:"nabla\ngradiente",
	isin:"pertence a",
	notin:"n?o pertence a",
	ni:"cont?m",
	prod:"produto de n elementos\ns?mbolo de produto",
	sum:"somat?rio de n elementos",
	minus:"sinal de menos",
	lowast:"asterisco",
	radic:"raiz quadrada\ns?mbolo de radical",
	prop:"proporcional a",
	infin:"infinito",
	ang:"?ngulo",
	and:"'e' l?gico\nwedge",
	or:"'ou' l?gico\nvee",
	cap:"intersec??o\nintersec??o",
	cup:"uni?o\nreuni?o","int":"integral",
	there4:"para isso",
	sim:"operador til\nvaria com\nigual a",
	cong:"aproximadamente igual a",
	asymp:"quase igual a\nassint?tico a",
	ne:"diferente de",
	equiv:"id?ntico a",
	le:"menor ou igual a",
	ge:"maior ou igual a",
	sub:"est? contido em",
	sup:"cont?m",
	nsub:"n?o est? contido em",
	sube:"est? contido ou ? igual a",
	supe:"cont?m ou ? igual a",
	oplus:"c?rculo mais\nsoma direta",
	otimes:"s?mbolo de vezes circulado\nproduto dos vetores",
	perp:"up tack\nortogonal a\nperpendicular",
	sdot:"ponto de multiplica??o",
	lceil:"chave em L com o canto voltado para cima ? esquerda\nAPL com o canto voltado para cima",
	rceil:"chave em L com o canto voltado para cima ? direita",
	lfloor:"chave em L com o canto voltado para baixo ? esquerda\nAPL com o canto voltado para baixo",
	rfloor:"chave em L com o canto voltado para baixo ? direita",
	lang:"sinal de maior e menor para esquerda",
	rang:"sinal de maior e menor para direita",
	loz:"losango",
	spades:"s?mbolo de espadas",
	clubs:"s?mbolo de paus\ntrevo",
	hearts:"cora??o negro\ns?mbolo de copas",
	diams:"diamante negro",
	OElig:"Liga??o latina mai?scula OE",
	oelig:"Liga??o latina min?scula oe",
	Scaron:"Letra latina mai?scula S com caron",
	scaron:"Letra latina min?scula s com caron",
	Yuml:"Letra latina mai?scula Y com trema",
	circ:"Acento circunflexo",
	tilde:"til pequeno",
	ensp:"espa?o simples",
	emsp:"espa?o duplo",
	thinsp:"espa?o estreito",
	zwnj:"separador de largura zero",
	zwj:"conector de largura zero",
	lrm:"marca da esquerda para a direita",
	rlm:"marca da direita para a esquerda",
	ndash:"tra?o",
	mdash:"travess?o",
	lsquo:"aspas simples ? esquerda",
	rsquo:"aspas simples ? direita",
	sbquo:"aspas simples inferior ? direita",
	ldquo:"aspas duplas inferior ? esquerda",
	rdquo:"aspas duplas ? direita",
	bdquo:"aspas duplas inferiores ? direita",
	dagger:"cruz",
	Dagger:"cruz dupla",
	permil:"s?mbolo por mil",
	lsaquo:"aspa latina de encerramento",
	rsaquo:"aspa latina de abertura",
	euro:"s?mbolo de euro"
})
//end v1.x content
);
