/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"signe d'exclamaci? obert",
	cent:"signe de c?ntims",
	pound:"signe de lliura",
	curren:"signe de moneda",
	yen:"signe de ien\nsigne de iuan",
	brvbar:"barra partida\nbarra vertical partida",
	sect:"signe de secci?",
	uml:"di?resi\ndi?resi d'espai",
	copy:"signe de copyright",
	ordf:"indicador ordinal femen?",
	laquo:"cometes llatines apuntant cap a l'esquerra\ncometes llatines cap a l'esquerra",
	not:"signe de negaci?",
	shy:"gui? tou\ngui? opcional",
	reg:"signe de registrat\nsigne de marca comercial registrada",
	macr:"macron\nmacron d'espaiat\nsobre-ratllat\ngui? alt",
	deg:"signe de graus",
	plusmn:"signe de m?s-menys\nsigne de m?s-o-menys",
	sup2:"dos en super?ndex\nn?mero dos en super?ndex\nal quadrat",
	sup3:"tres en super?ndex\nn?mero tres en super?ndex\nal cub",
	acute:"accent agut\nespaiat agut",
	micro:"signe de micro",
	para:"signe de par?grafn\nsigne de canvi de par?graf",
	middot:"punt volat\ncoma georgiana\npunt volat grec",
	cedil:"ce trencada\nespai de ce trencada",
	sup1:"? en super?ndex\nn?mero ? en super?ndex",
	ordm:"indicador d'ordinal mascul?",
	raquo:"cometes llatines apuntant cap a la dreta\ncometes llatines cap a la dreta",
	frac14:"fracci? vulgar d'un quart\nfracci? d'un quart",
	frac12:"fracci? vulgar de meitat\nfracci? d'un mig",
	frac34:"fracci? vulgar de tres quarts\nfracci? de tres quarts",
	iquest:"signe d'interrogaci? obert\ninterrogaci? oberta",
	Agrave:"lletra llatina A maj?scula amb accent greu\nA maj?scula amb accent greu",
	Aacute:"lletra llatina A maj?scula amb accent agut\nA maj?scula amb accent agut",
	Acirc:"lletra llatina A maj?scula amb circumflex\nA maj?scula amb circumflex",
	Atilde:"lletra llatina A maj?scula amb titlla",
	Auml:"lletra llatina A maj?scula amb di?resi",
	Aring:"lletra llatina A maj?scula amb anell al damunt\nA maj?scula amb anell",
	AElig:"lletra llatina AE maj?scula\n Lligatura llatina AE maj?scula",
	Ccedil:"lletra llatina C trencada maj?scula",
	Egrave:"lletra llatina E maj?scula amb accent greu",
	Eacute:"lletra llatina E maj?scula amb accent agut",
	Ecirc:"lletra llatina E maj?scula amb circumflex",
	Euml:"lletra llatina E maj?scula amb di?resi",
	Igrave:"lletra llatina I maj?scula amb accent greu",
	Iacute:"lletra llatina I maj?scula amb accent agut",
	Icirc:"lletra llatina I maj?scula amb circumflex",
	Iuml:"lletra llatina I maj?scula amb di?resi",
	ETH:"lletra llatina ETH maj?scula",
	Ntilde:"lletra llatina N maj?scula amb titlla\nlletra enye maj?scula",
	Ograve:"lletra llatina O maj?scula amb accent greu",
	Oacute:"lletra llatina O maj?scula amb accent agut",
	Ocirc:"lletra llatina O maj?scula amb circumflex",
	Otilde:"lletra llatina O maj?scula amb titlla",
	Ouml:"lletra llatina O maj?scula amb di?resi",
	times:"signe de multiplicaci?",
	Oslash:"lletra llatina O maj?scula amb tra?at\nO maj?scula amb barra inclinada",
	Ugrave:"lletra llatina U maj?scula amb accent greu",
	Uacute:"lletra llatina U maj?scula amb accent agut",
	Ucirc:"lletra llatina U maj?scula amb circumflex",
	Uuml:"lletra llatina U maj?scula amb di?resi",
	Yacute:"lletra llatina Y maj?scula amb accent agut",
	THORN:"lletra llatina THORN maj?scula",
	szlig:"lletra llatina s fina\nesze alemanya",
	agrave:"Lletra llatina a min?scula amb accent greu\na min?scula amb accent greu",
	aacute:"lletra llatina a min?scula amb accent agut",
	acirc:"lletra llatina a min?scula amb circumflex",
	atilde:"lletra llatina a min?scula amb titlla",
	auml:"lletra llatina a min?scula amb di?resi",
	aring:"Lletra llatina a min?scula amb anell\na min?scula amb anell",
	aelig:"lletra llatina AE min?scula\n Lligatura llatina AE min?scula",
	ccedil:"lletra llatina c trencada min?scula",
	egrave:"lletra llatina e min?scula amb accent greu",
	eacute:"lletra llatina e min?scula amb accent agut",
	ecirc:"lletra llatina e min?scula amb circumflex",
	euml:"lletra llatina e min?scula amb di?resi",
	igrave:"lletra llatina i min?scula amb accent greu",
	iacute:"lletra llatina i min?scula amb accent agut",
	icirc:"lletra llatina i min?scula amb circumflex",
	iuml:"lletra llatina i min?scula amb di?resi",
	eth:"lletra llatina eth min?scula",
	ntilde:"lletra llatina n min?scula amb titlla\nlletra enye min?scula",
	ograve:"lletra llatina o min?scula amb accent greu",
	oacute:"lletra llatina o min?scula amb accent agut",
	ocirc:"lletra llatina o min?scula amb circumflex",
	otilde:"lletra llatina o min?scula amb titlla",
	ouml:"lletra llatina o min?scula amb di?resi",
	divide:"signe de divisi?",
	oslash:"lletra llatina o min?scula amb tra?at\no min?scula amb barra inclinada",
	ugrave:"lletra llatina u min?scula amb accent greu",
	uacute:"lletra llatina u min?scula amb accent agut",
	ucirc:"lletra llatina u min?scula amb circumflex",
	uuml:"lletra llatina u min?scula amb di?resi",
	yacute:"lletra llatina y min?scula amb accent agut",
	thorn:"lletra llatina thorn min?scula",
	yuml:"lletra llatina y min?scula amb di?resi",

// Greek Characters and Symbols
	fnof:"lletra llatina f min?scula amb ganxet\nfunci?\nflor?",
	Alpha:"lletra grega alfa maj?scula",
	Beta:"lletra grega beta maj?scula",
	Gamma:"lletra grega gamma maj?scula",
	Delta:"lletra grega delta maj?scula",
	Epsilon:"lletra grega epsilon maj?scula",
	Zeta:"lletra grega zeta maj?scula",
	Eta:"lletra grega eta maj?scula",
	Theta:"lletra grega theta maj?scula",
	Iota:"lletra grega iota maj?scula",
	Kappa:"lletra grega kappa maj?scula",
	Lambda:"lletra grega lambda maj?scula",
	Mu:"lletra grega mu maj?scula",
	Nu:"lletra grega nu maj?scula",
	Xi:"lletra grega xi maj?scula",
	Omicron:"lletra grega omicron maj?scula",
	Pi:"lletra grega pi maj?scula",
	Rho:"lletra grega rho maj?scula",
	Sigma:"lletra grega sigma maj?scula",
	Tau:"lletra grega tau maj?scula",
	Upsilon:"lletra grega upsilon maj?scula",
	Phi:"lletra grega phi maj?scula",
	Chi:"lletra grega chi maj?scula",
	Psi:"lletra grega psi maj?scula",
	Omega:"lletra grega omega maj?scula",
	alpha:"lletra grega alfa min?scula",
	beta:"lletra grega beta min?scula",
	gamma:"lletra grega gamma min?scula",
	delta:"lletra grega delta min?scula",
	epsilon:"lletra grega epsilon min?scula",
	zeta:"lletra grega zeta min?scula",
	eta:"lletra grega eta min?scula",
	theta:"lletra grega theta min?scula",
	iota:"lletra grega iota min?scula",
	kappa:"lletra grega kappa min?scula",
	lambda:"lletra grega lambda min?scula",
	mu:"lletra grega mu min?scula",
	nu:"lletra grega nu min?scula",
	xi:"lletra grega xi min?scula",
	omicron:"lletra grega omicron min?scula",
	pi:"lletra grega pi min?scula",
	rho:"lletra grega rho min?scula",
	sigmaf:"lletra grega sigma final min?scula",
	sigma:"lletra grega sigma min?scula",
	tau:"lletra grega tau min?scula",
	upsilon:"lletra grega upsilon min?scula",
	phi:"lletra grega phi min?scula",
	chi:"lletra grega chi min?scula",
	psi:"lletra grega psi min?scula",
	omega:"lletra grega omega min?scula",
	thetasym:"s?mbol de lletra grega theta min?scula",
	upsih:"s?mbol de lletra grega upsilon amb ganxet",
	piv:"s?mbol grec de pi",
	bull:"vinyeta\npetit cercle negre",
	hellip:"el?lipsi horitzontal\nguia de tres punts",
	prime:"prima\nminuts\npeus",
	Prime:"doble prima\nsegons\npolzades",
	oline:"sobre-ratllat\nespai de gui? alt",
	frasl:"barra de fracci?",
	weierp:"lletra P maj?scula de script\nconjunt de pot?ncia\np de Weierstrass",
	image:"I maj?scula negra\npart imagin?ria",
	real:"R maj?scula negra\ns?mbol de part real",
	trade:"signe de marca registrada",
	alefsym:"s?mbol d'alef\nprimer cardinal transfinit",
	larr:"fletxa cap a l'esquerra",
	uarr:"fletxa cap amunt",
	rarr:"fletxa cap a la dreta",
	darr:"fletxa cap avall",
	harr:"fletxa a esquerra i dreta",
	crarr:"fletxa cap avall amb cantonada a l'esquerra\nretorn de carro",
	lArr:"doble fletxa cap a l'esquerra",
	uArr:"doble fletxa cap amunt",
	rArr:"doble fletxa cap a la dreta",
	dArr:"doble fletxa cap avall",
	hArr:"doble fletxa a esquerra i dreta",
	forall:"per a tot",
	part:"diferencial parcial",
	exist:"existeix",
	empty:"conjunt buit\nconjunt nul\ndi?metre",
	nabla:"nabla\ndifer?ncia cap enrere",
	isin:"?s element de",
	notin:"no ?s element de",
	ni:"cont? com a membre",
	prod:"producte n-ari\nsigne de producte",
	sum:"sumatori n-ari",
	minus:"signe menys",
	lowast:"operador asterisc",
	radic:"arrel quadrada\nsigne de radical",
	prop:"proporcional a",
	infin:"infinit",
	ang:"angle",
	and:"i l?gic\nfalca",
	or:"o l?gica\nvall",
	cap:"intersecci?\nbarret",
	cup:"uni?\ncopa","int":"integral",
	there4:"per tant",
	sim:"operador de titlla\nvaria amb\nsemblant a",
	cong:"aproximadament igual que",
	asymp:"gaireb? igual que\nasint?tic amb",
	ne:"no igual que",
	equiv:"id?ntic a",
	le:"menor o igual que",
	ge:"major o igual que",
	sub:"sots-conjunt de",
	sup:"super-conjunt de",
	nsub:"no ?s un sots-conjunt de",
	sube:"sots-conjunt de o igual que",
	supe:"super-conjunt de o igual que",
	oplus:"m?s encerclat\nsuma directa",
	otimes:"multiplicaci? encerclada\nproducte de vectors",
	perp:"clau aixecat\nortogonal a\nperpendicular",
	sdot:"operador de punt",
	lceil:"sostre esquerre\nAPL amunt",
	rceil:"sostre dret",
	lfloor:"terra esquerre\nAPL avall",
	rfloor:"terra dret",
	lang:"claud?tor angular apuntant a l'esquerra",
	rang:"claud?tor angular apuntant a la dreta",
	loz:"rombe",
	spades:"pal de piques negre",
	clubs:"pal de tr?bols negre\ntr?bol",
	hearts:"pal de cors negre\nsant valent?",
	diams:"pal de diamants negre",
	OElig:"lligatura llatina OE maj?scula",
	oelig:"lligatura llatina oe min?scula",
	Scaron:"lletra llatina S maj?scula amb circumflex invertit",
	scaron:"lletra llatina s min?scula amb circumflex invertit",
	Yuml:"lletra llatina Y maj?scula amb di?resi",
	circ:"modificador de lletra d'accent circumflex",
	tilde:"titlla petita",
	ensp:"espai en",
	emsp:"espai em",
	thinsp:"espai prim",
	zwnj:"no-uni? d'ample zero",
	zwj:"uni? d'ample zero",
	lrm:"marca d'esquerra-a-dreta",
	rlm:"marca de dreta-a-esquerra",
	ndash:"gui? en",
	mdash:"gui? em",
	lsquo:"marca de citaci? senzilla esquerra",
	rsquo:"marca de citaci? senzilla dreta",
	sbquo:"marca de citaci? de 9-baix senzilla",
	ldquo:"marca de citaci? doble esquerra",
	rdquo:"marca de citaci? doble dreta",
	bdquo:"marca de citaci? de 9-baix doble",
	dagger:"daga",
	Dagger:"doble daga",
	permil:"signe de tant per mil",
	lsaquo:"marca de citaci? en angle senzilla esquerra",
	rsaquo:"marca de citaci? en angle senzilla dreta",
	euro:"signe de l'euro"
})

//end v1.x content
);
