/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "bleu gris",
antiquewhite: "blanc antique",
aqua: "bleu-vert",
aquamarine: "aigue-marine",
azure: "bleu azur",
beige: "beige",
bisque: "beige ros?",
black: "noir",
blanchedalmond: "coquille d'oeuf",
blue: "bleu",
blueviolet: "bleu-violet",
brown: "brun",
burlywood: "bois pr?cieux",
cadetblue: "bleu p?trole",
chartreuse: "vert vif",
chocolate: "chocolat",
coral: "corail",
cornflowerblue: "bleuet",
cornsilk: "vanille",
crimson: "cramoisi",
cyan: "cyan",
darkblue: "bleu fonc?",
darkcyan: "cyan fonc?",
darkgoldenrod: "jaune paille fonc?",
darkgray: "gris fonc?",
darkgreen: "vert fonc?",
darkgrey: "gris fonc?", // same as darkgray
darkkhaki: "kaki fonc?",
darkmagenta: "magenta fonc?",
darkolivegreen: "olive fonc?",
darkorange: "orange fonc?",
darkorchid: "lilas fonc?",
darkred: "rouge fonc?",
darksalmon: "saumon fonc?",
darkseagreen: "vert d'eau fonc?",
darkslateblue: "bleu ardoise fonc?",
darkslategray: "gris ardoise fonc?",
darkslategrey: "gris ardoise fonc?", // same as darkslategray
darkturquoise: "turquoise fonc?",
darkviolet: "violet fonc?",
deeppink: "rose soutenu",
deepskyblue: "bleu ciel soutenu",
dimgray: "gris soutenu",
dimgrey: "gris soutenu", // same as dimgray
dodgerblue: "bleu France",
firebrick: "rouge brique",
floralwhite: "lys",
forestgreen: "vert sapin",
fuchsia: "fuchsia",
gainsboro: "gris souris",
ghostwhite: "blanc laiteux",
gold: "or",
goldenrod: "jaune paille",
gray: "gris",
green: "vert",
greenyellow: "vert-jaune",
grey: "gris", // same as gray
honeydew: "opalin",
hotpink: "rose intense",
indianred: "rose indien",
indigo: "indigo",
ivory: "ivoire",
khaki: "kaki",
lavender: "lavande",
lavenderblush: "lavandin",
lawngreen: "vert prairie",
lemonchiffon: "mousse de citron",
lightblue: "bleu clair",
lightcoral: "corail clair",
lightcyan: "cyan clair",
lightgoldenrodyellow: "jaune paille clair",
lightgray: "gris clair",
lightgreen: "vert clair",
lightgrey: "gris clair", // same as lightgray
lightpink: "rose clair",
lightsalmon: "saumon clair",
lightseagreen: "vert d'eau clair",
lightskyblue: "bleu ciel clair",
lightslategray: "gris ardoise clair",
lightslategrey: "gris ardoise clair", // same as lightslategray
lightsteelblue: "bleu acier clair",
lightyellow: "jaune clair",
lime: "vert citron",
limegreen: "citron vert",
linen: "?cru",
magenta: "magenta",
maroon: "marron",
mediumaquamarine: "aigue-marine moyen",
mediumblue: "bleu moyen",
mediumorchid: "lilas moyen",
mediumpurple: "pourpre moyen",
mediumseagreen: "vert d'eau moyen",
mediumslateblue: "bleu ardoise moyen",
mediumspringgreen: "vert printemps moyen",
mediumturquoise: "turquoise moyen",
mediumvioletred: "rouge violac? moyen",
midnightblue: "bleu nuit",
mintcream: "cr?me de menthe",
mistyrose: "rose p?le",
moccasin: "chamois",
navajowhite: "chair",
navy: "bleu marine",
oldlace: "blanc cass?",
olive: "olive",
olivedrab: "brun verd?tre",
orange: "orange",
orangered: "rouge orang?",
orchid: "lilas",
palegoldenrod: "jaune paille p?le",
palegreen: "vert p?le",
paleturquoise: "turquoise p?le",
palevioletred: "rouge violac? p?le",
papayawhip: "cr?me de papaye",
peachpuff: "p?che",
peru: "caramel",
pink: "rose",
plum: "prune",
powderblue: "bleu de smalt",
purple: "pourpre",
red: "rouge",
rosybrown: "vieux rose",
royalblue: "bleu roi",
saddlebrown: "brun cuir",
salmon: "saumon",
sandybrown: "sable",
seagreen: "vert d'eau",
seashell: "coquillage",
sienna: "terre de sienne",
silver: "argent",
skyblue: "bleu ciel",
slateblue: "bleu ardoise",
slategray: "gris ardoise",
slategrey: "gris ardoise", // same as slategray
snow: "neige",
springgreen: "vert printemps",
steelblue: "bleu acier",
tan: "gr?ge",
teal: "sarcelle",
thistle: "chardon",
tomato: "tomate",
turquoise: "turquoise",
violet: "violet",
wheat: "bl?",
white: "blanc",
whitesmoke: "blanc cendr?",
yellow: "jaune",
yellowgreen: "vert jaun?tre"
})
//end v1.x content
);
