/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"signo de exclamaci?n inicial",
	cent:"s?mbolo de centavos",
	pound:"s?mbolo libra esterlina",
	curren:"s?mbolo monetario",
	yen:"s?mbolo del yen\ns?mbolo de yuan",
	brvbar:"barra dividida\nbarra vertical dividida",
	sect:"signo de secci?n",
	uml:"di?resis\ndi?resis de espaciado",
	copy:"s?mbolo de copyright",
	ordf:"indicador de ordinal femenino",
	laquo:"comillas dobles en ?ngulo a la izquierda",
	not:"signo de negaci?n",
	shy:"signo de gui?n corto",
	reg:"s?mbolo de registrado\ns?mbolo de marca registrada",
	macr:"macr?n\ndiacr?tico largo\nl?nea superior\nbarra superior APL",
	deg:"signo de grados",
	plusmn:"signo de m?s-menos\nsigno de m?s o menos",
	sup2:"super?ndice dos\nsuper?ndice de d?gito dos\nelevado al cuadrado",
	sup3:"super?ndice tres\nsuper?ndice de d?gito tres\nelevado al cubo",
	acute:"acento agudo\nagudo de espaciado",
	micro:"signo de micro",
	para:"signo de p?rrafo",
	middot:"punto medio\ncoma georgiana\npunto medio griego",
	cedil:"cedilla\ncedilla de espaciado",
	sup1:"super?ndice uno\nsuper?ndice de d?gito uno",
	ordm:"indicador de ordinal masculino",
	raquo:"comillas dobles en ?ngulo a la derecha",
	frac14:"fracci?n de cuarto vulgar\nfracci?n de cuarto",
	frac12:"fracci?n de medio vulgar\nfracci?n de medio",
	frac34:"fracci?n de tres cuartos vulgar\nfracci?n de tres cuartos",
	iquest:"signo de interrogaci?n inicial\nsigno de apertura de interrogaci?n",
	Agrave:"letra A latina may?scula con acento grave\nletra A latina may?scula grave",
	Aacute:"letra A latina may?scula con acento agudo",
	Acirc:"letra A latina may?scula con acento circunflejo",
	Atilde:"letra A latina may?scula con virgulilla\nletra A latina may?scula con tilde",
	Auml:"letra A latina may?scula con di?resis",
	Aring:"letra A latina may?scula con anillo encima\nletra A latina may?scula con anillo",
	AElig:"diptongo AE latinas may?sculas\nligadura de AE latinas may?sculas",
	Ccedil:"letra C latina may?scula con cedilla",
	Egrave:"letra E latina may?scula con acento grave",
	Eacute:"letra E latina may?scula con acento agudo",
	Ecirc:"letra E latina may?scula con acento circunflejo",
	Euml:"letra E latina may?scula con acento di?resis",
	Igrave:"letra I latina may?scula con acento grave",
	Iacute:"letra I latina may?scula con acento agudo",
	Icirc:"letra I latina may?scula con acento circunflejo",
	Iuml:"letra I latina may?scula con di?resis",
	ETH:"letra ETH latina may?scula",
	Ntilde:"letra N latina may?scula con virgulilla\nletra N latina may?scula con tilde\nletra ? latina may?scula",
	Ograve:"letra O latina may?scula con acento grave",
	Oacute:"letra O latina may?scula con acento agudo",
	Ocirc:"letra O latina may?scula con acento circunflejo",
	Otilde:"letra O latina may?scula con virgulilla\nletra O latina may?scula con tilde",
	Ouml:"letra O latina may?scula con di?resis",
	times:"signo de multiplicaci?n",
	Oslash:"letra O latina may?scula con barra\nletra O latina may?scula con barra inclinada",
	Ugrave:"letra U latina may?scula con acento grave",
	Uacute:"letra U latina may?scula con acento agudo",
	Ucirc:"letra U latina may?scula con acento circunflejo",
	Uuml:"letra U latina may?scula con di?resis",
	Yacute:"letra Y latina may?scula con acento agudo",
	THORN:"letra THORN latina may?scula",
	szlig:"letra s fuerte latina min?scula\nEszet",
	agrave:"letra a latina min?scula con acento grave\nletra a latina min?scula grave",
	aacute:"letra a latina min?scula con acento agudo",
	acirc:"letra a latina min?scula con acento circunflejo",
	atilde:"letra a latina min?scula con virgulilla\nletra a latina min?scula con tilde",
	auml:"letra a latina min?scula con di?resis",
	aring:"letra a latina min?scula con anillo encima\nletra a latina min?scula con anillo",
	aelig:"Diptongo ae latinas min?sculas\nligadura de ae latinas min?sculas",
	ccedil:"letra c latina min?scula con cedilla",
	egrave:"letra e latina min?scula con acento grave",
	eacute:"letra e latina min?scula con acento agudo",
	ecirc:"letra e latina min?scula con acento circunflejo",
	euml:"letra e latina min?scula con di?resis",
	igrave:"letra i latina min?scula con acento grave",
	iacute:"letra i latina min?scula con acento agudo",
	icirc:"letra i latina min?scula con acento circunflejo",
	iuml:"letra i latina min?scula con di?resis",
	eth:"letra eth latina min?scula",
	ntilde:"letra n latina min?scula con virgulilla\nletra n latina min?scula con tilde",
	ograve:"letra o latina min?scula con acento grave",
	oacute:"letra o latina min?scula con acento agudo",
	ocirc:"letra o latina min?scula con acento circunflejo",
	otilde:"letra o latina min?scula con virgulilla\nletra o latina min?scula con tilde",
	ouml:"letra o latina min?scula con di?resis",
	divide:"signo de divisi?n",
	oslash:"letra o latina min?scula con barra\nletra o latina min?scula con barra inclinada",
	ugrave:"letra u latina min?scula con acento grave",
	uacute:"letra u latina min?scula con acento agudo",
	ucirc:"letra u latina min?scula con acento circunflejo",
	uuml:"letra u latina min?scula con di?resis",
	yacute:"letra y latina min?scula con acento agudo",
	thorn:"letra thorn latina min?scula",
	yuml:"letra y latina min?scula con di?resis",

// Greek Characters and Symbols
	fnof:"letra f latina min?scula con gancho\nfunci?n\nflor?n",
	Alpha:"letra alpha griega may?scula",
	Beta:"letra beta griega may?scula",
	Gamma:"letra gamma griega may?scula",
	Delta:"letra delta griega may?scula",
	Epsilon:"letra ?psilon griega may?scula",
	Zeta:"letra zeta griega may?scula",
	Eta:"letra eta griega may?scula",
	Theta:"letra theta griega may?scula",
	Iota:"letra iota griega may?scula",
	Kappa:"letra kappa griega may?scula",
	Lambda:"letra lambda griega may?scula",
	Mu:"letra mu griega may?scula",
	Nu:"letra nu griega may?scula",
	Xi:"letra xi griega may?scula",
	Omicron:"letra ?micron griega may?scula",
	Pi:"letra pi griega may?scula",
	Rho:"letra rho griega may?scula",
	Sigma:"letra sigma griega may?scula",
	Tau:"letra tau griega may?scula",
	Upsilon:"letra ?psilon griega may?scula",
	Phi:"letra phi griega may?scula",
	Chi:"letra chi griega may?scula",
	Psi:"letra psi griega may?scula",
	Omega:"letra omega griega may?scula",
	alpha:"letra alpha griega min?scula",
	beta:"letra beta griega min?scula",
	gamma:"letra gamma griega min?scula",
	delta:"letra delta griega min?scula",
	epsilon:"letra ?psilon griega min?scula",
	zeta:"letra zeta griega min?scula",
	eta:"letra eta griega min?scula",
	theta:"letra theta griega min?scula",
	iota:"letra iota griega min?scula",
	kappa:"letra kappa griega min?scula",
	lambda:"letra lambda griega min?scula",
	mu:"letra mu griega min?scula",
	nu:"letra nu griega min?scula",
	xi:"letra xi griega min?scula",
	omicron:"letra ?micron griega min?scula",
	pi:"letra pi griega min?scula",
	rho:"letra rho griega min?scula",
	sigmaf:"letra sigma final griega min?scula",
	sigma:"letra sigma griega min?scula",
	tau:"letra tau griega min?scula",
	upsilon:"letra ?psilon griega min?scula",
	phi:"letra phi griega min?scula",
	chi:"letra chi griega min?scula",
	psi:"letra psi griega min?scula",
	omega:"letra omega griega min?scula",
	thetasym:"s?mbolo de letra theta griega min?scula",
	upsih:"s?mbolo de letra ?psilon griega con gancho",
	piv:"s?mbolo pi griego",
	bull:"vi?eta\nc?rculo negro peque?o",
	hellip:"puntos suspensivos",
	prime:"s?mbolo primo\nminutos\npies",
	Prime:"s?mbolo primo doble\nsegundos\npulgadas",
	oline:"sobrel?nea\nsobre la letra",
	frasl:"barra de fracci?n",
	weierp:"letra P may?scula cursiva",
	image:"letra I may?scula\nn?meros imaginarios",
	real:"letra R may?scula\nn?meros reales",
	trade:"s?mbolo de marca registrada",
	alefsym:"s?mbolo alef\nprimer n?mero transfinito",
	larr:"flecha a la izquierda",
	uarr:"flecha hacia arriba",
	rarr:"flecha a la derecha",
	darr:"flecha hacia abajo",
	harr:"flecha izquierda-derecha",
	crarr:"flecha esquinada abajo a la izquierda\nretorno de carro",
	lArr:"doble flecha a la izquierda",
	uArr:"doble flecha hacia arriba",
	rArr:"doble flecha a la derecha",
	dArr:"doble flecha hacia abajo",
	hArr:"doble flecha izquierda-derecha",
	forall:"para todo",
	part:"derivada parcial",
	exist:"existe",
	empty:"conjunto vac?o\nconjunto nulo\ndi?metro",
	nabla:"nabla\ngradiente",
	isin:"pertenece",
	notin:"no pertenece",
	ni:"est? incluido",
	prod:"productoria\nmultiplicatoria",
	sum:"sumatoria",
	minus:"signo menos",
	lowast:"operador asterisco",
	radic:"ra?z cuadrada\nsigno radical",
	prop:"proporcional",
	infin:"infinito",
	ang:"?ngulo",
	and:"y l?gico\ncu?a",
	or:"o l?gico\nuve",
	cap:"intersecci?n\nconjuntos",
	cup:"uni?n\nconjuntos","int":"integral",
	there4:"por lo tanto",
	sim:"operador de tilde\nno l?gico\nparecido a",
	cong:"aproximadamente igual a",
	asymp:"parecido\ncasi igual a",
	ne:"no igual a",
	equiv:"id?ntico a",
	le:"menor o igual que",
	ge:"mayor o igual que",
	sub:"subconjunto de",
	sup:"superconjunto de",
	nsub:"no un subconjunto de",
	sube:"subconjunto de o igual a",
	supe:"superconjunto de o igual a",
	oplus:"m?s en c?rculo\nsuma directa",
	otimes:"cruz en c?rculo\nproducto vectorial",
	perp:"ortogonal a\nperpendicular",
	sdot:"operador punto",
	lceil:"parte superior de corchete abierto",
	rceil:"parte superior de corchete cerrado",
	lfloor:"parte inferior de corchete abierto",
	rfloor:"parte inferior de corchete abierto",
	lang:"corchete angular hacia la izquierda",
	rang:"corchete angular hacia la derecha",
	loz:"rombo",
	spades:"palo de picas",
	clubs:"palo de tr?boles",
	hearts:"palo de corazones",
	diams:"palo de diamantes",
	OElig:"ligadura de OE latinas may?sculas",
	oelig:"ligadura de oe latinas min?sculas",
	Scaron:"letra S latina may?scula con anticircunflejo",
	scaron:"letra s latina min?scula con anticircunflejo",
	Yuml:"letra Y latina may?scula con di?resis",
	circ:"acento circunflejo",
	tilde:"tilde peque?a",
	ensp:"espacio",
	emsp:"espacio largo",
	thinsp:"espacio estrecho",
	zwnj:"separador de anchura cero",
	zwj:"conector de anchura cero",
	lrm:"marca de izquierda a derecha",
	rlm:"marca de derecha a izquierda",
	ndash:"gui?n",
	mdash:"gui?n largo",
	lsquo:"comilla simple abierta",
	rsquo:"comilla simple cerrada",
	sbquo:"comilla simple inferior",
	ldquo:"comillas dobles abiertas",
	rdquo:"comillas dobles cerradas",
	bdquo:"comillas dobles inferiores",
	dagger:"daga",
	Dagger:"daga doble",
	permil:"signo de por mil",
	lsaquo:"comilla simple angular abierta",
	rsaquo:"comilla simple angular cerrada",
	euro:"signo del euro"
})

//end v1.x content
);
