/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space\nnon-breaking space",
		quot:"quote",
	*/
	iexcl:"ford?tott felki?lt?jel",
	cent:"cent jel",
	pound:"font jel",
	curren:"p?nznem jel",
	yen:"jen jel\nyuan jel",
	brvbar:"megszak?tott vonal\nmegszak?tott f?gg?leges vonal",
	sect:"paragrafusjel",
	uml:"dupla ?kezet\numlaut",
	copy:"copyright jel",
	ordf:"n?nem? sorsz?mn?v jelz?se a fels? indexben",
	laquo:"balra mutat? dupla hegyes id?z?jel\nbalra mutat? bels? id?z?jel",
	not:"nem jel",
	shy:"l?gy k?t?jel\nfelt?teles k?t?jel",
	reg:"v?djegy jel\nbejegyzett v?djegy jel",
	macr:"f?l?h?z?s jel\nAPL fel?lh?z?s",
	deg:"fok jel",
	plusmn:"plus-m?nusz jel\nplusz-vagy-m?nusz jel",
	sup2:"2 fels? indexben\nfels? indexbe ?rt kettes sz?mjegy\nn?gyzetre emel?s",
	sup3:"3 fels? indexben\nfels? indexbe ?rt h?rmas sz?mjegy\nk?bre emel?s",
	acute:"hegyes ?kezet\nkalapos ?kezet",
	micro:"mikro jel",
	para:"sorv?ge jel\nbekezd?s jel",
	middot:"k?z?ps? pont\nGregori?n vessz?\nG?r?g k?z?ps? pont",
	cedil:"cedill\nbalra hajl? als? hurok",
	sup1:"1 a fels? indexben\nfels? indexbe ?rt egyes sz?mjegy",
	ordm:"h?mnem? sorsz?mn?v jelz?se a fels? indexben",
	raquo:"jobbra mutat? dupla hegyes id?z?jel\njobbra mutat? bels? id?z?jel",
	frac14:"k?z?ns?ges egynegyed t?rt\nnegyed",
	frac12:"k?z?ns?ges f?l t?rt\nf?l",
	frac34:"k?z?ns?ges h?romnegyed t?rt\nh?romnegyed",
	iquest:"ford?tott k?rd?jel\nmegford?tott k?rd?jel",
	Agrave:"Latin nagy A bet? tompa ?kezettel\nTompa ?kezetes latin nagy A bet?",
	Aacute:"Latin nagy A bet? ?les ?kezettel",
	Acirc:"Latin kalapos nagy A bet?",
	Atilde:"Latin hull?mvonalas nagy A bet?",
	Auml:"Latin k?tpontos nagy A bet?",
	Aring:"Latin nagy A bet? fel?l k?rrel\nLatin nagy A bet? fels? k?rrel",
	AElig:"Latin nagy AE\nLatin nagy AE ikerbet?",
	Ccedil:"Latin nagy C bet? cedillel",
	Egrave:"Latin nagy E bet? tompa ?kezettel",
	Eacute:"Latin nagy E bet? ?les ?kezettel",
	Ecirc:"Latin kalapos nagy E bet?",
	Euml:"Latin k?tpontos nagy E bet?",
	Igrave:"Latin nagy I bet? tompa ?kezettel",
	Iacute:"Latin nagy I bet? ?les ?kezettel",
	Icirc:"Latin kalapos nagy I bet?",
	Iuml:"Latin k?tpontos nagy I bet?",
	ETH:"Latin nagy ETH bet?",
	Ntilde:"Latin hull?mvonalas nagy N bet?",
	Ograve:"Latin nagy O bet? tompa ?kezettel",
	Oacute:"Latin nagy O bet? ?les ?kezettel",
	Ocirc:"Latin kalapos nagy O bet?",
	Otilde:"Latin hull?mvonalas nagy O bet?",
	Ouml:"Latin k?tpontos nagy O bet?",
	times:"szorz?sjel",
	Oslash:"Latin ?th?zott nagy O bet?\nLatin nagy O bet? oszt?sjellel",
	Ugrave:"Latin nagy U bet? tompa ?kezettel",
	Uacute:"Latin nagy U bet? ?les ?kezettel",
	Ucirc:"Latin kalapos nagy U bet?",
	Uuml:"Latin k?tpontos nagy U bet?",
	Yacute:"Latin nagy Y bet? ?les ?kezettel",
	THORN:"Latin nagy THORN bet?",
	szlig:"Latin kis sharfes s\neszett",
	agrave:"Latin kis a bet? tompa ?kezettel\nTompa ?kezetes latin kis a bet?",
	aacute:"Latin kis a bet? ?les ?kezettel",
	acirc:"Latin kalapos kis a bet?",
	atilde:"Latin hull?mvonalas kis a bet?",
	auml:"Latin k?tpontos kis a bet?",
	aring:"Latin kis a bet? fel?l k?rrel\nLatin kis a bet? fels? k?rrel",
	aelig:"Latin kis ae bet?\nLatin kis ae ikerbet?",
	ccedil:"Latin kis c bet? cedillel",
	egrave:"Latin kis e bet? tompa ?kezettel",
	eacute:"Latin kis e bet? ?les ?kezettel",
	ecirc:"Latin kalapos kis e bet?",
	euml:"Latin k?tpontos kis e bet?",
	igrave:"Latin kis i bet? tompa ?kezettel",
	iacute:"Latin kis i bet? ?les ?kezettel",
	icirc:"Latin kalapos kis i bet?",
	iuml:"Latin k?tpontos kis i bet?",
	eth:"Latin kis eth bet?",
	ntilde:"Latin hull?mvonalas kis n bet?",
	ograve:"Latin kis o bet? tompa ?kezettel",
	oacute:"Latin kis o bet? ?les ?kezettel",
	ocirc:"Latin kalapos kis o bet?",
	otilde:"Latin hull?mvonalas kis o bet?",
	ouml:"Latin k?tpontos kis o bet?",
	divide:"oszt?sjel",
	oslash:"Latin ?th?zott kis o bet?\nLatin kis o bet? oszt?sjellel",
	ugrave:"Latin kis u bet? tompa ?kezettel",
	uacute:"Latin kis u bet? ?les ?kezettel",
	ucirc:"Latin kalapos kis u bet?",
	uuml:"Latin k?tpontos kis u bet?",
	yacute:"Latin kis y ?les ?kezettel",
	thorn:"Latin kis thorn bet?",
	yuml:"Latin k?tpontos kis y",

// Greek Characters and Symbols
	fnof:"Latin kis f horoggal\nf?ggv?ny\nforint",
	Alpha:"G?r?g nagy alfa bet?",
	Beta:"G?r?g nagy b?ta bet?",
	Gamma:"G?r?g nagy gamma bet?",
	Delta:"G?r?g nagy delta bet?",
	Epsilon:"G?r?g nagy epszilon bet?",
	Zeta:"G?r?g nagy dz?ta bet?",
	Eta:"G?r?g nagy ?ta bet?",
	Theta:"G?r?g nagy th?ta bet?",
	Iota:"G?r?g nagy iota bet?",
	Kappa:"G?r?g nagy kappa bet?",
	Lambda:"G?r?g nagy lambda bet?",
	Mu:"G?r?g nagy m? bet?",
	Nu:"G?r?g nagy n? bet?",
	Xi:"G?r?g nagy ksz? bet?",
	Omicron:"G?r?g nagy omikron bet?",
	Pi:"G?r?g nagy pi bet?",
	Rho:"G?r?g nagy r? bet?",
	Sigma:"G?r?g nagy szigma bet?",
	Tau:"G?r?g nagy tau bet?",
	Upsilon:"G?r?g nagy ?pszilon bet?",
	Phi:"G?r?g nagy f? bet?",
	Chi:"G?r?g nagy kh? bet?",
	Psi:"G?r?g nagy psz? bet?",
	Omega:"G?r?g nagy ?mega bet?",
	alpha:"G?r?g kis alfa bet?",
	beta:"G?r?g kis b?ta bet?",
	gamma:"G?r?g kis gamma bet?",
	delta:"G?r?g kis delta bet?",
	epsilon:"G?r?g kis epszilon bet?",
	zeta:"G?r?g kis dz?ta bet?",
	eta:"G?r?g kis ?ta bet?",
	theta:"G?r?g kis th?ta bet?",
	iota:"G?r?g kis i?ta bet?",
	kappa:"G?r?g kis kappa bet?",
	lambda:"G?r?g kis lambda bet?",
	mu:"G?r?g kis m? bet?",
	nu:"G?r?g kis n? bet?",
	xi:"G?r?g kis ksz? bet?",
	omicron:"G?r?g kis omikron bet?",
	pi:"G?r?g kis p? bet?",
	rho:"G?r?g kis r? bet?",
	sigmaf:"G?r?g kis szigma bet? utols? helyen",
	sigma:"G?r?g kis szigma bet?",
	tau:"G?r?g kis ta? bet?",
	upsilon:"G?r?g kis ?pszilon bet?",
	phi:"G?r?g kis f? bet?",
	chi:"G?r?g kis kh? bet?",
	psi:"G?r?g kis psz? bet?",
	omega:"G?r?g kis ?mega bet?",
	thetasym:"G?r?g kis th?ta bet? szimb?lum",
	upsih:"G?r?g ?pszilon horog szimb?lummal",
	piv:"G?r?g p? szimb?lum",
	bull:"pont felsorol?sjel\nkis fekete k?r",
	hellip:"v?zszintes h?rmaspont\nbevezet? h?rmas pont",
	prime:"szimpla egyenes id?z?jel\nperc\nl?b",
	Prime:"dupla egyenes id?z?jel\nm?sodperc\nh?velyk",
	oline:"fels? vonal\nfel?lvon?s",
	frasl:"t?rt oszt?sjel",
	weierp:"?rott nagy P\nhatv?nyhalmaz\nWeierstrass p",
	image:"megt?rt nagy I\nk?pzetes (imagin?rius) r?sz",
	real:"megt?rt nagy R\nval?s r?sz szimb?lum",
	trade:"v?djegy jel",
	alefsym:"alef szimb?lum\nels? transzfinit pozit?v eg?sz sz?m",
	larr:"balra mutat? ny?l",
	uarr:"felfel? mutat? ny?l",
	rarr:"jobbra mutat? ny?l",
	darr:"lefel? mutat? ny?l",
	harr:"balra-jobbra mutat? ny?l",
	crarr:"lefel? mutat? ny?l bal oldalon sarokkal\nsoremel?s",
	lArr:"balra mutat? dupla ny?l",
	uArr:"felfel? mutat? dupla ny?l",
	rArr:"jobbra mutat? dupla ny?l",
	dArr:"lefel? mutat? dupla ny?l",
	hArr:"balra-jobbra mutat? dupla ny?l",
	forall:"minden\nford?tott nagy A bet?",
	part:"r?szleges differenci?l",
	exist:"l?tezik",
	empty:"?res halmaz\nnull halmaz\n?tm?r?",
	nabla:"nabla\nford?tott k?l?nbs?g",
	isin:"eleme",
	notin:"nem eleme",
	ni:"tagk?nt tartalmazza",
	prod:"n-tag? Descartes szorzat\nszorzatjel",
	sum:"n-tag? ?sszegz?s",
	minus:"m?nusz jel",
	lowast:"csillag oper?tor",
	radic:"n?gyzetgy?k\nn?gyzetgy?k jel",
	prop:"ar?nyos",
	infin:"v?gtelen",
	ang:"sz?g",
	and:"logikai ?s\n?k",
	or:"logikai vagy\nv-alak",
	cap:"metszet",
	cup:"uni?","int":"integr?l",
	there4:"ez?rt",
	sim:"hull?m oper?tor\nv?ltakozik\nhasonl?",
	cong:"megk?zel?t?leg egyenl?",
	asymp:"majdnem egyenl?\naszimptotikus",
	ne:"nem egyenl?",
	equiv:"azonos",
	le:"kisebb vagy egyenl?",
	ge:"nagyobb vagy egyenl?",
	sub:"r?szhalmaza",
	sup:"b?v?tett halmaza",
	nsub:"nem r?szhalmaza",
	sube:"r?szhalmaza vagy egyenl?",
	supe:"b?v?tett halmaza vagy egyenl?",
	oplus:"bekarik?zott plusz jel\nk?zvetlen ?sszeg",
	otimes:"bekarik?zott x\nvektor szorzat",
	perp:"mer?leges\nortogon?lis",
	sdot:"pont oper?tor",
	lceil:"bal sz?gletes z?r?jel fels? sarok\nAPL fels? keret",
	rceil:"jobb sz?gletes z?r?jel fels? sarok",
	lfloor:"bal sz?gletes z?r?jel als? sarok\nAPL als? keret",
	rfloor:"jobb sz?gletes z?r?jel als? sarok",
	lang:"balra mutat? hegyes z?r?jel",
	rang:"jobbra mutat? hegyes z?r?jel",
	loz:"rombusz",
	spades:"fekete pikk k?rtyajel",
	clubs:"fekete treff k?rtyjel\nl?here",
	hearts:"fekete k?r k?rtyajel\nsz?valak",
	diams:"fekete k?r? k?ryajel",
	OElig:"Latin nagy OE ikerbet?",
	oelig:"Latin kis oe ikerbet?",
	Scaron:"Latin nagy S bet? cs?nakkal",
	scaron:"Latin kis s bet? cs?nakkal",
	Yuml:"Latin k?tpontos nagy Y bet?",
	circ:"bet?t m?dos?t? kalap ?kezet",
	tilde:"kis hull?m",
	ensp:"n sz?k?z",
	emsp:"m sz?k?z",
	thinsp:"sz?k sz?k?z",
	zwnj:"t?rhet? ?res jel",
	zwj:"nem t?rhet? ?res jel",
	lrm:"balr?l jobbra jel",
	rlm:"jobbr?l balra jel",
	ndash:"n k?t?jel",
	mdash:"m k?t?jel",
	lsquo:"bal szimpla id?z?jel",
	rsquo:"jobb szimpla id?z?jel",
	sbquo:"als? 9-es szimpla id?z?jel",
	ldquo:"bal dupla id?z?jel",
	rdquo:"jobb dupla id?z?jel",
	bdquo:"als? 9-es dupla id?z?jel",
	dagger:"kereszt",
	Dagger:"dupla kereszt",
	permil:"ezrel?kjel",
	lsaquo:"szimpla balra mutat? hegyes id?z?jel",
	rsaquo:"szimpla jobbra mutat? hegyes id?z?jel",
	euro:"euro jel"
})

//end v1.x content
);
