/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color e.g. gray vs. gray.
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "Alice-blau",
antiquewhite: "Antikwei?",
aqua: "Wasserblau",
aquamarine: "Aquamarin",
azure: "Azur",
beige: "Beige",
bisque: "Bisquit",
black: "Schwarz",
blanchedalmond: "Mandelwei?",
blue: "Blau",
blueviolet: "Blauviolett",
brown: "Braun",
burlywood: "Burlywood",
cadetblue: "Kadettenblau",
chartreuse: "Helles Gelbgr?n",
chocolate: "Schokoladenbraun",
coral: "Koralle",
cornflowerblue: "Kornblumenblau",
cornsilk: "Kornseide",
crimson: "Karmesinrot",
cyan: "Zyan",
darkblue: "Dunkelblau",
darkcyan: "Dunkelzyan",
darkgoldenrod: "Dunkelgoldgelb",
darkgray: "Dunkelgrau",
darkgreen: "Dunkelgr?n",
darkgrey: "Dunkelgrau", // same as darkgray
darkkhaki: "Dunkelkhaki",
darkmagenta: "Dunkelmagenta",
darkolivegreen: "Dunkelolivgr?n",
darkorange: "Dunkelorange",
darkorchid: "Dunkelorchidee",
darkred: "Dunkelrot",
darksalmon: "Dunkellachs",
darkseagreen: "Dunkles Meergr?n",
darkslateblue: "Dunkelschieferblau",
darkslategray: "Dunkelschiefergrau",
darkslategrey: "Dunkelschiefergrau", // same as darkslategray
darkturquoise: "Dunkelt?rkis",
darkviolet: "Dunkelviolett",
deeppink: "Tiefrosa",
deepskyblue: "Dunkles Himmelblau",
dimgray: "Blassgrau",
dimgrey: "Blassgrau", // same as dimgray
dodgerblue: "Dodger-blau",
firebrick: "Schamottestein",
floralwhite: "Bl?tenwei?",
forestgreen: "Forstgr?n",
fuchsia: "Fuchsia",
gainsboro: "Gainsboro",
ghostwhite: "Geisterwei?",
gold: "Gold",
goldenrod: "Goldgelb",
gray: "Grau",
green: "Gr?n",
greenyellow: "Gr?ngelb",
grey: "Grau", // same as gray
honeydew: "Honigtau",
hotpink: "Knallrosa",
indianred: "Indischrot",
indigo: "Indigoblau",
ivory: "Elfenbein",
khaki: "Khaki",
lavender: "Lavendelblau",
lavenderblush: "Lavendelhauch",
lawngreen: "Grasgr?n",
lemonchiffon: "Zitronenchiffon",
lightblue: "Hellblau",
lightcoral: "Hellkoralle",
lightcyan: "Hellzyan",
lightgoldenrodyellow: "Hellgoldgelb",
lightgray: "Hellgrau",
lightgreen: "Hellgr?n",
lightgrey: "Hellgrau", // same as lightgray
lightpink: "Hellrosa",
lightsalmon: "Helllachs",
lightseagreen: "Helles Meergr?n",
lightskyblue: "Helles Himmelblau",
lightslategray: "Helles Schiefergrau",
lightslategrey: "Helles Schiefergrau", // same as lightslategray
lightsteelblue: "Helles Stahlblau",
lightyellow: "Hellgelb",
lime: "Limone",
limegreen: "Limonengr?n",
linen: "Leinen",
magenta: "Magenta",
maroon: "Kastanienbraun",
mediumaquamarine: "Mittelaquamarin",
mediumblue: "Mittelblau",
mediumorchid: "Mittelorchidee",
mediumpurple: "Mittelpurpur",
mediumseagreen: "Mittelmeeresgr?n",
mediumslateblue: "Mittelschieferblau ",
mediumspringgreen: "Mittelfr?hlingsgr?n",
mediumturquoise: "Mittelt?rkis ",
mediumvioletred: "Mittelviolettrot ",
midnightblue: "Mitternachtblau",
mintcream: "Mintcreme",
mistyrose: "Blassrose",
moccasin: "Mokassin",
navajowhite: "Navajo-wei?",
navy: "Marineblau",
oldlace: "Alte Spitze",
olive: "Oliv",
olivedrab: "Olivgrau",
orange: "Orange",
orangered: "Orangerot",
orchid: "Orchidee",
palegoldenrod: "Blassgoldgelb",
palegreen: "Blassgr?n",
paleturquoise: "Blasst?rkis",
palevioletred: "Blassviolettrot ",
papayawhip: "Papayacreme",
peachpuff: "Pfirsich",
peru: "Peru",
pink: "Rosa",
plum: "Pflaume",
powderblue: "Pulverblau",
purple: "Purpurrot",
red: "Rot",
rosybrown: "Rosigbraun",
royalblue: "K?nigsblau",
saddlebrown: "Sattelbraun",
salmon: "Lachs",
sandybrown: "Sandbraun",
seagreen: "Meeresgr?n",
seashell: "Muschelwei?",
sienna: "Sienna",
silver: "Silbergrau",
skyblue: "Himmelblau",
slateblue: "Schieferblau",
slategray: "Schiefergrau",
slategrey: "Schiefergrau", // same as slategray
snow: "Schneewei?",
springgreen: "Fr?hlingsgr?n",
steelblue: "Stahlblau",
tan: "Hautfarben",
teal: "Smaragdgr?n",
thistle: "Distel",
tomato: "Tomatenrot",
turquoise: "T?rkis",
violet: "Violett",
wheat: "Weizen",
white: "Wei?",
whitesmoke: "Rauchwei?",
yellow: "Gelb",
yellowgreen: "Gelbgr?n"
})
//end v1.x content
);
